s|TAG_TITLE_NAME|Aishwarya Rai|g
s|TAG_KEYWORD_ACTRESS_NAME|aishwarya rai, aish, ash, cannes, abhishek bachchan, Aishwarya Rai Bachchan, Miss World|g
s|TAG_DESC_ACTRESS_NAME|Aishwarya Rai (Aishwarya Rai Bachchan) is an Indian  actress and former Miss World (1994). She worked as a model before her acting career.|g
s|TAG_ALT_ACTRESS_NAME|Aishwarya Rai, Aishwarya Bachchan|g
s|TAG_DIR_NAME_1|actress|g
s|TAG_DIR_ACTRESS_NAME|aishwarya_rai|g
#
s|TAG_ACTRESS_LONG_DESC|Aishwarya Rai (Aishwarya Rai Bachchan) is an Indian  actress and former Miss World (1994). She worked as a model before her acting career. Aishwarya has acted in movies in Hindi, English, Tamil and Bengali which also includes some international productions like The Pink Panther 2, Provoked, The Last LegionMistress of Spices, Bride and Prejudice. Aishwarya was featured in Dabboo Ratnani Calendar 2007. Aishwarya Rai has a wax model in at the world famous Madame Tussauds waxwork museum in London.|g
#
s|TAG_GOOGLE_ADLINKS|4774102528|g
#
s|TAG_NUM_OF_IMAGES|165|g
#
s|TAG_OTHER_FACTS|03/22/2006: Announced that Aishwarya Rai would be the brand ambassador for Coca-Cola in the new Thande Ka Tadka campaign.<br>Aishwarya Rai has a wax model in at the world famous Madame Tussauds waxwork museum in London.|g
#
s|TAG_FILMOGRAPHY_2004_2005_MOVIE_RELEASES|<A ALT="" TITLE="Bunty Aur Babli Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2005/bunty_aur_babli.html">Bunty Aur Babli (2005)</A> As Special Appearance (song: Kajra Ra)<br>Shabd (2005) As Antara Vashisht<br>Bride and Prejudice (2004) As Lalita Bakshi<br>Kyun...! Ho Gaya Na (2004) As Diya Malhotra<br>Raincoat (2004) As Neerja/Neeru<br>Khakee (2004) As Mahalaxshmi|g
s|TAG_FILMOGRAPHY_2006_MOVIE_RELEASES|Singularity (2006) As Tulaja<br>Akbar-Jodha (2006) As Jodha Bhai<br><A ALT="" TITLE="Dhoom 2 Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/dhoom_2.html">Dhoom 2 (2006)</A><br><A ALT="" TITLE="The Last Legion Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/the_last_legion.html">The Last Legion (2006)</A> As Mira<br><A ALT="" TITLE="Umrao Jaan Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/umrao_jaan.html">Umrao Jaan (2006)</A> As Umrao Jaan<br>The Heart of India (2006) As Mumtaz Mahal<br><A ALT="" TITLE="Mistress of Spices Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/mistress_of_spices.html">Mistress of Spices (2006)</A> As Tilo|g
#
s|TAG_MOVIES_WORKED_ON|josh, hamara dil aapke paas hai, mohabbatein, albela, hum tumhare hain sanam, shakti, dil ka rishta, kondukandain kondukondain, devdas, hum dil de chuke sanam, hum kisse se kum nahi, bride and prejudice, Ravoyi Chandamama (1999) As Special Appearance (Song). Other Title: Shankar (India: Tamil title) As <br>Taal (1999) As Mansi. Other Title: Thaalam (India: Tamil title) As <br>Hum Dil De Chuke Sanam (1999) As Nandini. Other Title: Straight from the Heart (International: English title) As <br>Aa Ab Laut Chalen (1999) As Pooja Walia. Other Title: Lets Go Back (International: English title) As <br>Jeans (1998) As Madhumitha/Vaishnavi <br>Aur Pyaar Ho Gaya (1997) As Ashi Kapoor <br>Iruvar (1997) As Pushpa/Kalpana. Other Title: Iddaru (India: Telugu title: dubbed version) As Kuch Naa Kaho (2003) As Namrata Shrivastav. Other Titles: Don't Say a Word (International: English title: informal literal title) As <br>Chokher Bali (2003) As Binodini. Other Titles: Choker Bali: A Passion Play (International: English title). Other Titles: Sand in the Eye (India: English title) As <br>Dil Ka Rishta (2003) As Tia Sharma. Other Titles: Heart of Gold (International: English title). Other Titles: Relationships of Hearts (International: English title: informal literal title) As <br>Shakti: The Power (2002) As Dream Girl. <br>23rd March 1931: Shaheed (2002) As Special Appearance (song)<br>Hum Kisi Se Kum Nahin (2002) As Komal Rastogi<br>Hum Tumhare Hain Sanam (2002) As Special Appearence <br>Devdas (2002) As Parvati ('Paro') As <br>Albela (2001) As Sonia <br>Mohabbatein (2000) As Megha. Other Titles: Love Stories (Europe: English title) As <br>Dhaai Akshar Prem Ke (2000) As Sahiba Gareval <br>Hamara Dil Aapke Paas Hai (2000) As Preeti Virat. Other Titles: You Have My Heart (International: English title: informal title) As <br>Josh (2000) As Shirley<br>Kandukondain Kandukondain (2000) As Meenakshi. Other Titles: I Have Found It (International: English title). Other Titles: Priyuraalu Pilichindi (India: Telugu title: dubbed version) As <br>Mela (2000) As Champakali <br>Sanam Tere Hain Hum (2000) As Special AppearanceMistress of Spices (2005) As Tilo<br>Bunty Aur Babli (2005) As Special Appearance (song: Kajra Ra)<br>Shabd (2005) As Antara Vashisht<br>Bride and Prejudice (2004) As Lalita Bakshi<br>Kyun...! Ho Gaya Na (2004) As Diya Malhotra<br>Raincoat (2004) As Neerja/Neeru<br>Khakee (2004) As Mahalaxshmi|g
#
s|TAG_PHOTO_LATEST_NEWS|<A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_21.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_183.jpg" ALT="Aishwarya Rai" TITLE="Aishwarya Rai" WIDTH="100" HEIGHT="100" BORDER="0"> </A> <b>Aishwarya Rai Bachchan On Cover Of Vogue India February 2011</b> <br> Date: <A ALT="" TITLE="Aishwarya Rai Bachchan On Cover Of Vogue India February 2011" HREF="http://www.bollywoodmovies.us/news/2011/01_31_2011.html">02/02/2011</A>: <br> The Vogue India Feruary 2011 cover feature Miss World <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> wearing a black dress with angel wings and all. The magazine includes interviews with some of her closets friends, including husband Abhishek Bachchan, designer Manish Malhotra, director Ashutosh Gowariker and make up artist Mickey Contractor.<br><hr size="1" width="100%">|g
#
s|<!--TAG_ADD_FAVICON_START||g
s|TAG_ADD_FAVICON_END-->||g
