s|TAG_TITLE_NAME|Koena Mitra|g
s|TAG_KEYWORD_ACTRESS_NAME|koena mitra|g
s|TAG_DESC_ACTRESS_NAME|koena mitra|g
s|TAG_ALT_ACTRESS_NAME|Koena Mitra|g
s|TAG_DIR_NAME_1|actress|g
s|TAG_DIR_ACTRESS_NAME|koena_mitra|g
#
s|TAG_ACTRESS_LONG_DESC|TAG_ACTRESS_LONG_DESC|g
