s|TAG_TITLE_NAME|Mugdha Godse|g
s|TAG_KEYWORD_ACTRESS_NAME|mugdha godse, actress|g
s|TAG_DESC_ACTRESS_NAME|Mugdha Godse is an Indian actress.|g
#
s|TAG_ALT_ACTRESS_NAME|Mugdha Godse|g
s|TAG_DIR_NAME_1|actress|g
s|TAG_DIR_ACTRESS_NAME|mugdha_godse|g
s|TAG_ACTRESS_LONG_DESC|Mugdha Godse is an Indian actress.|g
#
s|TAG_PHOTO_LATEST_NEWS|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/mugdha_godse/bollywood_mugdha_godse_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/mugdha_godse/pics/mugdha_godse_13.jpg" ALT="Mugdha Godse Maxim India September 2010" TITLE="Mugdha Godse Maxim India September 2010" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Mugdha Godse On Cover Of Maxim India September 2010 Issue</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Mugdha Godse On Cover Of Maxim India September 2010 Issue" HREF="http://www.bollywoodmovies.us/news/2010/09_20_2010.html">09/20/2010</A>: </font> <br> <A ALT="" TITLE="Mugdha Godse" HREF="http://www.bollywoodmovies.us/actress/mugdha_godse/bollywood_mugdha_godse.html">Mugdha Godse</A> is being featured on the cover of September 2010 edition of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . The photos will be part of the Maxim India September 2010 edition. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --> <A HREF="http://www.bollywoodmovies.us/actress/mugdha_godse/bollywood_mugdha_godse_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/mugdha_godse/pics/mugdha_godse_06.jpg" ALT="Mugdha Godse Stuff February 2009" TITLE="Mugdha Godse Stuff February 2009" WIDTH="100" HEIGHT="100" BORDER="0"> </A> <b>Mugdha Godse On Cover Of Stuff India February 2009 Issue</b> <br> Date: <A ALT="" TITLE="Mugdha Godse On Cover Of Stuff India February 2009 Issue" HREF="http://www.bollywoodmovies.us/news/2009/02_02_2009.html">02/07/2009</A>: <br> <A ALT="" TITLE="Mugdha Godse" HREF="http://www.bollywoodmovies.us/actress/mugdha_godse/bollywood_mugdha_godse.html">Mugdha Godse</A> is being featured on the cover of February 2009 edition of <A ALT="" TITLE="Stuff India" HREF="http://www.bollywoodmovies.us/info/stuff_magazine.html">Stuff India</A> . The photos will be part of the Stuff India February 2009 edition. Mugdha was last seen in the movie <A ALT="" TITLE="Fashion Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/fashion.html">Fashion (2008)</A> .<br><hr size="1" width="100%">|g
