s|TAG_META_TITLE|Jennifer Love Hewitt|g
s|TAG_META_KEYWORDS|jennifer love hewitt, Maxim May 2009, Maxim Hot 100 List|g
s|TAG_META_DESCRIPTION|jennifer love hewitt, Maxim May 2009, Maxim Hot 100 List|g
#
s|TAG_BIOGRAPHY_1|<b>Jennifer Love Hewitt</b> was born on February 21, 1979 in Waco, Texas, U.S.A.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Jennifer is an American actress, singer and songwriter. She is well known of her roles on TV shows like Party of Five (1995-1999) and Ghost Whisperer. She has also acted in movies like I Know What You Did Last Summer (1997), The Tuxedo (2002) and The Truth About Love (2004). <BR>In 2008 she was ranked num 76 on the AskMen.com Top 99 Women list. <BR> In 2007 she was ranked num 91 on the AskMen.com Top 99 Women list.|g
#
#
s|TAG_BIO_2007_LATEST_NEWS|<!-- HOLLYWOOD_NEWS_STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="white"> <A HREF="http://www.bollywoodmovies.us/hollywood/actress/jennifer_love_hewitt/hollywood_jennifer_love_hewitt_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/actress/jennifer_love_hewitt/pics/jennifer_love_hewitt_01.jpg" ALT="Hollywood Jennifer Love Hewitt" TITLE="Hollywood Jennifer Love Hewitt" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="white"> <b>Jennifer Love Hewitt Fights Back</b> <br> Date: <A ALT="" TITLE="Jennifer Love Hewitt" HREF="http://www.bollywoodmovies.us/news/2007/12_10_2007.html">12/13/2007</A> <br> <A ALT="" TITLE="Jennifer Love Hewitt" HREF="http://www.bollywoodmovies.us/hollywood/actress/jennifer_love_hewitt/hollywood_jennifer_love_hewitt.html">Jennifer Love Hewitt</A> is angry and upset about some paparazzi shots that surfaced on the Internet of her on vacation with fiance Ross McCall. More then the photos she is upset with the comment about her weight that accompanied the photos. Jennifer is currently starrring in TV show Ghost Whisperer. </TD> </TR> <!-- HOLLYWOOD_NEWS_STORY_END -->|g
#
#
#
s|TAG_BIO_LATEST_NEWS|<b>House's Olivia Wilde Tops Maxim Hot 100 List</b> <br> Date: <A ALT="" TITLE="House's Olivia Wilde Tops Maxim Hot 100 List" HREF="http://www.bollywoodmovies.us/news/2009/05_11_2009.html">05/13/2009</A>: <br> Fox's hit medical drama House's <A ALT="" TITLE="Olivia Wilde" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/olivia_wilde/celebrites_olivia_wilde.html">Olivia Wilde</A> topped the list of the Maxim 2009 Hot 100 unveiled today. For the first time, the First Lady of the United States made the list. First lady, <A ALT="" TITLE="Michelle Obama" HREF="http://www.bollywoodmovies.us/famous_person/michelle_obama/famous_person_michelle_obama.html">Michelle Obama</A> showed on the list at number 93. The top 10 on the list are: <A ALT="" TITLE="Megan Fox" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/megan_fox/celebrites_megan_fox.html">Megan Fox</A> , <A ALT="" TITLE="Bar Refaeli" HREF="http://www.bollywoodmovies.us/models/bar_refaeli/models_bar_refaeli.html">Bar Refaeli</A> , <A ALT="" TITLE="Malin Akerman" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/malin_akerman/celebrites_malin_akerman.html">Malin Akerman</A> , <A ALT="" TITLE="Mila Kunis" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/mila_kunis/celebrites_mila_kunis.html">Mila Kunis</A> , <A ALT="" TITLE="Eliza Dushku" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/eliza_dushku/celebrites_eliza_dushku.html">Eliza Dushku</A> , <A ALT="" TITLE="Adriana Lima" HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima.html">Adriana Lima</A> , <A ALT="" TITLE="Rihanna" HREF="http://www.bollywoodmovies.us/hollywood/artists/rihanna/hollywood_rihanna.html">Rihanna</A> , <A ALT="" TITLE="Jordana Brewster" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/jordana_brewster/celebrites_jordana_brewster.html">Jordana Brewster</A> , <A ALT="" TITLE="Jennifer Love Hewitt" HREF="http://www.bollywoodmovies.us/hollywood/actress/jennifer_love_hewitt/hollywood_jennifer_love_hewitt.html">Jennifer Love Hewitt</A> .<br><hr size="1" width="100%"><b>Jennifer Love Hewitt On Cover Of Maxim May 2009 Issue</b> <br> Date: <A ALT="" TITLE="Jennifer Love Hewitt On Cover Of Maxim May 2009 Issue" HREF="http://www.bollywoodmovies.us/news/2009/05_04_2009.html">05/07/2009</A>: <br> <A ALT="" TITLE="Jennifer Love Hewitt" HREF="http://www.bollywoodmovies.us/hollywood/actress/jennifer_love_hewitt/hollywood_jennifer_love_hewitt.html">Jennifer Love Hewitt</A> is being featured on the cover of May 2009 edition of <A ALT="" TITLE="Maxim" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim</A> . The photos will be part of the Maxim May 2009 edition.|g
