s|TAG_META_TITLE|Michelle Obama, Barack Obama|g
s|TAG_META_KEYWORDS|Michelle Obama, Barack Obama, Maxim Hot 100 List|g
s|TAG_META_DESCRIPTION|Michelle Obama, Maxim Hot 100 List|g
#
s|TAG_BIOGRAPHY_1|<b>Michelle Obama</b> was born on January 17, 1964 in Chicago, Illinois, U.S.A.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Michelle is the wife of the forty fourth President of the United States, <A ALT="" TITLE="Barack Obama" HREF="http://www.bollywoodmovies.us/famous_person/barack_obama/famous_person_barack_obama.html">Barack Obama</A>, and the first African American First Lady of the United States.|g
#
#
#
s|TAG_BIO_LATEST_NEWS|<b>House's Olivia Wilde Tops Maxim Hot 100 List</b> <br> Date: <A ALT="" TITLE="House's Olivia Wilde Tops Maxim Hot 100 List" HREF="http://www.bollywoodmovies.us/news/2009/05_11_2009.html">05/13/2009</A>: <br> Fox's hit medical drama House's <A ALT="" TITLE="Olivia Wilde" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/olivia_wilde/celebrites_olivia_wilde.html">Olivia Wilde</A> topped the list of the Maxim 2009 Hot 100 unveiled today. For the first time, the First Lady of the United States made the list. First lady, <A ALT="" TITLE="Michelle Obama" HREF="http://www.bollywoodmovies.us/famous_person/michelle_obama/famous_person_michelle_obama.html">Michelle Obama</A> showed on the list at number 93. The top 10 on the list are: <A ALT="" TITLE="Megan Fox" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/megan_fox/celebrites_megan_fox.html">Megan Fox</A> , <A ALT="" TITLE="Bar Refaeli" HREF="http://www.bollywoodmovies.us/models/bar_refaeli/models_bar_refaeli.html">Bar Refaeli</A> , <A ALT="" TITLE="Malin Akerman" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/malin_akerman/celebrites_malin_akerman.html">Malin Akerman</A> , <A ALT="" TITLE="Mila Kunis" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/mila_kunis/celebrites_mila_kunis.html">Mila Kunis</A> , <A ALT="" TITLE="Eliza Dushku" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/eliza_dushku/celebrites_eliza_dushku.html">Eliza Dushku</A> , <A ALT="" TITLE="Adriana Lima" HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima.html">Adriana Lima</A> , <A ALT="" TITLE="Rihanna" HREF="http://www.bollywoodmovies.us/hollywood/artists/rihanna/hollywood_rihanna.html">Rihanna</A> , <A ALT="" TITLE="Jordana Brewster" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/jordana_brewster/celebrites_jordana_brewster.html">Jordana Brewster</A> , <A ALT="" TITLE="Jennifer Love Hewitt" HREF="http://www.bollywoodmovies.us/hollywood/actress/jennifer_love_hewitt/hollywood_jennifer_love_hewitt.html">Jennifer Love Hewitt</A> .|g