s|TAG_META_TITLE|Kim Kardashian|g
s|TAG_META_KEYWORDS|kim kardashian, |g
s|TAG_META_DESCRIPTION|kim kardashian|g
#
s|TAG_BIOGRAPHY_1|<b>Kim Kardashian</b> was born on October 21, 1980 Los Angeles, California, USA.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|She is an television personality. She is well known for her reality show, Keeping Up With The Kardashians. <BR>In 2008 she was ranked num 28 on the AskMen.com Top 99 Women list. <BR>|g
#
s|TAG_BIO_LATEST_NEWS|<b>Kim Kardashian Has A New Boyfriend</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Kim Kardashian Has A New Boyfriend" HREF="http://www.bollywoodmovies.us/news/2010/06_28_2010.html">07/03/2010</A>: </font> <br> <A ALT="" TITLE="Kim Kardashian" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/kim_kardashian/celebrites_kim_kardashian.html">Kim Kardashian</A> had been dating Orleans Saints running back Reggie Bush for a while and now just two months after splitting with Reggie, Kim was seen with Dallas Cowboys wide receiver Miles Austin.|g
#
s|TAG_BIO_2009_LATEST_NEWS|<b>Milkshake Named After Bollywood Actress Mallika Sherawat</b> <br> Date: <A ALT="" TITLE="Milkshake Named After Bollywood Actress Mallika Sherawat" HREF="http://www.bollywoodmovies.us/news/2009/04_20_2009.html">04/20/2009</A>: <br> <A ALT="" TITLE="Mallika Sherawat" HREF="http://www.bollywoodmovies.us/actress/mallika_sherawat/bollywood_mallika_sherawat.html">Mallika Sherawat</A> has now joined league of Hollywood celebrities including <A ALT="" TITLE="Kim Kardashian" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/kim_kardashian/celebrites_kim_kardashian.html">Kim Kardashian</A> , <A ALT="" TITLE="Miley Cyrus" HREF="http://www.bollywoodmovies.us/hollywood/artists/miley_cyrus/hollywood_miley_cyrus.html">Miley Cyrus</A> , Victoria Beckham, David Beckham and <A ALT="" TITLE="Paris Hilton" HREF="http://www.bollywoodmovies.us/models/paris_hilton/models_paris_hilton.html">Paris Hilton</A> , after a Hollywood milkshake was named after her that is made up of blueberries, raspberries, blackberries, strawberries, and chocolate sauce and topped with whipped cream. Millika is in Hollywood to promote her upcoming horror film <A ALT="" TITLE="Hissss (Naagin The Snake Woman) Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/hissss.html">Hissss (Naagin The Snake Woman) (2009)</A> .|g
