s|TAG_META_TITLE|Celina Jaitley|g
s|TAG_META_KEYWORDS|celina jaitley, |g
s|TAG_META_DESCRIPTION|celina jaitley|g
#
s|TAG_BIOGRAPHY_1|<b>Celina Jaitley</b> was born on November 24, 1981 in Kabul, Afghanistan.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Celina is an Indian actress and model. Celina was a Miss Universe 2001 contest finalist. She made her Bollywood film debut in 2007 in Feroz Khan's Janasheen. Celina Jaitley is brand ambassador for Egyptian tourism in India. Celina Jaitley is brand ambassador for Jashn saris. Celina was on the cover of January 2009 cover of Stuff India magazine.|g
#
s|TAG_BIO_LATEST_NEWS|<b>Celina Jaitley Announced Her Marriage Via Twitter</b> <br> Date: <A ALT="" TITLE="Celina Jaitley Announced Her Marriage Via Twitter" HREF="http://www.bollywoodmovies.us/news/2011/08_29_2011.html">08/29/2011</A>: <br> Bollywood actress <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> recently announced her wedding to Peter Haag on Twitter. The wedding took place last month in a monastery in Austria. Peter Haag is a Dubai based hotelier. Celina Jaitley and Peter Haag have been together since one-and-a-half years now.|g
#
#
#
s|TAG_BIO_2009_LATEST_NEWS|<b>Celina Jaitley On Cover Of Stuff India January 2009 Issue</b> <br> Date: <A ALT="" TITLE="Celina Jaitley On Cover Of Stuff India January 2009 Issue" HREF="http://www.bollywoodmovies.us/news/2009/01_12_2009.html">01/18/2009</A>: <br> <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> is being featured on the cover of January 2009 edition of <A ALT="" TITLE="Stuff India" HREF="http://www.bollywoodmovies.us/info/stuff_magazine.html">Stuff India</A> . The photos will be part of the Stuff India January 2009 edition. Celina was last seen in movie <A ALT="" TITLE="Golmaal Returns Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/golmaal_returns.html">Golmaal Returns (2008)</A> .|g
#
s|TAG_BIO_2008_LATEST_NEWS|<b>Celina Jaitley In King Con</b> <br> Date: <A ALT="" TITLE="elina Jaitley In King Con" HREF="http://www.bollywoodmovies.us/news/2008/09_01_2008.html">09/03/2008</A>: <br> <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> will play the role of a Kleptomaniac stripper in the upcoming movie <A ALT="" TITLE="King Con Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/king_con.html">King Con (2009)</A> opposite <A ALT="" TITLE="Govinda" HREF="http://www.bollywoodmovies.us/actor/govinda/bollywood_govinda.html">Govinda</A> . The movie will be shot in London.|g
#
s|TAG_BIO_2007_LATEST_NEWS|<b>Celina Jaitley Opposite Sean Connery</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Celina Jaitley Opposite Sean Connery" HREF="http://www.bollywoodmovies.us/news/2008/10_20_2008.html">10/21/2008</A>: </font> <br> <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> former Miss India and Bollywood actress has been signed to appear opposite Oscar winner Sean Connery and Orlando Bloom in an international project based on "Arabian Nights". The film Quest of Sheherzade will start to shot in January. Celina next release is going to be <A ALT="" TITLE="Golmaal Returns Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/golmaal_returns.html">Golmaal Returns (2008)</A> October 24, 2008.<br><hr size="1" width="100%"> <b>Celina Jaitley In Hollywood Movie</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Celina Jaitley Hollywood" HREF="http://www.bollywoodmovies.us/news/2007/09_24_2007.html">09/25/2007</A>: </font> <br> <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> has been signed to star in Hollywood movies. The movies that she will star is are Love has no Language and The Quest of Sheherzade.<br><hr size="1" width="100%"><b>Celina Jaitley Featured On Maxim India August 2007</b> <br> Date: <A ALT="" TITLE="Celina Jaitley Maxim India" HREF="http://www.bollywoodmovies.us/news/2007/08_20_2007.html">08/20/2007</A>: <br> <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> was again featured on the cover of August 2007 issues of magazine Maxim India. She was previously on the cover back in 2006. This time she in on the cover because of her love for animals and to support <A ALT="" TITLE="PETA News" HREF="http://www.bollywoodmovies.us/info/peta.html">PETA</A> India with their campaign 'Sexy for a Cause'. Mumbai recently banned captive elephants within the city limits after pressure from PETA India which has backing of many Bollywood celebrites and politician.<br><hr size="1" width="100%"><b>Celina Jaitley Signed By Jashn</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/02_05_2007.html">02/05/2007</A> </font> <br> <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> has been signed by Jashn as the brand ambassador. They will launch a new collection named after the star called Celina Jashn. The collection will include sarees and wraps.<br><hr size="1" width="100%">|g
#
s|TAG_BIO_2006_LATEST_NEWS|<A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2006/06_05_2006.html">06/11/2006</A> <br> <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> is currently busy shooting for of Vikram Bhatt's Red. She was busy the last two months with her overseas Heat World Tour. She has been given a role of a lifetime in the movie and<br><hr size="1" width="100%"><b>Celina Jaitley Works Through Illness</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: 03/06/2006 </font> <br> Recently <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> was shooting Subhash Ghai's <A ALT="" TITLE="Apna Sapna Money Money Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/apna_sapna_money_money.html">Apna Sapna Money Money</A> when she suddenly suffered from a stomach ailment, but continued to work through the shooting to insure that the producer did not incur any losses. <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> will next be seen in a sex comedy of Deepak Tizori's <A ALT="" TITLE="Tom Dick and Harry Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/tom_dick_and_harry.html">Tom Dick and Harry</A> . Celina plays a pole dancer in this movie.<br><hr size="1" width="100%"><b>Actress Celina Jaitley and Sean Teeg</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: 02/04/2006 </font> <br> Actress <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> recently confessed that she is seeing an officer, Sean Teeg, of a Californian production company. Sean Teeg met Celina at the premiere of her Jaanasheen. Celina has a scene in Jawani Deewani in which she is wearng an metallic red bikni.<br><hr size="1" width="100%">|g