s|TAG_META_TITLE|Dev Patel|g
s|TAG_META_KEYWORDS|Dev Patel, |g
s|TAG_META_DESCRIPTION|Dev Patel|g
#
s|TAG_BIOGRAPHY_1|<b>Dev Patel</b> was born on born April 1990 in London.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Dev is an English actor. Dev became well known after his role as Jamal Malik in Danny Boyle's film <A ALT="" TITLE="Slumdog Millionaire Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/slumdog_millionaire.html">Slumdog Millionaire (2008)</A>.|g
#
s|TAG_BIO_LATEST_NEWS|<b>Slumdog Millionaire Get 10 Oscar Nominations</b> <br> Date: <A ALT="" TITLE="Slumdog Millionaire Get 10 Oscar Nominations" HREF="http://www.bollywoodmovies.us/news/2009/01_19_2009.html">01/22/2009</A>: <br> <A ALT="" TITLE="Slumdog Millionaire Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/slumdog_millionaire.html">Slumdog Millionaire (2008)</A> received 10 Oscar nominations. The movie has become a world wide phenomenon and is due to release in India tomorrow January 23, 2009. It has already picked up four Golden Globe for Best Screenplay, <A ALT="" TITLE="AR Rahman" HREF="http://www.bollywoodmovies.us/music_director/ar_rahman/bollywood_ar_rahman_filmography.html">AR Rahman</A> for Best Original Score, Best Director Dale Boyle and Best Movie. Its Oscar nominations are for Best Picture, Best Director, Best Adapted Screenplay, Best Cinematography, Best Film Editing, Best Original Score, Best Original Song (2 nominations for O...Saya and Jai Ho), Best Sound Editing, and Best Sound Mixing. <BR> The film stars <A ALT="" TITLE="Dev Patel" HREF="http://www.bollywoodmovies.us/actor/dev_patel/bollywood_dev_patel.html">Dev Patel</A>, <A ALT="" TITLE="Anil Kapoor" HREF="http://www.bollywoodmovies.us/actor/anil_kapoor/bollywood_anil_kapoor.html">Anil Kapoor</A>, and <A ALT="" TITLE="Freida Pinto" HREF="http://www.bollywoodmovies.us/actress/freida_pinto/bollywood_freida_pinto.html">Freida Pinto</A> and is directed by Danny Boyle.<br><hr size="1" width="100%"> <b>Slumdog Millionaire Wins 4 Golden Globes</b> <br> Date: <A ALT="" TITLE="Slumdog Millionaire Wins 4 Golden Globes" HREF="http://www.bollywoodmovies.us/news/2009/01_12_2009.html">01/11/2009</A>: <br> It started with winning the Screenplay awards for <A ALT="" TITLE="Slumdog Millionaire Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/slumdog_millionaire.html">Slumdog Millionaire (2008)</A> by Simon Beaufoy followed by the mistro himself, <A ALT="" TITLE="AR Rahman" HREF="http://www.bollywoodmovies.us/music_director/ar_rahman/bollywood_ar_rahman_filmography.html">AR Rahman</A> for Best Original Score. Then the man who put it all together, the director Dale Boyle and they closed out the night by winning the best movie drama. The film stars <A ALT="" TITLE="Dev Patel" HREF="http://www.bollywoodmovies.us/actor/dev_patel/bollywood_dev_patel.html">Dev Patel</A>, <A ALT="" TITLE="Anil Kapoor" HREF="http://www.bollywoodmovies.us/actor/anil_kapoor/bollywood_anil_kapoor.html">Anil Kapoor</A>, and <A ALT="" TITLE="Freida Pinto" HREF="http://www.bollywoodmovies.us/actress/freida_pinto/bollywood_freida_pinto.html">Freida Pinto</A> and is directed by Danny Boyle. The movie will release all over India on January 23, 2009.<br><hr size="1" width="100%">|g
#
#
#
s|TAG_BIO_2008_LATEST_NEWS|<b>Slumdog Millionaire Passes Jodhaa Akbar</b> <br>  Date: <A ALT="" TITLE="Slumdog Millionaire Passes Jodhaa Akbar" HREF="http://www.bollywoodmovies.us/news/2008/12_08_2008.html">12/08/2008</A>: <br> After winning Best Film, Best Director, and the Most Promising Newcomer for 18 year old actor Dev Patel awards at the British Independent Film Awards, the film <A ALT="" TITLE="Slumdog Millionaire Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/slumdog_millionaire.html">Slumdog Millionaire (2008)</A> has collected more then $3.8 million at the North American box office, surpassing <A ALT="" TITLE="Jodha Akbar, Jodhaa Akbar Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/jodha_akbar.html">Jodha Akbar, Jodhaa Akbar (2008)</A> starring <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> and <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> which has collected $3.4 million and hence making it the highest grossing Indian movie of 2008. The film stars <A ALT="" TITLE="Dev Patel" HREF="http://www.bollywoodmovies.us/actor/dev_patel/bollywood_dev_patel.html">Dev Patel</A> and <A ALT="" TITLE="Freida Pinto" HREF="http://www.bollywoodmovies.us/actress/freida_pinto/bollywood_freida_pinto.html">Freida Pinto</A> and is directed by Danny Boyle. The movie was released only on 49 locations within North American, but will should now be opening in more theatres nationwide.|g