s|TAG_META_TITLE|Farhan Akhtar|g
s|TAG_META_KEYWORDS|Farhan Akhtar, |g
s|TAG_META_DESCRIPTION|Farhan Akhtar|g
#
s|TAG_BIOGRAPHY_1|<b>Farhan Akhtar</b> was born on January 9, 1974 in India.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Farhan's father is <A ALT="" TITLE="Javed Akhtar" HREF="http://www.bollywoodmovies.us/lyrics/javed_akhtar/bollywood_javed_akhtar.html">Javed Akhtar</A>, a well known scripwriter, poet and lyricist. Farhan's step mother is Shabana Azmi, a well known Bollywood film actress. Farhan's debut Bollywood movie was Dil Chahta Hai in 2001, starring <A ALT="" TITLE="Aamir Khan" HREF="http://www.bollywoodmovies.us/actor/aamir_khan/bollywood_aamir_khan.html">Aamir Khan</A>, <A ALT="" TITLE="Akshaye Khanna" HREF="http://www.bollywoodmovies.us/actor/akshaye_khanna/bollywood_akshaye_khanna.html">Akshaye Khanna</A> and <A ALT="" TITLE="Saif Ali Khan" HREF="http://www.bollywoodmovies.us/actor/saif_ali_khan/bollywood_saif_ali_khan.html">Saif Ali Khan</A> and it was a great hit. His next movie was Lakshya with <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> in 2004. Lakshya did not do well as his first movie. Farhan's next project was the remake of 1978 Amitabh Bachchan film Don. His version was called  <A ALT="" TITLE="Don 2 The Chase Begins Again Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/don_2.html">Don 2 The Chase Begins Again (2006)</A> which starred <A ALT="" TITLE="Shahrukh Khan" HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan.html">Shahrukh Khan</A> and released in 2006. This time his movie hit the mark and was a high success at the box office.|g
#
#
s|TAG_BIO_LATEST_NEWS||g
#
s|TAG_BIO_2010_LATEST_NEWS|<b>Katrina Kaif And Hrithik Roshan Shot A Kissing Scene?</b> <br> Date: <A ALT="" TITLE="Katrina Kaif And Hrithik Roshan Shot A Kissing Scene?" HREF="http://www.bollywoodmovies.us/news/2010/11_01_2010.html">11/03/2010</A>: <br> Rumors have it that director Zoya Akhtar has shot a steamy kissing scene between <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> and <A ALT="" TITLE="Katrina Kaif" HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif.html">Katrina Kaif</A> for their upcoming movie <A ALT="" TITLE="Zindagi Milegi Na Dobara Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/zindagi_milegi_na_dobara.html">Zindagi Milegi Na Dobara (2010)</A> . The scene is said to be about two minutes long which would make it longest lip lock in Bollywood so far. This is the first time the Katrina will be paired opposite Hrithik. This will the first on screen kissing scene for Katrian while, Hrithik has already kissed <A ALT="" TITLE="Aishwarya Rai" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai</A> in movie <A ALT="" TITLE="Dhoom 2, Back In Action Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/dhoom_2.html">Dhoom 2, Back In Action (2006)</A> and <A ALT="" TITLE="Barbara Mori" HREF="http://www.bollywoodmovies.us/actress/barbara_mori/bollywood_barbara_mori.html">Barbara Mori</A> in movie <A ALT="" TITLE="Kites Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/kites.html">Kites (2009)</A> This is the 2nd movie that will be directed by Zoya after her debut film <A ALT="" TITLE="Luck by Chance Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/luck_by_chance.html">Luck by Chance (2008)</A> . The film will also star her brother <A ALT="" TITLE="Farhan Akhtar" HREF="http://www.bollywoodmovies.us/actor/farhan_akhtar/bollywood_farhan_akhtar.html">Farhan Akhtar</A> , along with Abhay Deol and Kalki Koechlin. The movie has been shot in Spain.<br><hr size="1" width="100%"> 
#
s|TAG_BIO_2010_LATEST_NEWS|<b>Shahrukh Khan And Aamir Khan Together In A Movie</b> <br> Date: <A ALT="" TITLE="Shahrukh Khan And Aamir Khan Together In A Movie" HREF="http://www.bollywoodmovies.us/news/2009/01_19_2009.html">01/21/2009</A>: <br> <A ALT="" TITLE="Shahrukh Khan (SRK)" HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan.html">Shahrukh Khan (SRK)</A> and <A ALT="" TITLE="Aamir Khan" HREF="http://www.bollywoodmovies.us/actor/aamir_khan/bollywood_aamir_khan.html">Aamir Khan</A> will both been seen in the upcoming movie <A ALT="" TITLE="Luck by Chance Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/luck_by_chance.html">Luck by Chance (2009)</A> directed by first time director <A ALT="" TITLE="Zoya Akhtar" HREF="http://www.bollywoodmovies.us/director/zoya_akhtar/bollywood_zoya_akhtar.html">Zoya Akhtar</A> , sister of <A ALT="" TITLE="Farhan Akhtar" HREF="http://www.bollywoodmovies.us/actor/farhan_akhtar/bollywood_farhan_akhtar.html">Farhan Akhtar</A> and daugther of well known poet and lyricist <A ALT="" TITLE="Javed Akhtar" HREF="http://www.bollywoodmovies.us/lyrics/javed_akhtar/bollywood_javed_akhtar.html">Javed Akhtar</A> . The two stars are in the same movie, but do not share any onscreen scene time together. They both play themselfs in the movie, Shahrukh interacts with Farhan and Aamir with <A ALT="" TITLE="Konkona Sen Sharma" HREF="http://www.bollywoodmovies.us/actress/konkona_sen_sharma/bollywood_konkona_sen_sharma.html">Konkona Sen Sharma</A> . The movie is due to release on January 30, 2009.|g
