s|TAG_META_TITLE|Parvathy Omanakuttan|g
s|TAG_META_KEYWORDS|Parvathy Omanakuttan, |g
s|TAG_META_DESCRIPTION|Parvathy Omanakuttan|g
#
s|TAG_BIOGRAPHY_1|<b>Parvathy Omanakuttan</b> was born on July 13, 1987 in Changanassery, Kottayam, Kerala.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Parvathy is an model. Parvathy was the Miss India World 2008. She won the "Pantaloons Femina Miss India World 2008" title in Mumbai on 5 April 2008. Parvathy represented India at the Miss World 2008 pageant on December 13, 2008 in Johannesburg, South Africa. |g
#
s|TAG_BIO_LATEST_NEWS|<b>Parvathy Omanakuttan To Compete In Miss World 2008</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Parvathy Omanakuttan To Compete In Miss World 2008" HREF="http://www.bollywoodmovies.us/news/2008/12_08_2008.html">12/10/2008</A>: </font> <br> <A ALT="" TITLE="Parvathy Omanakuttan" HREF="http://www.bollywoodmovies.us/actress/parvathy_omanakuttan/bollywood_parvathy_omanakuttan.html">Parvathy Omanakuttan</A> will be representing India at the Miss World 2008 pageant on December 13, 2008. The Miss World 2008 pageant is being held at the Sandton Convention Center in Johannesburg, South Africa, which was originally scheduled to take place at Kiev, Ukraine, but because of the ongoing crisis between Georgia and Russia in neighboring South Ossetia, the pageant was moved from Eastern Europe by the Miss World Organization. Parvathy is 21 years old from Changanassery, Kottayam, Kerala. Parvathy is the reigning Miss India World 2008 and on 5 April 2008 was crowned "Pantaloons Femina Miss India World 2008". She has already been the Femina Miss India South 2008 and Miss Malayali 2005. If Parvathy wins, she will joins the likes of Reita Faria (1966), <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> (1994), <A ALT="" TITLE="Diana Hayden" HREF="http://www.bollywoodmovies.us/actress/diana_hayden/bollywood_diana_hayden.html">Diana Hayden</A> (1997), Yukta Mookhey (1999) and <A ALT="" TITLE="Priyanka Chopra" HREF="http://www.bollywoodmovies.us/actress/priyanka_chopra/bollywood_priyanka_chopra.html">Priyanka Chopra</A> (2000) who have brought the crown to India.|g
