call create_biography_per_person.bat actress kareena_kapoor
call create_biography_per_person.bat actress madhuri_dixit
call create_biography_per_person.bat actress aishwarya_rai
call create_biography_per_person.bat actress shilpa_shetty
call create_biography_per_person.bat actress prachi_desai
call create_biography_per_person.bat actress genelia_dsouza
call create_biography_per_person.bat actress priyanka_chopra
call create_biography_per_person.bat actress katrina_kaif
call create_biography_per_person.bat actress kangna_ranaut
call create_biography_per_person.bat actress asin_thottumkal
call create_biography_per_person.bat actress giselle_monteiro

call create_biography_per_person.bat actor salman_khan
call create_biography_per_person.bat actor hrithik_roshan
call create_biography_per_person.bat actor abhishek_bachchan
call create_biography_per_person.bat actor shahrukh_khan
call create_biography_per_person.bat actor ritesh_deshmukh
call create_biography_per_person.bat actor ajay_devgan
call create_biography_per_person.bat actor aamir_khan
call create_biography_per_person.bat actor amitabh_bachchan