s|TAG_META_TITLE|Trisha Krishnan|g
s|TAG_META_KEYWORDS|Trisha Krishnan, Actress, Kollywood|g
s|TAG_META_DESCRIPTION|Trisha Krishnan, Actres, Kollywood|g
#
s|TAG_BIOGRAPHY_1|<b>Trisha Krishnan</b> was born on May 4, 1983 in Palakkad, Kerala, India.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Trisha is an Indian actress. She is also one of the top actress in south Indian cinema. Trisha is an award winning actress in both Tamil and Telugu film industries. She become well known after her role in Tamil movie Saamy and Ghilli and in Telugu Varsham. Earlier in her modelling career she won the Miss Salem in 1999, Miss Chennai in 1999 and Miss India Miss Beautiful Smile in 2001.|g
#
s|TAG_BIO_LATEST_NEWS|<b>Trisha Krishnan Going From Kollywood To Bollywood?</b> <br> Date: <A ALT="" TITLE="Trisha Krishnan Going From Kollywood To Bollywood?" HREF="http://www.bollywoodmovies.us/news/2009/06_08_2009.html">06/13/2009</A>: <br> One of the top actress of Kollywood (Tamil Film), <A ALT="" TITLE="Trisha Krishnan" HREF="http://www.bollywoodmovies.us/actress/trisha_krishnan/bollywood_trisha_krishnan.html">Trisha Krishnan</A> has been signed by director Priyadarshan to play a role opposite Bollywood's <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A> in movie <A ALT="" TITLE="Khatta Meeta Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/khatta_meeta.html">Khatta Meeta (2009)</A> . The director had introduced Trisha seven years ago to the <A ALT="" TITLE="Kollywood Movies" HREF="http://www.bollywoodmovies.us/kollywood/kollywood.html">Kollywood</A> in movie Lesa Lesa in Tamil. The movie is schedule to start shooting in November 2009. Trisha has already worked with the best in the business like <A ALT="" TITLE="Rajnikanth" HREF="http://www.bollywoodmovies.us/kollywood/actor/rajnikanth/kollywood_rajnikanth.html">Rajnikanth</A> , <A ALT="" TITLE="Kamal Hassan" HREF="http://www.bollywoodmovies.us/actor/kamal_hassan/bollywood_kamal_hassan.html">Kamal Hassan</A> megastar Chiranjeevi.|g
