s|TAG_TITLE_NAME|Aishwarya Rai, Aishwarya Bachchan|g
s|TAG_KEYWORD_ACTRESS_NAME|aishwarya rai, aish, ash, cannes, aishwarya bachchan|g
s|TAG_DESC_ACTRESS_NAME|aishwarya rai|g
#
s|TAG_ALT_ACTRESS_NAME|Aishwarya Rai, Aishwarya Bachchan|g
s|TAG_DIR_NAME_1|actress|g
s|TAG_DIR_ACTRESS_NAME|aishwarya_rai|g
s|TAG_ACTRESS_LONG_DESC|Aishwarya Rai (Aishwarya Bachchan), latest news and pictures, video clips, biography, filmography, bollywood movie actress, indian model pictures gallery, aish, Bollywood, photo gallery, photos, pictures, wallpapers, devdas, hum dil de chuke sanam, hum kisse se kum nahi, bride and prejudice, india, indian models, iruvar, aishwarya model, aishwarya rai model, albela, ash, bollywood pictures, miss world, model, cannes, loreal, aishwarya loreal ad, lux, nakshatra, aishwarya rai pics, aishwarya rai photo, ash photos, aishwarya rai gallery, aishwarya rai video, aishwarya rai adverts, aishwarya rai ads, aishwarya rai commercials, aishwarya rai audio, devdas, , hum dil de chuke sanam, dil ka rishta, kondukandain kondukondain, taj mahal, josh, hamara dil aapke paas hai, mohabbatein, albela, hum tumhare hain sanam, shakti.|g
#
s|TAG_FILMOGRAPHY_WORKED_WITH_DIRECTORS|Paul Mayeda Berges, Gurinder Chadha, Shaad Ali, Leena Yadav, Martin Henderson, Rituparno Ghosh, Rajkumar Santoshi, Rohan Sippy, Rituparno Ghosh, Naresh Malhotra, Sanjay Leela Bhansali, Aditya Chopra, Mansoor Khan, Rajiv Menon, Subhash Ghai, |g
s|TAG_FILMOGRAPHY_WORKED_WITH_ACTORS|<A ALT="" TITLE="Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan.html">Amitabh Bachchan</A>, <A ALT="" TITLE="Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html">Abhishek Bachchan</A>, Sanjay Dutt, Zayed Khan, Samir Karnik, <A ALT="" TITLE="Ajay Devgan" HREF="http://www.bollywoodmovies.us/actor/ajay_devgan/bollywood_ajay_devgan.html">Ajay Devgan</A>, <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A>, Prasenjit Chatterjee, <A ALT="" TITLE="Arjun Rampal" HREF="http://www.bollywoodmovies.us/actor/arjun_rampal/bollywood_arjun_rampal.html">Arjun Rampal</A>, <A ALT="" TITLE="Shahrukh Khan" HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan.html">Shahrukh Khan</A>, Jackie Shroff, Chandrachur Singh, Anil Kapoor, <A ALT="" TITLE="Akshaye Khanna" HREF="http://www.bollywoodmovies.us/actor/akshaye_khanna/bollywood_akshaye_khanna.html">Akshaye Khanna</A>, <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A>, <A ALT="" TITLE="Salman Khan" HREF="http://www.bollywoodmovies.us/actor/salman_khan/bollywood_salman_khan.html">Salman Khan</A>, <A ALT="" TITLE="Vivek Oberoi" HREF="http://www.bollywoodmovies.us/actor/vivek_oberoi/bollywood_vivek_oberoi.html">Vivek Oberoi</A>, Colin Firth, Ben Kingsley|g
s|TAG_FILMOGRAPHY_WORKED_WITH_ACTRESS|<A ALT="" TITLE="Rani Mukherjee" HREF="http://www.bollywoodmovies.us/actress/rani_mukherjee/bollywood_rani_mukherjee.html">Rani Mukherjee</A>, <A ALT="" TITLE="Madhuri Dixit" HREF="http://www.bollywoodmovies.us/actress/madhuri_dixit/bollywood_madhuri_dixit.html">Madhuri Dixit</A>, Preeti Jhangiani, Shamita Shetty, <A ALT="" TITLE="Tabu" HREF="http://www.bollywoodmovies.us/actress/Tabu/bollywood_tabu.html">Tabu</A>|g
#
s|TAG_META_TITLE_LATEST_MOVIE_RELEASES|Mistress of Spices, The Last Legion, Dhoom 2, Provoked, Umrao Jaan|g
s|TAG_META_KEYWORD_LATEST_MOVIE_RELEASES|Mistress of Spices, The Last Legion, Dhoom 2, Provoked, Umrao Jaan|g
s|TAG_META_DESC_LATEST_MOVIE_RELEASES|Mistress of Spices, The Last Legion, Dhoom 2, Provoked, Umrao Jaan|g
#
s|TAG_FILMOGRAPHY_PRE_2000_MOVIE_RELEASES|Ravoyi Chandamama (1999) As Special Appearance (Song). Other Title: Shankar (India: Tamil title) As <br>Taal (1999) As Mansi. Other Title: Thaalam (India: Tamil title) As <br>Hum Dil De Chuke Sanam (1999) As Nandini. Other Title: Straight from the Heart (International: English title) As <br>Aa Ab Laut Chalen (1999) As Pooja Walia. Other Title: Lets Go Back (International: English title) As <br>Jeans (1998) As Madhumitha/Vaishnavi <br>Aur Pyaar Ho Gaya (1997) As Ashi Kapoor <br>Iruvar (1997) As Pushpa/Kalpana. Other Title: Iddaru (India: Telugu title: dubbed version) As |g
s|TAG_FILMOGRAPHY_2000_2004_MOVIE_RELEASES|Kuch Naa Kaho (2003) As Namrata Shrivastav. Other Titles: Don't Say a Word (International: English title: informal literal title) As <br>Chokher Bali (2003) As Binodini. Other Titles: Choker Bali: A Passion Play (International: English title). Other Titles: Sand in the Eye (India: English title) As <br>Dil Ka Rishta (2003) As Tia Sharma. Other Titles: Heart of Gold (International: English title). Other Titles: Relationships of Hearts (International: English title: informal literal title) As <br>Shakti: The Power (2002) As Dream Girl. <br>23rd March 1931: Shaheed (2002) As Special Appearance (song)<br>Hum Kisi Se Kum Nahin (2002) As Komal Rastogi<br>Hum Tumhare Hain Sanam (2002) As Special Appearence <br>Devdas (2002) As Parvati ('Paro') As <br>Albela (2001) As Sonia <br>Mohabbatein (2000) As Megha. Other Titles: Love Stories (Europe: English title) As <br>Dhaai Akshar Prem Ke (2000) As Sahiba Gareval <br>Hamara Dil Aapke Paas Hai (2000) As Preeti Virat. Other Titles: You Have My Heart (International: English title: informal title) As <br>Josh (2000) As Shirley<br>Kandukondain Kandukondain (2000) As Meenakshi. Other Titles: I Have Found It (International: English title). Other Titles: Priyuraalu Pilichindi (India: Telugu title: dubbed version) As <br>Mela (2000) As Champakali <br>Sanam Tere Hain Hum (2000) As Special Appearance|g
s|TAG_FILMOGRAPHY_2004_2005_MOVIE_RELEASES|<A ALT="" TITLE="Bunty Aur Babli Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2005/bunty_aur_babli.html">Bunty Aur Babli (2005)</A> As Special Appearance (song: Kajra Ra)<br>Shabd (2005) As Antara Vashisht<br>Bride and Prejudice (2004) As Lalita Bakshi<br>Kyun...! Ho Gaya Na (2004) As Diya Malhotra<br>Raincoat (2004) As Neerja/Neeru<br>Khakee (2004) As Mahalaxshmi|g
s|TAG_FILMOGRAPHY_2006_MOVIE_RELEASES|<A ALT="" TITLE="Dhoom 2 Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/dhoom_2.html">Dhoom 2 (2006)</A><br><A ALT="" TITLE="Umrao Jaan Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/umrao_jaan.html">Umrao Jaan (2006)</A> As Umrao Jaan<br>The Heart of India (2006) As Mumtaz Mahal<br><A ALT="" TITLE="Mistress of Spices Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/mistress_of_spices.html">Mistress of Spices (2006)</A> As Tilo|g
#
s|TAG_FILMOGRAPHY_2007_MOVIE_RELEASES|<A ALT="" TITLE="The Last Legion Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/the_last_legion.html">The Last Legion (2007)</A> As Mira<br><A ALT="" TITLE="Provoked Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/provoked.html">Provoked (2007)</A> As Mira<br>|g
#
s|TAG_FILMOGRAPHY_2008_MOVIE_RELEASES|<A ALT="" TITLE="Jodha Akbar Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/jodha_akbar.html">Jodha Akbar (2007)</A>|g
