s|TAG_TITLE_NAME|Isha Gopikar|g
s|TAG_KEYWORD_ACTRESS_NAME|isha gopikar|g
s|TAG_DESC_ACTRESS_NAME|isha gopikar|g
#
s|TAG_ALT_ACTRESS_NAME|Isha Gopikar|g
s|TAG_DIR_NAME_1|actress|g
s|TAG_DIR_ACTRESS_NAME|isha_gopikar|g
s|TAG_ACTRESS_LONG_DESC||g
#
s|TAG_FILMOGRAPHY_2000_2004_MOVIE_RELEASES||g
s|TAG_FILMOGRAPHY_2004_2005_MOVIE_RELEASES||g
#
s|TAG_FILMOGRAPHY_2006_MOVIE_RELEASES||g
#
s|TAG_FILMOGRAPHY_2007_MOVIE_RELEASES||g
