s|TAG_META_TITLE|Need To Update|g
s|TAG_META_KEYWORDS|need to update, |g
s|TAG_META_DESCRIPTION|need to update|g
#
s|TAG_BIOGRAPHY_1|<b>Need To Update</b> |g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|NEED_TO_UPDATE|g
#
s|TAG_BIO_2007_LATEST_NEWS|<A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/05_21_2007.html">05/22/2007</A>: <br> <A ALT="" TITLE="Lindsay Lohan" HREF="http://www.bollywoodmovies.us/hollywood/actress/lindsay_lohan/hollywood_lindsay_lohan_photo_gallery.html">Lindsay Lohan</A> votes into Maxim Hot 100 list for the month of May. The number 2 stop went to <A ALT="" TITLE="Jessica Alba" HREF="http://www.bollywoodmovies.us/hollywood/actress/jessica_alba/hollywood_jessica_alba_photo_gallery.html">Jessica Alba</A> , followed by <A ALT="" TITLE="Scarlett Johansson" HREF="http://www.bollywoodmovies.us/hollywood/actress/scarlett_johansson/hollywood_scarlett_johansson_photo_gallery.html">Scarlett Johansson</A> , Christina Aguilera, and Jessica Biel.|g
#
s|TAG_BIO_2008_LATEST_NEWS|<b>Aishwarya Rai Bachchan Has The Sexiest Eyes</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Aishwarya Rai Bachchan Has The Sexiest Eyes" HREF="http://www.bollywoodmovies.us/news/2008/11_03_2008.html">11/03/2008</A>: </font> <br> <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> beat out Hollywood superstars <A ALT="" TITLE="Angelina Jolie" HREF="http://www.bollywoodmovies.us/hollywood/actress/angelina_jolie/hollywood_angelina_jolie.html">Angelina Jolie</A> , <A ALT="" TITLE="Megan Fox" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/megan_fox/celebrites_megan_fox.html">Megan Fox</A> , <A ALT="" TITLE="Scarlett Johansson" HREF="http://www.bollywoodmovies.us/hollywood/actress/scarlett_johansson/hollywood_scarlett_johansson.html">Scarlett Johansson</A> and other to be voted as having the ‘sexiest eyes’ in US TV E!'s Sexiest Body Parts List. <A ALT="" TITLE="Gisele Bundchen" HREF="http://www.bollywoodmovies.us/models/gisele_bundchen/models_gisele_bundchen.html">Gisele Bundchen</A> , Brazilian supermodel, walked away with the sexiest legs award. <A ALT="" TITLE="Charlize Theron" HREF="http://www.bollywoodmovies.us/hollywood/actress/charlize_theron/hollywood_charlize_theron.html">Charlize Theron</A> won for her sultry shoulders and <A ALT="" TITLE="Eva Mendes" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/eva_mendes/celebrites_eva_mendes.html">Eva Mendes</A> got votes for her locks. Taiwanese actress Shu Qi was voted has having the sexiest lips.<br><hr size="1" width="100%"> <b>Scarlett Johansson Engaged To Ryan Reynolds</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Scarlett Johansson Engaged To Ryan Reynolds" HREF="http://www.bollywoodmovies.us/news/2008/05_05_2008.html">05/05/2008</A>: </font> <br> <A ALT="" TITLE="Scarlett Johansson" HREF="http://www.bollywoodmovies.us/hollywood/actress/scarlett_johansson/hollywood_scarlett_johansson.html">Scarlett Johansson</A> and Ryan Reynolds announced their engagement. The 23 year old actress and the 31 year old actor have yet not set the wedding date.|g
#
#
s|TAG_BIO_LATEST_NEWS|<b>Scarlett Johansson In Iron Men 2</b> <br> Date: <A ALT="" TITLE="Scarlett Johansson In Iron Men 2" HREF="http://www.bollywoodmovies.us/news/2009/03_02_2009.html">03/13/2009</A>: <br> <A ALT="" TITLE="Scarlett Johansson" HREF="http://www.bollywoodmovies.us/hollywood/actress/scarlett_johansson/hollywood_scarlett_johansson.html">Scarlett Johansson</A> has joined the cast for the sequel to Iron Men, Scarlett will star as the Black Widow in the <A ALT="" TITLE="Iron Man 2 Movie Review" HREF="http://www.bollywoodmovies.us/hollywood/movie_reviews/2010/iron_man_2.html">Iron Man 2 (2010)</A> opposite Robert Downey Jr. Mickey Rourke has also been signed to play villain Whiplash. The movie is scheduled for May 2010 release and will also bring back <A ALT="" TITLE="Gwyneth Paltrow" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/gwyneth_paltrow/celebrites_gwyneth_paltrow.html">Gwyneth Paltrow</A> returning as Pepper Potts, and Samuel L. Jackson as Nick Fury and Don Cheadle playing Col. James "Rhodey" Rhodes.|g
