s|TAG_META_TITLE|Bollywood Movie Review for Players, Actor Abhishek Bachchan, Actress Sonam Kapoor, Madhuri Dixit To Be Added To Madame Tussauds London Wax Museum|g
s|TAG_META_KEYWORDS|Bollywood Movie Review for Players, Actor Abhishek Bachchan, Actress Sonam Kapoor, Madhuri Dixit To Be Added To Madame Tussauds London Wax Museum|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/madhuri_dixit/bollywood_madhuri_dixit_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/madhuri_dixit/pics/madhuri_dixit_03.jpg" ALT="Madhuri Dixit" TITLE="Madhuri Dixit" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Madhuri Dixit To Be Added To Madame Tussauds London Wax Museum</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Madhuri Dixit To Be Added To Madame Tussauds London Wax Museum" HREF="http://www.bollywoodmovies.us/news/2012/01_02_2012.html">01/05/2012</A>: </font> <br> The Bollywood dhak dhak queen <A ALT="" TITLE="Madhuri Dixit" HREF="http://www.bollywoodmovies.us/actress/madhuri_dixit/bollywood_madhuri_dixit.html">Madhuri Dixit</A> will soon join other Bollywood celebrities in the Madame Tussauds London wax museum. Currently the following Bollywood actors can be seem at the Madame Tussauds London wax museum: Amitabh Bachchan, <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A>, <A ALT="" TITLE="Shahrukh Khan" HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan.html">Shahrukh Khan</A>, <A ALT="" TITLE="Salman Khan" HREF="http://www.bollywoodmovies.us/actor/salman_khan/bollywood_salman_khan.html">Salman Khan</A>, <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> and <A ALT="" TITLE="Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor.html">Kareena Kapoor</A> . Madhuri will be joining the attraction in March 2012. Madhuri recently moved her home from USA to <A ALT="" TITLE="Maharashtra Mumbai" HREF="http://www.bollywoodmovies.us/Regional/India/Maharashtra/Mumbai/Mumbai.html">Mumbai</A> with her family. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/abhishek_bachchan/pics/abhishek_bachchan_05.jpg" ALT="Abhishek Bachchan" TITLE="Abhishek Bachchan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/sonam_kapoor/bollywood_sonam_kapoor_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/sonam_kapoor/pics/sonam_kapoor_04.jpg" ALT="Sonam Kapoor" TITLE="Sonam Kapoor" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing January 06, 2012" HREF="http://www.bollywoodmovies.us/news/2011/12_19_2011.html">Movie Releasing January 06, 2012</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Players" HREF="http://www.bollywoodmovies.us/movie_reviews/2011/players.html">Players (2011) </A> <br> Cast: <A ALT="" TITLE="Actor Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan_photo_gallery_01.html">Abhishek Bachchan </A> , <A ALT="" TITLE="Actress Sonam Kapoor" HREF="http://www.bollywoodmovies.us/actress/sonam_kapoor/bollywood_sonam_kapoor_photo_gallery_01.html">Sonam Kapoor </A> </font> , Bobby Deol, Neil Nitin Mukesh, Omi Vaidya, Bipasha Basu </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
