s|TAG_META_TITLE|Sony NGP, PSP, PS3, WiFi, touchscreen, Mallika Sherawat, Thank You, Aishwarya Rai Bachchan On Cover Of Vogue|g
s|TAG_META_KEYWORDS|Sony NGP, PSP, PS3, WiFi, touchscreen, Mallika Sherawat, Thank You, Aishwarya Rai Bachchan On Cover Of Vogue|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_21.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_183.jpg" ALT="Aishwarya Rai" TITLE="Aishwarya Rai" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Aishwarya Rai Bachchan On Cover Of Vogue India February 2011</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Aishwarya Rai Bachchan On Cover Of Vogue India February 2011" HREF="http://www.bollywoodmovies.us/news/2011/01_31_2011.html">02/02/2011</A>: </font> <br> The Vogue India Feruary 2011 cover feature Miss World <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> wearing a black dress with angel wings and all. The magazine includes interviews with some of her closets friends, including husband Abhishek Bachchan, designer Manish Malhotra, director Ashutosh Gowariker and make up artist Mickey Contractor. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/mallika_sherawat/bollywood_mallika_sherawat_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/mallika_sherawat/pics/mallika_sherawat_01.jpg" ALT="Mallika Sherawat" TITLE="Mallika Sherawat" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Mallika Sherawat Shots An Item Number For Upcoming Movie</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Mallika Sherawat Shots An Item Number For Upcoming Movie" HREF="http://www.bollywoodmovies.us/news/2011/01_31_2011.html">01/31/2011</A>: </font> <br> <A ALT="" TITLE="Mallika Sherawat" HREF="http://www.bollywoodmovies.us/actress/mallika_sherawat/bollywood_mallika_sherawat.html">Mallika Sherawat</A> has shot an item number song for upcoming movie <A ALT="" TITLE="Thank You Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/thank_you.html">Thank You (2010)</A> starring <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A> and <A ALT="" TITLE="Sonam Kapoor" HREF="http://www.bollywoodmovies.us/actress/sonam_kapoor/bollywood_sonam_kapoor.html">Sonam Kapoor</A> . The title of the song is Razia Gundo Mein Phans Gayee. At first, Mallika showed up with a dress that was too revealing, and given that the film is a family movie, director Anees Bazmee asked her to put on some more clothing. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD|<!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="Sony PSP Successor NGP Game Console Announced" HREF="http://www.bollywoodmovies.us/news/2011/01_31_2011.html">01/31/2011</A>: <br> At the Sony Computer event at Tokyo, company CEO Kaz Hirai announced the PlayStation Portable 2 game console codenamed NGP. <A ALT="" TITLE="Apple NGP" HREF="http://www.bollywoodmovies.us/info/video_game_player.html">NGP</A> stands for Next-Generation PlayStation. NGP will have 5 inch OLED touchscreen supporting 960x544 pixel resolution, touchscreen on the front panel, two touchpads on its back panel, front facing camera, another camera lies on the top center at the back of the console, built in stereo speaker with grills on front and built in mic, three axis accelerometer, three axis gyroscopic sensor and three axis compass, built in GPS, wireless 3G Network, Wi-Fi 802.11 b/g/n (infra and Ad Hoc) and Bluetooth 2.1. The dual analog sticks promise you DualShock experience just like the ones in DualShock controllers for PS3. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END -->|g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Feburary 04, 2010" HREF="http://www.bollywoodmovies.us/news/2011/01_31_2010.html">Movie Releasing Feburary 04, 2011</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Angel <hr size="1" width="100%"> Masti Express <hr size="1" width="100%"> United Six <hr size="1" width="100%"> Utt Pataang <hr size="1" width="100%"> Yeh Saali Zindagi <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
