s|TAG_META_TITLE|Meiyang Chang Win Jhalak Dikhla Jaa 4, Ferrari to make India debut, Ranbir Kapoor And Nargis Fakhri|g
s|TAG_META_KEYWORDS|Meiyang Chang Win Jhalak Dikhla Jaa 4, Ferrari to make India debut, Ranbir Kapoor And Nargis Fakhri, Rockstar|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/ranbir_kapoor/pics/ranbir_kapoor_17.jpg" ALT="Ranbir Kapoor" TITLE="Ranbir Kapoor" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Ranbir Kapoor And Nargis Fakhri? What about Katrina Kaif?</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Ranbir Kapoor And Nargis Fakhri? What about Katrina Kaif?" HREF="http://www.bollywoodmovies.us/news/2011/03_07_2011.html">03/10/2011</A>: </font> <br> Can it be true that <A ALT="" TITLE="Ranbir Kapoor" HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor.html">Ranbir Kapoor</A> is now going out with <A ALT="" TITLE="Nargis Fakhri" HREF="http://www.bollywoodmovies.us/actress/nargis_fakhri/bollywood_nargis_fakhri.html">Nargis Fakhri</A> , who also happens to star opposite him in his upcoming film <A ALT="" TITLE="Rockstar Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/rockstar.html">Rockstar (2011)</A> . Recently both where spotted coming out of a Mumbai multiplex with his friend Ayaan Mukherji. If this was a real date, then the Ranbit and Katrina pair did not last that long. For some time Katrina has suspected that Ranbir and Nargis were going out, and hence came to Delhi on the sets of thier film Rockstar. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE|<!-- TV_SHOWS_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Meiyang Chang Win Jhalak Dikhla Jaa 4" HREF="http://www.bollywoodmovies.us/news/2011/03_07_2011.html">03/09/2011</A> <br> <A ALT="" TITLE="Meiyang Chang" HREF="http://www.bollywoodmovies.us/actor/meiyang_chang/bollywood_meiyang_chang.html">Meiyang Chang</A> became popular when he made it to the top five in Indian Idol 3 and year after ancorhed the show. He then made his Bollywood film debut in <A ALT="" TITLE="Badmaash Company Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/badmaash_company.html">Badmaash Company (2010)</A> . Now is he won the dance title in <A ALT="" TITLE="Jhalak Dikhhla Jaa Season 4" HREF="http://www.bollywoodmovies.us/tv_shows/jhalak_dikhhla_jaa/jhalak_dikhhla_jaa.html">Jhalak Dikhhla Jaa Season 4</A> . The 28 year old Chang is a professional dentist and a singer but has won the hearts of Indian fan as a singer and actor. Meiyang forefathers lived in China's Hubei province. <hr size="1" width="100%"> </td> </tr> <!-- TV_SHOWS_END -->|g
#
s|TAG_NEWS_WORLD|<!-- INDIA_STORY_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Ferrari to make India debut" HREF="http://www.bollywoodmovies.us/news/2011/03_07_2011.html">03/10/2011</A>: <br> Italian super sports car <A ALT="" TITLE="Sport Cars" HREF="http://www.bollywoodmovies.us/info/cars.html">Ferrari</A> will be launched in India in the coming months. The Ferrari car will be available at the price of 2.27 crore to 3.37 crore. Ferrari, part of Italy's largest car company Fiat Auto, has made a deal with India's Shreyans group to import and sell these cars by spring this year (2011). The first showroom will start in Delhi in the first half of this year and then followed by Mumbai in the second half of this year. Ferrari will compete with the likes of super sports cars like Lamborghini which is part of the Volkswagen Group. <hr size="1" width="100%"> </td> </tr> <!-- INDIA_STORY_END -->|g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES||g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
