s|TAG_META_TITLE|Iron Men 2, Palm Pre, iPhone, Blackberry Bold, Apple iPod Shuffle|g
s|TAG_META_KEYWORDS|Apple iPod Shuffle, Palm Pre, iPhone, Blackberry Bold, Long Term Evolution (LTE) And WiMAX, Scarlett Johansson In Iron Men 2|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/hollywood/actress/scarlett_johansson/hollywood_scarlett_johansson_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/actress/scarlett_johansson/pics/scarlett_johansson_05.jpg" ALT="Scarlett Johansson" TITLE="Scarlett Johansson" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Scarlett Johansson In Iron Men 2</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Scarlett Johansson In Iron Men 2" HREF="http://www.bollywoodmovies.us/news/2009/03_02_2009.html">03/13/2009</A>: </font> <br> <A ALT="" TITLE="Scarlett Johansson" HREF="http://www.bollywoodmovies.us/hollywood/actress/scarlett_johansson/hollywood_scarlett_johansson.html">Scarlett Johansson</A> has joined the cast for the sequel to Iron Men, Scarlett will star as the Black Widow in the <A ALT="" TITLE="Iron Man 2 Movie Review" HREF="http://www.bollywoodmovies.us/hollywood/movie_reviews/2010/iron_man_2.html">Iron Man 2 (2010)</A> opposite Robert Downey Jr. Mickey Rourke has also been signed to play villain Whiplash. The movie is scheduled for May 2010 release and will also bring back <A ALT="" TITLE="Gwyneth Paltrow" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/gwyneth_paltrow/celebrites_gwyneth_paltrow.html">Gwyneth Paltrow</A> returning as Pepper Potts, and Samuel L. Jackson as Nick Fury and Don Cheadle playing Col. James "Rhodey" Rhodes. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/tollywood/actress/priyamani/tollywood_priyamani_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/tollywood/actress/priyamani/pics/priyamani_01.jpg" ALT="Priyamani Tollywood" TITLE="Priyamani Tollywood" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Tamil and Malayalam Film Actress Priyamani Now In Kannada Film</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Tamil and Malayalam Film Actress Priyamani Now In Kannada Film" HREF="http://www.bollywoodmovies.us/news/2009/03_09_2009.html">03/11/2009</A>: </font> <br> <A ALT="" TITLE="Priyamani Tollywood" HREF="http://www.bollywoodmovies.us/tollywood/actress/priyamani/tollywood_priyamani.html">Priyamani</A> a popular actress in Tamil and Malayalam films will now be working in a Kannada film. Many in the past have tried to bring Priyamani into Kannada films and now producer Aditya Babu has made that happen by signing her in the movie Ram starring opposite Puneet Rajkumar. The movie has already started to shoot with the next shooting scheduled for Bangalore. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD|<!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="Apple iPod Shuffle" HREF="http://www.bollywoodmovies.us/news/2009/03_09_2009.html">03/11/2009</A>: <br> Apple today announced the availability of a new <A ALT="" TITLE="Apple iPod Shuffle" HREF="http://www.bollywoodmovies.us/info/technology.html">iPod Shuffle</A> . It has been redesigned and provides more capability and functionality. It's half the size of the last generation but with twice the capacity, the latest Shuffle provides a way of letting you know what track you're listening to: It talks. It's available now for $79, the new Shuffle is billed as the "world's smallest music player," and indeed, it looks tiny just 1.8 by 0.7 by 0.3 inches, a little smaller than a AA battery. It also comes with new in line remote on the earphone cord, from which you can adjust the volume, pause and skip tracks. This also is its drawback since third party earphones won't work. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END --><!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="What Palm Pre Brings To The Table" HREF="http://www.bollywoodmovies.us/news/2009/03_09_2009.html">03/09/2009</A>: <br> Here are some of the things that the <A ALT="" TITLE="Palm Pre" HREF="http://www.bollywoodmovies.us/info/cell_phones.html">Palm Pre</A> bring to the table: Multitouch Portrait Screen and Slide-Down Keyboard, Design, Size and Form Factor smaller then iPhone and BlackBerry Bold, Speed : new webOS and high end processor makes web browser easier and faster, Multitasking, Built In WiFi, GPS, EvDO Rev. A, 8GB Storage, 3.0 Megapixel Camera with Built In LED Flash and Large Back Speaker, 3.5mm Stereo Headphone Jack, Removable Battery, Ambient Light, Accelerometer and Proximity Sensors. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END --><!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="Long Term Evolution (LTE) And WiMAX" HREF="http://www.bollywoodmovies.us/news/2009/03_09_2009.html">03/09/2009</A>: <br> <A ALT="" TITLE="Long Term Evolution (LTE)" HREF="http://www.bollywoodmovies.us/info/technology.html">Long Term Evolution (LTE)</A> is the next big thing in mobile wireless broadband. While WiMAX is being driven mostly by computer industry players, LTE is the leading edge broadband technology of the cellphone service providers. In some sense WiMAX and LTE are similar in that they both use technologies such as OFDM (orthogonal frequency division multiplexing) signal types and MIMO (multiple-input, multiple-output) signal processing algorithms. WiMAX and LTE are both IP (Internet Protocol) based technologies. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END -->|g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/models/marisa_miller/models_marisa_miller_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/marisa_miller/pics/marisa_miller_01.jpg" ALT="Marisa Miller" TITLE="Marisa Miller" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/hollywood/actress/pamela_anderson/hollywood_pamela_anderson_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/actress/pamela_anderson/pics/pamela_anderson_02.jpg" ALT="Pamela Anderson" TITLE="Pamela Anderson" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing March 13, 2009: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Gulaal <BR> Jai Veeru </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
