s|TAG_META_TITLE|Idiot Box, Lahore, Love Sex Aur Dhokha, Shaapit, Priyanka Chopra, Fear Factor 3 Katron Ke Khiladi|g
s|TAG_META_KEYWORDS|Idiot Box, Lahore, Love Sex Aur Dhokha, Shaapit, Priyanka Chopra, Fear Factor 3 Katron Ke Khiladi|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/priyanka_chopra/bollywood_priyanka_chopra_photo_gallery_05.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/priyanka_chopra/pics/priyanka_chopra_45.jpg" ALT="Priyanka Chopra" TITLE="Priyanka Chopra" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Priyanka Chopra To Host Fear Factor 3 Katron Ke Khiladi (FF KKK)</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Priyanka Chopra To Host Fear Factor 3 Katron Ke Khiladi" HREF="http://www.bollywoodmovies.us/news/2010/03_15_2010.html">03/20/2010</A>: </font> <br> <A ALT="" TITLE="Priyanka Chopra" HREF="http://www.bollywoodmovies.us/actress/priyanka_chopra/bollywood_priyanka_chopra.html">Priyanka Chopra</A> has been signed to host <A ALT="" TITLE="Fear Factor 3 Khatron Ke Khiladi" HREF="http://www.bollywoodmovies.us/tv_shows/fear_factor_khatron_ke_khiladi/fear_factor_khatron_ke_khiladi.html">Fear Factor 3 Khatron Ke Khiladi</A> . The show is currently being hosted by <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A> but next season will be hosted by Priyanka Chopra. The thrid install of the popular Colors TV show will focus on cricket in an effort to weave together the magic of IPL and Bollywood. Early that week, Priyanka picked up the National award for her role in movie <A ALT="" TITLE="Fashion Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/fashion.html">Fashion (2008)</A> . <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actress/barbara_mori/bollywood_barbara_mori_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/barbara_mori/pics/barbara_mori_03.jpg" ALT="Barbara Mori" TITLE="Barbara Mori" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/tricia_helfer/models_tricia_helfer_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/tricia_helfer/pics/tricia_helfer_03.jpg" ALT="Tricia Helfer" TITLE="Tricia Helfer" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing March 19, 2010" HREF="http://www.bollywoodmovies.us/news/2010/03_15_2010.html">Movie Releasing March 19, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Idiot Box <hr size="1" width="100%"> Lahore <hr size="1" width="100%"> Love Sex Aur Dhokha <hr size="1" width="100%"> Shaapit <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK|<!-- TABLE_SEPARATOR_START --> <TABLE WIDTH=100% ALIGN="center" cellspacing="0" border="1" bordercolor="blue"> <TR> <TD> <center><b><font color="#0033cc" size="4">Top 10 Songs Of The Week (03/12/2010)</font></b></center> <hr size="2" width="100%"s color="#0000FF"> <b>10.</b> Na Ghar Ke Na Ghaat Ke <hr size="2" width="100%"> <b>09.</b> Ishqiya (2010) <hr size="2" width="100%"> <b>08.</b> Well Done Abba (2010) <hr size="2" width="100%"> <b>07.</b> <A ALT="" TITLE="Right Yaaa Wrong Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/right_yaaa_wrong.html">Right Yaaa Wrong (2010)</A> <hr size="2" width="100%"> <b>06.</b> <A ALT="" TITLE="Atithi Tum Kab Jaoge Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/atithi_tum_kab_jaoge.html">Atithi Tum Kab Jaoge (2010)</A> <hr size="2" width="100%"> <b>05.</b> <A ALT="" TITLE="Teen Patti Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/teen_patti.html">Teen Patti (2010)</A> <hr size="2" width="100%"> <b>04.</b> Shaapit (2010) <hr size="2" width="100%"> <b>03.</b> <A ALT="" TITLE="My Name Is Khan (MNIK) Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/my_name_is_khan.html">My Name Is Khan (MNIK) (2010)</A> <hr size="2" width="100%"> <b>02.</b> <A ALT="" TITLE="Karthik Calling Karthik Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/karthik_calling_karthik.html">Karthik Calling Karthik (2010)</A> <hr size="2" width="100%"> <b>01.</b> Prince (2010) <hr size="2" width="100%"> </TD> </TR> </TABLE> <!-- TABLE_SEPARATOR_END -->|g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
