s|TAG_META_TITLE|Riya Sen Maxim India April 2010, Rockstar (2010), Diana Penty, Ranbir Kapoor|g
s|TAG_META_KEYWORDS|Riya Sen Maxim India April 2010, Rockstar (2010), Diana Penty, Ranbir Kapoor|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/diana_penty/bollywood_diana_penty_photo_gallery_08.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/diana_penty/pics/diana_penty_02.jpg" ALT="Diana Penty" TITLE="Diana Penty" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Fashion Model Diana Penty Signed Opposite Ranbir Kapoor</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Fashion Model Diana Penty Signed Opposite Ranbir Kapoor" HREF="http://www.bollywoodmovies.us/news/2010/04_12_2010.html">04/18/2010</A>: </font> <br> Fashion model <A ALT="" TITLE="Riya Sen" HREF="http://www.bollywoodmovies.us/actress/diana_penty/bollywood_diana_penty.html">Diana Penty</A> has been signed by director Imtiaz Ali for his next film. The file is titled <A ALT="" TITLE="Rockstar Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/rockstar.html">Rockstar (2010)</A> with the male lead being played by <A ALT="" TITLE="Ranbir Kapoor" HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor.html">Ranbir Kapoor</A> . The film is being produced by Ashtavinayaka, the producer of <A ALT="" TITLE="Jab We Met Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/jab_we_met.html">Jab We Met (2007)</A> . <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/riya_sen/bollywood_riya_sen_photo_gallery_08.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/riya_sen/pics/riya_sen_64.jpg" ALT="Riya Sen Maxim India April 2010" TITLE="Riya Sen Maxim India April 2010" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Riya Sen On Cover Of Maxim India April 2010 Issue</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Riya Sen On Cover Of Maxim India April 2010 Issue" HREF="http://www.bollywoodmovies.us/news/2010/04_12_2010.html">04/16/2010</A>: </font> <br> <A ALT="" TITLE="Riya Sen" HREF="http://www.bollywoodmovies.us/actress/riya_sen/bollywood_riya_sen.html">Riya Sen</A> is being featured on the cover of April 2010 edition of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . The photos will be part of the Maxim India April 2010 edition. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing April 09, 2010" HREF="http://www.bollywoodmovies.us/news/2010/04_12_2010.html">Movie Releasing April 16, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Paathshala" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/paathshala.html">Paathshala (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Shahid Kapoor" HREF="http://www.bollywoodmovies.us/actor/shahid_kapoor/bollywood_shahid_kapoor_photo_gallery_01.html">Shahid Kapoor </A> , <A ALT="" TITLE="Actress Ayesha Takia" HREF="http://www.bollywoodmovies.us/actress/ayesha_takia/bollywood_ayesha_takia_photo_gallery_01.html">Ayesha Takia </A> </font> , Suniel Shetty, Nana Patekar, Sushant Singh, , Saurabh Shukla <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Phoonk 2" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/phoonk_2.html">Phoonk 2 (2010) </A> <br> Cast: <A ALT="" TITLE="Actor " HREF="http://www.bollywoodmovies.us/actor//bollywood__photo_gallery_01.html"> </A> , <A ALT="" TITLE="Actress Neeru Bajwa" HREF="http://www.bollywoodmovies.us/actress/neeru_bajwa/bollywood_neeru_bajwa_photo_gallery_01.html">Neeru Bajwa </A> </font> <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
