s|TAG_META_TITLE|A. R. Rahman Jai Ho Concert 2010, Actor Ranbir Kapoor, Katrina Kaif, Rajneeti|g
s|TAG_META_KEYWORDS|A. R. Rahman Jai Ho Concert 2010, Actor Ranbir Kapoor, Katrina Kaif, Rajneeti|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/music_director/ar_rahman/bollywood_ar_rahman_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/music_director/ar_rahman/pics/ar_rahman_01.jpg" ALT="AR Rahman" TITLE="AR Rahman" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>A. R. Rahman Jai Ho Concert: The Journey Home World Tour Stars On June 11, 2010</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="A. R. Rahman Jai Ho Concert: The Journey Home World Tour' begins on June 11" HREF="http://www.bollywoodmovies.us/news/2010/05_31_2010.html">05/31/2010</A>: </font> <br> The master of music, <A ALT="" TITLE="AR Rahman" HREF="http://www.bollywoodmovies.us/music_director/ar_rahman/bollywood_ar_rahman.html">AR Rahman</A> has been very busy preparing for the upcoming world tour, the tour is called A. R. Rahman Jai Ho Concert: The Journey Home World. The tour is scheduled to start on June 11, 2010 with shows in around 20 cities globally and will end at London's Wembley Stadium on July 25. The tour kicks off in New York at the famous Nassau Coliseum arena on June 11, 2010. Ritu Beri, an international fashion designer, has designed AR Rahman's outfits for the concert. <BR> Below is the tour schedule: Jun. 11: Uniondale, N.Y. (Nassau Coliseum), Jun. 12: Atlantic City, N.J. (Boardwalk Hall Arena), Jun. 13: Washington, D.C. (Patriot Center), Jun. 18: Chicago, Ill. (Sears Centre Arena), Jun. 19: Detroit, Mich. (Pontiac Silverdome), Jun. 20: Toronto, Ontario (Air Canada Centre), Jun. 26: San Francisco, Calif. (Oracle Arena), Jun. 27: Los Angeles, Calif. (The Forum), Jul. 2: Dallas, Texas (American Airlines Center), Jul. 3: Houston, Texas (Houston Toyota Center), Jul. 9: Amsterdam, Netherlands (Ohio Arena), Jul. 10: Paris, France (Bercy), Jul. 18: Oslo, Norway (Oslo Spektrum), Jul. 23: Glasgow, Scotland (SECC), Jul. 24: Manchester, England (M.E.N. Arena), Jul. 25: London, England (O2 Arena), Jul. 26: London, England (Wembley Stadium), <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/ranbir_kapoor/pics/ranbir_kapoor_13.jpg" ALT="Ranbir Kapoor" TITLE="Ranbir Kapoor" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/katrina_kaif/pics/katrina_kaif_15.jpg" ALT="Katrina Kaif" TITLE="Katrina Kaif" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing June 04, 2010" HREF="http://www.bollywoodmovies.us/news/2010/05_31_2010.html">Movie Releasing June 04, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Rajneeti" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/rajneeti.html">Rajneeti (2008) </A> <br> Cast: <A ALT="" TITLE="Actor Ranbir Kapoor" HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor_photo_gallery_01.html">Ranbir Kapoor </A> , <A ALT="" TITLE="Actress Katrina Kaif" HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif_photo_gallery_01.html">Katrina Kaif </A> </font> , Nana Patekar, Arjun Rampal, Ajay Devgan, Manoj Bajpai, Sarah Thompson <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
