s|TAG_META_TITLE|iPhone 3GS, Kal Kisne Dekha, Vaishali Desai, Trisha Krishnan, Jackie Bhagnani, Wimbledon, Sania Mirza|g
s|TAG_META_KEYWORDS|iPhone 3GS, Kal Kisne Dekha, Vaishali Desai, Trisha Krishnan, Jackie Bhagnani, Sania Mirza, Aegon Classic, Wimbledon, Khatta Meeta Movie Review, Akshay Kumar, Rajnikanth, Kamal Hassan|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/trisha_krishnan/bollywood_trisha_krishnan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/trisha_krishnan/pics/trisha_krishnan_04.jpg" ALT="Trisha Krishnan Kollywood" TITLE="Trisha Krishnan Kollywood" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Trisha Krishnan Going From Kollywood To Bollywood?</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Trisha Krishnan Going From Kollywood To Bollywood?" HREF="http://www.bollywoodmovies.us/news/2009/06_08_2009.html">06/13/2009</A>: </font> <br> One of the top actress of Kollywood (Tamil Film), <A ALT="" TITLE="Trisha Krishnan" HREF="http://www.bollywoodmovies.us/actress/trisha_krishnan/bollywood_trisha_krishnan.html">Trisha Krishnan</A> has been signed by director Priyadarshan to play a role opposite Bollywood's <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A> in movie <A ALT="" TITLE="Khatta Meeta Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/khatta_meeta.html">Khatta Meeta (2009)</A> . The director had introduced Trisha seven years ago to the <A ALT="" TITLE="Kollywood Movies" HREF="http://www.bollywoodmovies.us/kollywood/kollywood.html">Kollywood</A> in movie Lesa Lesa in Tamil. The movie is schedule to start shooting in November 2009. Trisha has already worked with the best in the business like <A ALT="" TITLE="Rajnikanth" HREF="http://www.bollywoodmovies.us/kollywood/actor/rajnikanth/kollywood_rajnikanth.html">Rajnikanth</A> , <A ALT="" TITLE="Kamal Hassan" HREF="http://www.bollywoodmovies.us/actor/kamal_hassan/bollywood_kamal_hassan.html">Kamal Hassan</A> megastar Chiranjeevi. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD|<!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="Apple Intros iPhone 3GS" TITLE="" HREF="http://www.bollywoodmovies.us/news/2009/06_08_2009.html">06/08/2009</A>: <br> At the World Wide Developers Conference in San Francisco, Apple introduced the next generation <A ALT="" TITLE="Apple iPhone" HREF="http://www.bollywoodmovies.us/info/apple_iphone.html">iPhone</A> . The new iPhone will be known as iPhone 3GS and includes features such as more speed, 3 megapixel camera with autofocus and white balancing, ability to record and edit videos on the handset, built in voice controls for hands free operation, cut, copy, and paste capabilities, device tethering, HTTP streaming, auto-fill, multi language support, and built in compass. The new iPhone 3GS will be available on June 19 for $199 for the 16 GB version, and the 32 GB version will cost $299 with a new contract. And the iPhone 3G, 8 GB version now costs $99 with a new two year contract. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END -->|g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/pics/sania_mirza_17.jpg" ALT="Sania Mirza" TITLE="Sania Mirza" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sania Mirza Enters Aegon Classic Semi Final</b> <br> <A ALT="" TITLE="Sania Mirza Enters Aegon Classic Semi Final" HREF="http://www.bollywoodmovies.us/news/2009/06_06_2009.html">06/12/2009</A>: <br> The unseeded Indian, <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> , was able to continue her good run at the Aegon Classic by beating 16th seed Hungarian Melinda Czink in straight sets 6-1, 7-6 (4) on Friday. Sania will now face winner of the other quarter final match between 13th seed Slovakian Magdalena Rybarikova and unseeded Polish Urszula Radwanska. This event is a precursor to Wimbledon. </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing June 12, 2009: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Kal Kisne Dekha" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/kal_kisne_dekha.html">Kal Kisne Dekha (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Jackie Bhagnani" HREF="http://www.bollywoodmovies.us/actor/jackie_bhagnani/bollywood_jackie_bhagnani_photo_gallery_01.html">Jackie Bhagnani </A> , <A ALT="" TITLE="Actress Vaishali Desai" HREF="http://www.bollywoodmovies.us/actress/vaishali_desai/bollywood_vaishali_desai_photo_gallery_01.html">Vaishali Desai </A> </font> , Rishi Kapoor, Irrfan Khan, Javed Jaffrey, Shahrukh Khan, Sanjay Dutt, Abhishek Bachchan, Kunal Kumar, Akshay Kapoor, Azharuddin Ismail, Rubina Ali, Juhi Chawla, , Archana Puran Singh, Rachna Shah, </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Karma - Crime Passion Reincarnation <BR> Zor Lagaa Ke... Haiya! </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
