s|TAG_META_TITLE|Raavan (2010), Abhishek Bachchan, Aishwarya Rai Bachchan, Gul Panag Maxim India June 2010|g
s|TAG_META_KEYWORDS|Raavan (2010), Abhishek Bachchan, Aishwarya Rai Bachchan, Gul Panag Maxim India June 2010|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/gul_panag/bollywood_gul_panag_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/gul_panag/pics/gul_panag_16.jpg" ALT="Gul Panag Maxim India June 2010" TITLE="Gul Panag Maxim India June 2010" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Gul Panag On Cover Of Maxim India June 2010 Issue</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Gul Panag On Cover Of Maxim India June 2010 Issue" HREF="http://www.bollywoodmovies.us/news/2010/06_14_2010.html">06/14/2010</A>: </font> <br> <A ALT="" TITLE="Gul Panag" HREF="http://www.bollywoodmovies.us/actress/gul_panag/bollywood_gul_panag.html">Gul Panag</A> is being featured on the cover of June 2010 edition of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . The photos will be part of the Maxim India June 2010 edition. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/abhishek_bachchan/pics/abhishek_bachchan_07.jpg" ALT="Abhishek Bachchan" TITLE="Abhishek Bachchan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_01.jpg" ALT="Aishwarya Rai" TITLE="Aishwarya Rai" WIDTH="100" HEIGHT="100" BORDER="0"> </A>...<A HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/ranbir_kapoor/pics/ranbir_kapoor_13.jpg" ALT="Ranbir Kapoor" TITLE="Ranbir Kapoor" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/katrina_kaif/pics/katrina_kaif_15.jpg" ALT="Katrina Kaif" TITLE="Katrina Kaif" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing June 18, 2010" HREF="http://www.bollywoodmovies.us/news/2010/06_14_2010.html">Movie Releasing June 18, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Raavan" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/raavan.html">Raavan (2010) </A> <br> Cast: <A ALT="" TITLE="Actor Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan_photo_gallery_01.html">Abhishek Bachchan </A> , <A ALT="" TITLE="Actress Aishwarya Rai" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_01.html">Aishwarya Rai </A> </font> , Vikram, Govinda, Ravi Kishan, Prithviraj Sukumaran, Ravi Kishan, Nikhil Dwivedi, Priyamani, Manisha Koirala <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
