s|TAG_META_TITLE|Shruti Haasan, Gemma Atkinson, Aishwarya Rai (Aishwarya Bachchan), Abhishek Bachchan, lovebirds|g
s|TAG_META_KEYWORDS|Shruti Haasan, Gemma Atkinson, Aishwarya Rai (Aishwarya Bachchan), Abhishek Bachchan, lovebirds|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_07.jpg" ALT="Aishwarya Rai (Aishwarya Bachchan)" TITLE="Aishwarya Rai (Aishwarya Bachchan)" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Bollywood Couple Abhishek And Aishwarya Bachchan Asked To Help PETA</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Bollywood Couple Abhishek And Aishwarya Bachchan Asked To Help PETA" HREF="http://www.bollywoodmovies.us/news/2009/07_06_2009.html">07/09/2009</A>: </font> <br> <A ALT="" TITLE="Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html">Abhishek Bachchan</A> and <A ALT="" TITLE="Aishwarya Rai" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai</A> were approached by animal rights group People for the Ethical Treatment of Animals (PETA) for a photo shoot with lovebirds to bring awareness about the plight of lovebirds. Lovebirds are small members of the parrot family. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/gemma_atkinson/celebrites_gemma_atkinson_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/gemma_atkinson/pics/gemma_atkinson_01.jpg" ALT="Gemma Atkinson" TITLE="Gemma Atkinson" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/shruti_haasan/bollywood_shruti_haasan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/shruti_haasan/pics/shruti_haasan_09.jpg" ALT="Shruti Haasan" TITLE="Shruti Haasan" WIDTH="100" HEIGHT="100" BORDER="0"> </A>..<A HREF="http://www.bollywoodmovies.us/hollywood/actress/jennifer_garner/hollywood_jennifer_garner_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/actress/jennifer_garner/pics/jennifer_garner_09.jpg" ALT="Jennifer Garner" TITLE="Jennifer Garner" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/holly_madison/models_holly_madison_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/holly_madison/pics/holly_madison_01.jpg" ALT="Holly Madison" TITLE="Holly Madison" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g

#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing July 10, 2009: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Dekh Bhai Dekh <hr size="1" width="100%"> Mohan Das - A Man Lost In His Own Nation <hr size="1" width="100%"> Morning Walk <hr size="1" width="100%"> Sankat City <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Shortcut, The Con Is On" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/shortcut.html">Shortcut, The Con Is On (2008) </A> <br> Cast: <A ALT="" TITLE="Actor Akshaye Khanna" HREF="http://www.bollywoodmovies.us/actor/akshaye_khanna/bollywood_akshaye_khanna_photo_gallery_01.html">Akshaye Khanna </A> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END --> <!-- TABLE_SEPARATOR_START --> <TABLE ALIGN="center" cellspacing="0" border="1" bordercolor="white"> <TR> <TD>|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
