s|TAG_META_TITLE|Partner Movie, Lara Dutta, Sania Mirza, Sarah Jessica Parker, Megan Fox, Madame Tussauds|g
s|TAG_META_KEYWORDS|Partner Movie, Lara Dutta, Sania Mirza, Sarah Jessica Parker, Megan Fox, Madame Tussauds|g
#
s|TAG_NEWS_WITH_IMAGE||g
#
s|TAG_NEWS_WITHOUT_IMAGE|<!-- TV_SHOWS_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/07_16_2007.html">07/21/2007</A>: <br> Three female and one male ended up in the bottom four. It was Puja, the much favoured Deepali, Charu and Abhishek in the bottom four this week. I think the female are not getting enough votes and the male's contestants seem to be getting a lot more votes from female fans. It was yet another female, Charu, leaving the stage of Indian Idol. <hr size="1" width="100%"> </td> </tr> <!-- TV_SHOWS_END --> <!-- TV_SHOWS_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/07_16_2007.html">07/20/2007</A>: <br> On today's show the girl held there foot down and performed great. The guys will have to suffer a loss this time. From the girls, Ankita performed really good and even pulled the guest star, Govinda, on the stage for song and dance. She was followed by Amit, who for the second time came thru with a great performance. <BR> I think that Prashant, Abhishek, Charu and maybe Puja could end up in the bottom four. <hr size="1" width="100%"> </td> </tr> <!-- TV_SHOWS_END -->|g
#
s|TAG_NEWS_WORLD|<!-- STORY_START --> <TR ALIGN="left"> <TD WIDTH=900 bgcolor="white"> <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/07_16_2007.html">07/22/2007</A>: <br> The famous Madame Tussauds will soon be opening in Washington D.C. It is currently under construction and is scheduled to open in October. The museum will feature was statues of George W. Bush, Hillary Clinton, and many more US personalities. </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR ALIGN="left"> <TD WIDTH=900 bgcolor="white"> <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/07_16_2007.html">07/16/2007</A>: <br> A 6.8 magnitude earthquake struck Japan on Monday, killing eight people while injuring hundreds of people. The quake also caused fire and radioactive water leak at the world's largest nuclear plant, Kashiwazaki. The day of the quake was Marine Day, a national holiday in Japan. </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/pics/sania_mirza_04.jpg" ALT="Tennis Player Mirza Photo Gallery" TITLE="Tennis Player Mirza Photo Gallery" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sania Mirza Out Of Cincinnati Open</b> <br> <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/07_16_2007.html">07/22/2007</A>: <br> <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> lost to top seed Anna Chakvetadze of Russia 2-6, 7-5, 3-6 to end her run at the women's open in Cincinnati. Anna Chekvetadze willl play Akiko Morigami in the finals. </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END --><!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/pics/sania_mirza_08.jpg" ALT="Tennis Player Mirza Photo Gallery" TITLE="Tennis Player Mirza Photo Gallery" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sania Mirza Moves To Quarter Finals</b> <br> <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/07_16_2007.html">07/20/2007</A>: <br> <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> beat Varvara Lepchenko from Uzbekistan 6-2, 6-2 in the Cincinnati hardcourt tournament. Russian Anna Chakvetadze also reached the quarter-finals by defeating Anda Perianu of Romanian. </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/sarah_jessica_parker/celebrites_sarah_jessica_parker.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/sarah_jessica_parker/pics/sarah_jessica_parker_01.jpg" ALT="Hollywood, Celebrites, Actresses Sarah Jessica Parker" TITLE="Hollywood, Celebrites, Actresses Sarah Jessica Parker" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/megan_fox/celebrites_megan_fox.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/megan_fox/pics/megan_fox_07.jpg" ALT="Hollywood, Celebrites, Actresses Megan Fox" TITLE="Hollywood, Celebrites, Actresses Megan Fox" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing July 20, 2007: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Partner" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/partner.html">Partner (2006) </A> <br> Cast: <A ALT="" TITLE="Bollywood Movie Review, Salman Khan" HREF="http://www.bollywoodmovies.us/actor/salman_khan/bollywood_salman_khan_photo_gallery_01.html">Salman Khan </A> , <A ALT="" TITLE="Bollywood Movie Review, Lara Dutta" HREF="http://www.bollywoodmovies.us/actress/lara_dutta/bollywood_lara_dutta_photo_gallery_01.html">Lara Dutta </A> </font> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_DATE_MONTH|2007_07_Jul|g