s|TAG_META_TITLE|Love Aaj Kal, Deepika Padukone, Saif Ali Khan, Delhi 6, Oscar|g
s|TAG_META_KEYWORDS|Love Aaj Kal, Deepika Padukone, Saif Ali Khan, Delhi 6 Going To The Oscar|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/sonam_kapoor/bollywood_sonam_kapoor_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/sonam_kapoor/pics/sonam_kapoor_07.jpg" ALT="Sonam Kapoor" TITLE="Sonam Kapoor" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Delhi 6 Going To The Oscar?</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Delhi 6 Going To The Oscar?" HREF="http://www.bollywoodmovies.us/news/2009/07_27_2009.html">07/28/2009</A>: </font> <br> <A ALT="" TITLE="Delhi 6, Dilli 6 Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/delhi_6.html">Delhi 6, Dilli 6 (2008)</A> starring <A ALT="" TITLE="Sonam Kapoor" HREF="http://www.bollywoodmovies.us/actress/sonam_kapoor/bollywood_sonam_kapoor.html">Sonam Kapoor</A> and <A ALT="" TITLE="Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html">Abhishek Bachchan</A> has been submitted by director Rakeysh Omprakash Mehra to the Indian Motion Pictures' Producers Association (IMPPA) to be sent to the Film Federation of India for sending it as India's entry in the Best Foreign Language Film category of the Academy Awards. In order for a film to qualify, it should have been released or should be releasing between October 1, 2008 and September 30, 2009 and should have run for seven consecutive days at least. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/models/diana_penty/models_diana_penty_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/diana_penty/pics/diana_penty_02.jpg" ALT="Diana Penty" TITLE="Diana Penty" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/michael_joseph_jackson/celebrites_michael_joseph_jackson_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/michael_joseph_jackson/pics/michael_joseph_jackson_01.jpg" ALT="Michael Joseph Jackson" TITLE="Michael Joseph Jackson" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing July 31, 2009: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Perfect Mismatch <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Love Aaj Kal" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/love_aaj_kal.html">Love Aaj Kal (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Saif Ali Khan" HREF="http://www.bollywoodmovies.us/actor/saif_ali_khan/bollywood_saif_ali_khan_photo_gallery_01.html">Saif Ali Khan </A> , <A ALT="" TITLE="Actress Deepika Padukone" HREF="http://www.bollywoodmovies.us/actress/deepika_padukone/bollywood_deepika_padukone_photo_gallery_01.html">Deepika Padukone </A> </font> , Rahul Khanna, Rishi Kapoor, Florence Brudenell Bruce </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
