s|TAG_META_TITLE|Aishwarya Rai, iphone, gps, tomtom, Sophie Choudry Maxim India August 2009|g
s|TAG_META_KEYWORDS|Aishwarya Rai, Sick, Abhishek Bachchan, Amitabh Bachchan, Singapore, iphone, gps, tomtom, itunes, Sophie Choudry Maxim India August 2009|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/sophie_choudry/bollywood_sophie_choudry_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/sophie_choudry/pics/sophie_choudry_05.jpg" ALT="Sophie Choudry Maxim India August 2009" TITLE="Sophie Choudry Maxim India August 2009" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sophie Choudry On Cover Of Maxim India August 2009 Issue</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Sophie Choudry On Cover Of Maxim India June 2009 Issue" HREF="http://www.bollywoodmovies.us/news/2009/08_17_2009.html">08/18/2009</A>: </font> <br> <A ALT="" TITLE="Sophie Choudry" HREF="http://www.bollywoodmovies.us/actress/sophie_choudry/bollywood_sophie_choudry.html">Sophie Choudryr</A> is being featured on the cover of August 2009 edition of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . The photos will be part of the Maxim India August 2009 edition. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_22.jpg" ALT="Aishwarya Rai (Aishwarya Bachchan)" TITLE="Aishwarya Rai (Aishwarya Bachchan)" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Aishwarya Rai Is Ill?</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Aishwarya Rai Takes Karate Lessons" HREF="http://www.bollywoodmovies.us/news/2009/08_17_2009.html">08/17/2009</A>: </font> <br> <A ALT="" TITLE="Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan.html">Amitabh Bachchan</A> who is currently in Singapore said that former Miss World and daughter in law, <A ALT="" TITLE="Aishwarya Rai" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai</A> has chest infection and flu-like symptoms is now making a slow recovery. The 66 year old actor is in Singapore to be with his friend and Samajwadi Party leader Amar Singh, who underwent medical treatment there. Aishwarya Rai is currently in Ooty, where she is shooting for Mani Ratnam’s film <A ALT="" TITLE="Raavan Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/raavan.html">Raavan (2010)</A> with her husband <A ALT="" TITLE="Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html">Abhishek Bachchan</A> . <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD|<!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="Car Navigation app headed to iPhone" HREF="http://www.bollywoodmovies.us/news/2009/08_17_2009.html">08/17/2009</A>: <br> TomTom, the maker of stand-alone GPS system has announced the avaliablity of a $99 application for the <A ALT="" TITLE="Apple iPhone" HREF="http://www.bollywoodmovies.us/info/apple_iphone.html">iPhone</A> to offer GPS based voice navigation. The new application can be purchased via iTunes . <A ALT="" TITLE="Apple iPhone TomTom App" HREF="http://www.tomtom.com/tomtom-app">(TomTom App)</A> The application offer new features and a car kit that includes a windsheild mount. The features includesd are: An IQ routes system that provides users with the fastest routes and directions based on drivers’ collective experiences, A tap and go interface that allows drivers to zoom in and out of various locations, ability to choose a person from your iPhone contacts and travel to their address, directions to a restaurant, allows you to make reservations by calling ahead, An option to view directions horizontally or vertically, in 2-D or 3-D, and a nighttime and daytime view, ability to listen to directions in 18 different languages. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END -->|g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/jennifer_ellison/celebrites_jennifer_ellison_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/jennifer_ellison/pics/jennifer_ellison_02.jpg" ALT="Jennifer Ellison" TITLE="Jennifer Ellison" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/giselle_monteiro/bollywood_giselle_monteiro_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/giselle_monteiro/pics/giselle_monteiro_01.jpg" ALT="Giselle Monteiro" TITLE="Giselle Monteiro" WIDTH="100" HEIGHT="100" BORDER="0"> </A>..<A HREF="http://www.bollywoodmovies.us/models/diana_penty/models_diana_penty_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/diana_penty/pics/diana_penty_02.jpg" ALT="Diana Penty" TITLE="Diana Penty" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/michael_joseph_jackson/celebrites_michael_joseph_jackson_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/michael_joseph_jackson/pics/michael_joseph_jackson_01.jpg" ALT="Michael Joseph Jackson" TITLE="Michael Joseph Jackson" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing August 21, 2009: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Fast Forward <hr size="1" width="100%"> Shadow <hr size="1" width="100%"> Sikandar <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
