s|TAG_META_TITLE|Six months pregnant Aishwarya shoots an ad for Lux|g
s|TAG_META_KEYWORDS|Six months pregnant Aishwarya shoots an ad for Lux|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_21.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_184.jpg" ALT="Aishwarya Rai Pregnant Lux" TITLE="Aishwarya Rai Pregnant Lux" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Six months pregnant Aishwarya shoots an ad for Lux</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Six months pregnant Aishwarya shoots an ad for Lux" HREF="http://www.bollywoodmovies.us/news/2011/08_15_2011.html">08/18/2011</A>: </font> <br> <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> is about six months pregnant and she is still able to fulfilling her commitments. Aishwarya recently shot an ad for Lux soap in Bangkok. Dressed in a peach grown, she looked elegant and stunning and was full of energy. Her baby bump was quite evident. Her costume was designed by ace designer Manish Malhotra while her makeup was done by Mickey Contractor. After completing the shoot in Bangkok, she flew off to London with her husband <A ALT="" TITLE="Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html">Abhishek Bachchan</A>. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/shahrukh_khan/pics/shahrukh_khan_07.jpg" ALT="Shahrukh Khan (SRK)" TITLE="Shahrukh Khan (SRK)" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/anushka_sharma/bollywood_anushka_sharma_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/anushka_sharma/pics/anushka_sharma_06.jpg" ALT="Anushka Sharma" TITLE="Anushka Sharma" WIDTH="100" HEIGHT="100" BORDER="0"> </A> |g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing August 19, 2011" HREF="http://www.bollywoodmovies.us/news/2011/08_15_2011.html">Movie Releasing August 19, 2011</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Chatur Singh Two Star <hr size="1" width="100%"> Cover Story <hr size="1" width="100%"> Not A Love Story <hr size="1" width="100%"> Sahi Dhandhe Galat Bande <hr size="1" width="100%"> Yaara O Dildaara <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
