s|TAG_META_TITLE|gPhone, Gateway, Acer, Dhokha, Sholay, Ke Aag, Ki Aag|g
s|TAG_META_KEYWORDS|gPhone, Gateway, Acer, Dhokha, Sholay, Ke Aag, Ki Aag|g
#
s|TAG_NEWS_WITH_IMAGE||g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD|<!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="Acer To Buy Gateway" HREF="http://www.bollywoodmovies.us/news/2007/08_27_2007.html">08/27/2007</A>: <br> US computer maker Gateway to be acquired by Taiwan personal computer supplier, Acer, for $710 million. This will put Acer past the Lenovo Group Ltd. as the world's third-biggest PC maker. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END --> <!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="gPhone News" HREF="http://www.bollywoodmovies.us/news/2007/08_27_2007.html">08/27/2007</A>: <br> Google maybe close to the launch of it's phone service. The mobile phone is called gPhone and is awaiting final ok and carrier agreement before it launch. Recently there was news that Google may be interested in bidding on spectrum. Lets see if Google will lauch the gPhone? <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END -->|g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center" colspan=2> <A ALT="" TITLE="Tennis Sport News" HREF="http://www.bollywoodmovies.us/news/2007/08_27_2007.html">09/02/2007</A>: <br> <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> 's prusit for a grand slam title was stopped by 6th seed Russian Anna Chakvetadze at the U.S. Open being played in New York. Anna defeated the Indian ace 6-2, 6-3. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END --><!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/pics/sania_mirza_12.jpg" ALT="Sania Mirza" TITLE="Sania Mirza" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sania Mirza Beats Laura Granville To Advance To 3rd Round At US Open</b> <br> <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/08_27_2007.html">08/31/2007</A>: <br> <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> defeated Laura Granville 6-3, 7-5 in the 2nd round at the US open to advance. Sania will now face sixth seeded Russian Anna Chakvetadze. Anna has defeated Sania 3 times already this year at the Hobart semi-final, Cincinnati semi-final and final at Stanford respectivily and has already won four tournaments this year. This will be a good test for Sania. </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END --><!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Tennis Sport News" HREF="http://www.bollywoodmovies.us/news/2007/08_27_2007.html">08/28/2007</A>: <br> <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> won her first round match against Estonian Kaia Kanepi 6-2, 6-7 (5/7), 6-1 to advance to the second round at the US Open tennis championships being played in Flushing Meadows, New York. Sania will face 60th ranked American Laura Granville in the second round. Sania had her best Grand Slam showing back in 2006 US Open where she advanced to round of 16 and was defeated by <A ALT="" TITLE="Maria Sharapova" HREF="http://www.bollywoodmovies.us/sports/tennis/maria_sharapova/tennis_maria_sharapova.html">Maria Sharapova</A> of Russia. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/abhishek_bachchan/pics/abhishek_bachchan_01.jpg" ALT="Abhishek Bachchan" TITLE="Abhishek Bachchan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_05.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_43.jpg" ALT="Aishwarya Rai Wax Statue" TITLE="Aishwarya Rai Wax Statue" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing August 31, 2007: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Dhokha" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/dhokha.html">Dhokha (2007) </A> <br> Cast: <A ALT="" TITLE="Bollywood Movie Review, Tulip Joshi" HREF="http://www.bollywoodmovies.us/actress/tulip_joshi/bollywood_tulip_joshi_photo_gallery_01.html">Tulip Joshi </A> </font> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Sholay, Ke Aag, Ki Aag" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/sholay.html">Sholay, Ke Aag, Ki Aag (2006) </A> <br> Cast: <A ALT="" TITLE="Bollywood Movie Review, Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan_photo_gallery_01.html">Amitabh Bachchan </A> , <A ALT="" TITLE="Bollywood Movie Review, Sushmita Sen" HREF="http://www.bollywoodmovies.us/actress/sushmita_sen/bollywood_sushmita_sen_photo_gallery_01.html">Sushmita Sen </A> </font> </td> </tr> <!-- REVIEW_START_END --> <BR> Victoria No. 203 </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_DATE_MONTH|2007_08_Aug|g