s|TAG_META_TITLE|Udita Goswami, Sachin Tendulkar, Indian Idol 3|g
s|TAG_META_KEYWORDS|Sachin Tendulkar, Udita Goswami, Aggar, Tushar Kapoor, Indian Idol 3|g
#
s|TAG_NEWS_WITH_IMAGE||g
#
s|TAG_NEWS_WITHOUT_IMAGE|<A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/09_10_2007.html">09/14/2007</A>: <br> Today begin the final lap for the two remaining contestants for the <A ALT="" TITLE="Indian Idol 3" HREF="http://www.bollywoodmovies.us/indian_idol/season_3/indian_idol.html">Indian Idol 3</A>, <A ALT="" TITLE="Amit Paul" HREF="http://www.bollywoodmovies.us/singer/amit_paul/bollywood_amit_paul.html">Amit Paul</A> and Prashant Tamang. Who will the next Indian Idol, Amit or Prashant? Amit has the great voice and the personality, but Prashant seems to have the public. Only time will tell who takes the next crown of Indian Idol.|g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Cricket News" HREF="http://www.bollywoodmovies.us/news/2007/09_10_2007.html">09/11/2007</A>: <br> Today marked a new beginning in the world of cricket. The Twenty20 cricket format will be used during the ICC World Twenty20 tournament being held in South Africa. The tournament will have 12 teams divided into 4 group play the 1st round. The teams are Australia, Bangladesh, England, India, Kenya, New Zealand, Pakistan, Scotland, South Africa, Sri Lanka, West Indies, and Zimbabwe. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/hollywood/actress/jessica_alba/hollywood_jessica_alba_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/actress/jessica_alba/pics/jessica_alba_04.jpg" ALT="Jessica Alba" TITLE="Jessica Alba" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/sports/cricket/sachin_tendulkar/cricket_sachin_tendulkar_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/cricket/sachin_tendulkar/pics/sachin_tendulkar_08.jpg" ALT="Sachin Tendulkar Cricket" TITLE="Sachin Tendulkar Cricket" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing September 14, 2007: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Aggar" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/aggar.html">Aggar (2007) </A> <br> Cast: <A ALT="" TITLE="Bollywood Movie Review, Tushar Kapoor" HREF="http://www.bollywoodmovies.us/actor/tushar_kapoor/bollywood_tushar_kapoor_photo_gallery_01.html">Tushar Kapoor </A> , <A ALT="" TITLE="Bollywood Movie Review, Udita Goswami" HREF="http://www.bollywoodmovies.us/actress/udita_goswami/bollywood_udita_goswami_photo_gallery_01.html">Udita Goswami </A> </font> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_DATE_MONTH|2007_09_Sep|g