s|TAG_META_TITLE|Bigg Boss 3, Wake up Sid, Ranbir Kapoor, Konkona Sen Sharma, Sherlyn Chopra|g
s|TAG_META_KEYWORDS|Bigg Boss 3, Wake up Sid, Ranbir Kapoor, Konkona Sen Sharma, Top 10 Songs Of The Week, Sherlyn Chopra|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/sherlyn_chopra/bollywood_sherlyn_chopra_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/sherlyn_chopra/pics/sherlyn_chopra_01.jpg" ALT="Sherlyn Chopra, Bigg Boss 3" TITLE="Sherlyn Chopra, Bigg Boss 3" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Bigg Boss 3, Sherlyn Chopra As Contestant</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Bigg Boss 3, Sherlyn Chopra As Contestant" HREF="http://www.bollywoodmovies.us/news/2009/09_28_2009.html">10/01/2009</A>: </font> <br> Bollywood movie actress <A ALT="" TITLE="Sherlyn Chopra" HREF="http://www.bollywoodmovies.us/actress/sherlyn_chopra/bollywood_sherlyn_chopra.html">Sherlyn Chopra</A> will be starring in <A ALT="" TITLE="Bigg Boss 3" HREF="http://www.bollywoodmovies.us/tv_shows/bigg_boss/bigg_boss.html">Bigg Boss 3</A> . The rumors has it that the show wanted to get Baba Ramdev on board but he opted out. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE|<!-- TV_SHOWS_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2009/09_28_2009.html">09/30/2009</A> <br> On today's show, Archana mother in laws asks her to call her mom, Sulochana, to get her to send back the gold bangles and the real necklace back to her, which Manav overhears. Manjusha tells the family that she was the one that replaced the real gold necklace with the silver gold plated necklace to save money for her daughter eduction. Varsha's boss invites all of the office staff for his birthday celebration. Manav later gives Archana a gold necklace to give to her mom, Sulochana, so she can give it to his mom becuase he knows that his mom is doing wrong and wants to earn the trust and love of Archana and hence make the nice gesture. <hr size="1" width="100%"> </td> </tr> <!-- TV_SHOWS_END -->|g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/ranbir_kapoor/pics/ranbir_kapoor_07.jpg" ALT="Ranbir Kapoor" TITLE="Ranbir Kapoor" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/konkona_sen_sharma/bollywood_konkona_sen_sharma_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/konkona_sen_sharma/pics/konkona_sen_sharma_01.jpg" ALT="Konkona Sen Sharma" TITLE="Konkona Sen Sharma" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing October 02, 2009" HREF="http://www.bollywoodmovies.us/news/2009/09_28_2009.html">Movie Releasing October 02, 2009</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Do Knot Disturb <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Wake up Sid" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/wake_up_sid.html">Wake up Sid (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Ranbir Kapoor" HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor_photo_gallery_01.html">Ranbir Kapoor </A> , <A ALT="" TITLE="Actress Konkona Sen Sharma" HREF="http://www.bollywoodmovies.us/actress/konkona_sen_sharma/bollywood_konkona_sen_sharma_photo_gallery_01.html">Konkona Sen Sharma </A> </font> , Rahul Khanna, </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK|<center><b><font color="#0033cc" size="4">Top 10 Songs Of The Week (09/21/2009)</font></b></center> <hr size="2" width="100%"s color="#0000FF"> <b>10.</b> <A ALT="" TITLE="Acid Factory Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/acid_factory.html">Acid Factory (2009)</A> <hr size="2" width="100%"> <b>09.</b> <A ALT="" TITLE="London Dreams Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/london_dreams.html">London Dreams (2009)</A> <hr size="2" width="100%"> <b>08.</b> Do Knot Disturb <hr size="2" width="100%"> <b>04.</b> <A ALT="" TITLE="Kaminay Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/kaminay.html">Kaminay (2009)</A> <hr size="2" width="100%"> <b>07.</b> <A ALT="" TITLE="All The Best Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/all_the_best.html">All The Best (2009)</A> <hr size="2" width="100%"> <b>06.</b> <A ALT="" TITLE="Main Aur Mrs Khanna Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/main_aur_mrs_khanna.html">Main Aur Mrs Khanna (2009)</A> <hr size="2" width="100%"> <b>05.</b> <A ALT="" TITLE="Blue Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/blue.html">Blue (2009)</A> <hr size="2" width="100%"> <b>03.</b> <A ALT="" TITLE="Whats Your Raashee Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/whats_your_raashee.html">Whats Your Raashee (2009)</A> <hr size="2" width="100%"> <b>02.</b> <A ALT="" TITLE="Wake up Sid Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/wake_up_sid.html">Wake up Sid (2009)</A> <hr size="2" width="100%"> <b>01.</b> Dil Bole Hadippa <hr size="2" width="100%">|g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
