s|TAG_META_TITLE|Acid Factory, Bigg Boss 3 Contestants|g
s|TAG_META_KEYWORDS|Acid Factory, Jenny McCarthy, Jennifer Morrison, House TV Show, Bigg Boss 3 Contestants|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/sherlyn_chopra/bollywood_sherlyn_chopra_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/sherlyn_chopra/pics/sherlyn_chopra_21.jpg" ALT="Sherlyn Chopra, Bigg Boss 3" TITLE="Sherlyn Chopra, Bigg Boss 3" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Bigg Boss 3 Contestants</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Bigg Boss 3 Contestants" HREF="http://www.bollywoodmovies.us/news/2009/10_05_2009.html">10/05/2009</A>: </font> <br> The list of contestants for the new season of <A ALT="" TITLE="Bigg Boss 3" HREF="http://www.bollywoodmovies.us/tv_shows/bigg_boss/bigg_boss.html">Bigg Boss 3</A> on tv channel Colors have been announced. The show will be hosted by <A ALT="" TITLE="Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan.html">Amitabh Bachchan</A> . The list includes Bollywood movie actress <A ALT="" TITLE="Sherlyn Chopra" HREF="http://www.bollywoodmovies.us/actress/sherlyn_chopra/bollywood_sherlyn_chopra.html">Sherlyn Chopra</A> , Shilpa's little sister <A ALT="" TITLE="Shamita Shetty" HREF="http://www.bollywoodmovies.us/actress/shamita_shetty/bollywood_shamita_shetty.html">Shamita Shetty</A> . Aditi Gowitrikar a former Mrs World 2001, ex-Gladrags champion who also starred on first season of Khatron Ke Khiladi. Music director Ismail Darbar sho provided hit songs from Hum Dil De Chuke Sanam, Tera Jadoo Chal Gaya and <A ALT="" TITLE="Devdas Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2002/devdas.html">Devdas (2002)</A> . Jaya Sawant, mother of Rakhi Sawant. German super model, singer and actress Claudia Ciesla. Former Miss India and Bollywood actress from the the 80s Poonam Dhillon. Comedian Raju Srivastav, designer Rohit Varma, Kamaal R Khan, Vindoo Dara Singh, and the married couple Bakhtiyar and Tanaz Irani. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/jennifer_morrison/celebrites_jennifer_morrison_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/jennifer_morrison/pics/jennifer_morrison_01.jpg" ALT="Jennifer Morrison" TITLE="Jennifer Morrison" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/jenny_mccarthy/celebrites_jenny_mccarthy_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/jenny_mccarthy/pics/jenny_mccarthy_08.jpg" ALT="Jenny McCarthy" TITLE="Jenny McCarthy" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing October 09, 2009" HREF="http://www.bollywoodmovies.us/news/2009/10_05_2009.html">Movie Releasing October 09, 2009</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> 3 Nights 4 Days <hr size="1" width="100%"> Shaabash! You Can Do It <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Acid Factory" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/acid_factory.html">Acid Factory (2008) </A> <br> Cast: <A ALT="" TITLE="Actor Fardeen Khan" HREF="http://www.bollywoodmovies.us/actor/fardeen_khan/bollywood_fardeen_khan_photo_gallery_01.html">Fardeen Khan </A> , <A ALT="" TITLE="Actress Diya Mirza" HREF="http://www.bollywoodmovies.us/actress/diya_mirza/bollywood_diya_mirza_photo_gallery_01.html">Diya Mirza </A> </font> , Aftab Shivdasani, Dino Morea, Danny Denzongpa, Manoj Bajpai, Irfan Khan, </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
