s|TAG_META_TITLE|Nisha Kothari|g
s|TAG_META_KEYWORDS|Nisha Kothari|g
#
s|TAG_NEWS_WITH_IMAGE||g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actress/nisha_kothari/bollywood_nisha_kothari_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/nisha_kothari/pics/nisha_kothari_01.jpg" ALT="Nisha Kothari" TITLE="Nisha Kothari" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/akshay_kumar/pics/akshay_kumar_01.jpg" ALT="Akshay Kumar" TITLE="Akshay Kumar" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing October 05, 2007: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Go" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/go.html">Go (2006) </A> <br> Cast: <A ALT="" TITLE="Bollywood Movie Review, Gautam" HREF="http://www.bollywoodmovies.us/actor/gautam/bollywood_gautam_photo_gallery_01.html">Gautam </A> , <A ALT="" TITLE="Bollywood Movie Review, Nisha Kothari" HREF="http://www.bollywoodmovies.us/actress/nisha_kothari/bollywood_nisha_kothari_photo_gallery_01.html">Nisha Kothari </A> </font> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_DATE_MONTH|2007_10_Oct|g
#
s|TAG_FORTHCOMING_RELEASES|<!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for De Taali" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/de_taali.html">De Taali (2008) </A> <br> Cast: <A ALT="" TITLE="Bollywood Movie Review, Aftab Shivdasani" HREF="http://www.bollywoodmovies.us/actor/aftab_shivdasani/bollywood_aftab_shivdasani_photo_gallery_01.html">Aftab Shivdasani </A> , <A ALT="" TITLE="Bollywood Movie Review, Ayesha Takia" HREF="http://www.bollywoodmovies.us/actress/ayesha_takia/bollywood_ayesha_takia_photo_gallery_01.html">Ayesha Takia </A> </font> <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Delhi 6" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/delhi_6.html">Delhi 6 (2008) </A> <br> Cast: <A ALT="" TITLE="Actor Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan_photo_gallery_01.html">Abhishek Bachchan </A> , <A ALT="" TITLE="Actress Vidya Balan" HREF="http://www.bollywoodmovies.us/actress/vidya_balan/bollywood_vidya_balan_photo_gallery_01.html">Vidya Balan </A> </font> <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END -->|g
