s|TAG_META_TITLE|Aishwarya Rai, Akshay Kumar, Action Replay|g
s|TAG_META_KEYWORDS|Aishwarya Rai, Akshay Kumar, Action Replay, Katrina Kaif And Hrithik Roshan Shot A Kissing Scene, Zindagi Milegi Na Dobara|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/katrina_kaif/pics/katrina_kaif_25.jpg" ALT="Katrina Kaif" TITLE="Katrina Kaif" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Katrina Kaif And Hrithik Roshan Shot A Kissing Scene?</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Katrina Kaif And Hrithik Roshan Shot A Kissing Scene?" HREF="http://www.bollywoodmovies.us/news/2010/11_01_2010.html">11/03/2010</A>: </font> <br> Rumors have it that director Zoya Akhtar has shot a steamy kissing scene between <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> and <A ALT="" TITLE="Katrina Kaif" HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif.html">Katrina Kaif</A> for their upcoming movie <A ALT="" TITLE="Zindagi Milegi Na Dobara Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/zindagi_milegi_na_dobara.html">Zindagi Milegi Na Dobara (2010)</A> . The scene is said to be about two minutes long which would make it longest lip lock in Bollywood so far. This is the first time the Katrina will be paired opposite Hrithik. This will the first on screen kissing scene for Katrian while, Hrithik has already kissed <A ALT="" TITLE="Aishwarya Rai" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai</A> in movie <A ALT="" TITLE="Dhoom 2, Back In Action Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/dhoom_2.html">Dhoom 2, Back In Action (2006)</A> and <A ALT="" TITLE="Barbara Mori" HREF="http://www.bollywoodmovies.us/actress/barbara_mori/bollywood_barbara_mori.html">Barbara Mori</A> in movie <A ALT="" TITLE="Kites Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/kites.html">Kites (2009)</A> This is the 2nd movie that will be directed by Zoya after her debut film <A ALT="" TITLE="Luck by Chance Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/luck_by_chance.html">Luck by Chance (2008)</A> . The film will also star her brother <A ALT="" TITLE="Farhan Akhtar" HREF="http://www.bollywoodmovies.us/actor/farhan_akhtar/bollywood_farhan_akhtar.html">Farhan Akhtar</A> , along with Abhay Deol and Kalki Koechlin. The movie has been shot in Spain. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing November 05, 2010" HREF="http://www.bollywoodmovies.us/news/2010/11_01_2010.html">Movie Releasing November 05, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Dunno Y Na Jaane Kyun... <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Golmaal 3" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/golmaal_3.html">Golmaal 3 (2010) </A> <br> Cast: <A ALT="" TITLE="Actor Ajay Devgan" HREF="http://www.bollywoodmovies.us/actor/ajay_devgan/bollywood_ajay_devgan_photo_gallery_01.html">Ajay Devgan </A> , <A ALT="" TITLE="Actress Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor_photo_gallery_01.html">Kareena Kapoor </A> </font> , Arshad Warsi, Tusshar Kapoor, Shreyas Talpade, Mithun Chakraborty, <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Action Replay" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/action_replay.html">Action Replay (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar_photo_gallery_01.html">Akshay Kumar </A> , <A ALT="" TITLE="Actress Aishwarya Rai" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_01.html">Aishwarya Rai </A> </font> , Randhir Kapoor, <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/akshay_kumar/pics/akshay_kumar_02.jpg" ALT="Akshay Kumar" TITLE="Akshay Kumar" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_04.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_29.jpg" ALT="Aishwarya Rai" TITLE="Aishwarya Rai" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
