s|TAG_META_TITLE|Ajab Prem Ki Ghazab Kahani, Ranbir Kapoor, Katrina Kaif, Jail, Mugdha Godse|g
s|TAG_META_KEYWORDS|Doutzen Kroes, Ajab Prem Ki Ghazab Kahani, Ranbir Kapoor, Katrina Kaif, Jail, Mugdha Godse|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/deepika_padukone/bollywood_deepika_padukone_photo_gallery_04.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/deepika_padukone/pics/deepika_padukone_28.jpg" ALT="Deepika Padukone" TITLE="Deepika Padukone" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Deepika Padukone Joins Cast Of Khelein Gay Hum Jee Jaan Se</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Deepika Padukone Joins Cast Of Khelein Gay Hum Jee Jaan Se" HREF="http://www.bollywoodmovies.us/news/2009/11_02_2009.html">11/08/2009</A>: </font> <br> Today <A ALT="" TITLE="Deepika Padukone" HREF="http://www.bollywoodmovies.us/actress/deepika_padukone/bollywood_deepika_padukone.html">Deepika Padukone</A> has joined the cast of Khelein Gay Hum Jee Jaan Se to star opposite <A ALT="" TITLE="Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html">Abhishek Bachchan</A> . The movie is being directed by <A ALT="" TITLE="Ashutosh Gowariker" HREF="http://www.bollywoodmovies.us/director/ashutosh_gowariker/bollywood_ashutosh_gowariker.html">Ashutosh Gowariker</A> . Just recently <A ALT="" TITLE="Asin Thottumkal" HREF="http://www.bollywoodmovies.us/actress/asin_thottumkal/bollywood_asin_thottumkal.html">Asin Thottumkal</A> stepped out of the movie and now Deepika has stepped in. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actress/prachi_desai/bollywood_prachi_desai_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/prachi_desai/pics/prachi_desai_04.jpg" ALT="Prachi Desai" TITLE="Prachi Desai" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/doutzen_kroes/models_doutzen_kroes_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/doutzen_kroes/pics/doutzen_kroes_01.jpg" ALT="Doutzen Kroes" TITLE="Doutzen Kroes" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing November 06, 2009" HREF="http://www.bollywoodmovies.us/news/2009/11_01_2009.html">Movie Releasing November 06, 2009</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Ajab Prem Ki Ghazab Kahani" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/ajab_prem_ki_ghazab_kahani.html">Ajab Prem Ki Ghazab Kahani (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Ranbir Kapoor" HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor_photo_gallery_01.html">Ranbir Kapoor </A> , <A ALT="" TITLE="Actress Katrina Kaif" HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif_photo_gallery_01.html">Katrina Kaif </A> </font> , Upen Patel, Rakhi Sawant <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Jail" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/jail.html">Jail (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Neil Mukesh" HREF="http://www.bollywoodmovies.us/actor/neil_mukesh/bollywood_neil_mukesh_photo_gallery_01.html">Neil Mukesh </A> , <A ALT="" TITLE="Actress Mugdha Godse" HREF="http://www.bollywoodmovies.us/actress/mugdha_godse/bollywood_mugdha_godse_photo_gallery_01.html">Mugdha Godse </A> </font> , Manoj Bajpai <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
