s|TAG_META_TITLE|De Dhana Dhan, Trisha Krishnan, Shazahn Padamsee, Mallika Sherawat, Los Angeles, Sushmita Sen Maxim India November 2009|g
s|TAG_META_KEYWORDS|De Dhana Dhan, Trisha Krishnan, Shazahn Padamsee, Mallika Sherawat, Hissss, Los Angeles, Sushmita Sen Maxim India November 2009|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/sushmita_sen/bollywood_sushmita_sen_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/sushmita_sen/pics/sushmita_sen_18.jpg" ALT="Sushmita Sen Maxim India November 2009" TITLE="Sushmita Sen Maxim India November 2009" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sushmita Sen On Cover Of Maxim India November 2009 Issue</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Sushmita Sen On Cover Of Maxim India November 2009 Issue" HREF="http://www.bollywoodmovies.us/news/2009/11_23_2009.html">11/23/2009</A>: </font> <br> <A ALT="" TITLE="Sushmita Sen" HREF="http://www.bollywoodmovies.us/actress/sushmita_sen/bollywood_sushmita_sen.html">Sushmita Sen</A> is being featured on the cover of November 2009 edition of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . The photos will be part of the Maxim India November 2009 edition. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/mallika_sherawat/bollywood_mallika_sherawat_photo_gallery_05.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/mallika_sherawat/pics/mallika_sherawat_40.jpg" ALT="Mallika Sherawat" TITLE="Mallika Sherawat" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Mallika Sherawat To Star Romantic Comedy</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Mallika Sherawat To Star Romantic Comedy" HREF="http://www.bollywoodmovies.us/news/2009/11_23_2009.html">11/23/2009</A>: </font> <br> Bollywood actress <A ALT="" TITLE="Mallika Sherawat" HREF="http://www.bollywoodmovies.us/actress/mallika_sherawat/bollywood_mallika_sherawat.html">Mallika Sherawat</A> is currently in Los Angeles to promote her upcoming film, <A ALT="" TITLE="Hissss (Naagin The Snake Woman) Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/hissss.html">Hissss (Naagin The Snake Woman) (2008)</A> . Mallika was also recently signed for a role in the movie based on the US President <A ALT="" TITLE="Barack Obama" HREF="http://www.bollywoodmovies.us/famous_person/barack_obama/famous_person_barack_obama.html">Barack Obama</A> . The film is a romantic political comedy directed by Doug McHenry. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actress/shazahn_padamsee/bollywood_shazahn_padamsee_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/shazahn_padamsee/pics/shazahn_padamsee_01.jpg" ALT="Shazahn Padamsee" TITLE="Shazahn Padamsee" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/trisha_krishnan/bollywood_trisha_krishnan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/trisha_krishnan/pics/trisha_krishnan_01.jpg" ALT="Trisha Krishnan" TITLE="Trisha Krishnan" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing November 27, 2009" HREF="http://www.bollywoodmovies.us/news/2009/11_23_2009.html">Movie Releasing November 27, 2009</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for De Dhana Dhan" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/de_dhana_dhan.html">De Dhana Dhan (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar_photo_gallery_01.html">Akshay Kumar </A> , <A ALT="" TITLE="Actress Katrina Kaif" HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif_photo_gallery_01.html">Katrina Kaif </A> </font> , Suneil Shetty and Paresh Rawal, Neha Dhupia, Sameera Reddy </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
