s|TAG_META_TITLE|Radio, Paa, Actor Abhishek Bachchan, Actress Vidya Balan, Amitabh Bachchan|g
s|TAG_META_KEYWORDS|Aishwarya Rai And Sir Ben Kingsley In Film Taj, Radio, Paa, Actor Abhishek Bachchan, Actress Vidya Balan, Amitabh Bachchan|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_16.jpg" ALT="Aishwarya Rai" TITLE="Aishwarya Rai" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Aishwarya Rai And Sir Ben Kingsley In Film Taj</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Aishwarya Rai And Sir Ben Kingsley In Film Taj" HREF="http://www.bollywoodmovies.us/news/2009/11_30_2009.html">12/03/2009</A>: </font> <br> British actor Sir <A ALT="" TITLE="Ben Kingsley" HREF="http://www.bollywoodmovies.us/actor/ben_kingsley/bollywood_ben_kingsley.html">Ben Kingsley</A> well known for his Oscar winning portrayal of Indian independence hero Mohandas Gandhi, has signed former Miss World and Bollywood actress <A ALT="" TITLE="Aishwarya Rai" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai</A> to star opposite him in a movie Taj Mahal. Aishwarya will play the role of Queen Mumtaz and Ben Kingsley will play the role of her husband Mughal Emperor Shah Jahan in the movie titled, <A ALT="" TITLE="Taj Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/taj.html">Taj (2010)</A> . Kingsley’s wife, Brazilian actress Daniela Lavender will play the role of Persian Princess Kandahari Begum, Shah Jahan’s first wife. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/models/katie_price/models_katie_price_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/katie_price/pics/katie_price_01.jpg" ALT="Katie Price" TITLE="Katie Price" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/neeru_bajwa/models_neeru_bajwa_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/neeru_bajwa/pics/neeru_bajwa_01.jpg" ALT="Neeru Bajwa" TITLE="Neeru Bajwa" WIDTH="100" HEIGHT="100" BORDER="0"> </A>..<A HREF="http://www.bollywoodmovies.us/actress/prachi_desai/bollywood_prachi_desai_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/prachi_desai/pics/prachi_desai_04.jpg" ALT="Prachi Desai" TITLE="Prachi Desai" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/elisabetta_canalis/models_elisabetta_canalis_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/elisabetta_canalis/pics/elisabetta_canalis_01.jpg" ALT="Elisabetta Canalis" TITLE="Elisabetta Canalis" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing December 03, 2009" HREF="http://www.bollywoodmovies.us/news/2009/11_30_2009.html">Movie Releasing December 03, 2009</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Radio <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Paa" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/paa.html">Paa (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan_photo_gallery_01.html">Abhishek Bachchan </A> , <A ALT="" TITLE="Actress Vidya Balan" HREF="http://www.bollywoodmovies.us/actress/vidya_balan/bollywood_vidya_balan_photo_gallery_01.html">Vidya Balan </A> </font> , Amitabh Bachchan, Paresh Rawal, <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
