s|TAG_META_TITLE|Monica Dogra, Hrithik Roshan, AR Rahman Get Golden Globe Nominations, 127 days, Slumdog Millionaire, Aruna Shields, Maxim|g
s|TAG_META_KEYWORDS|Monica Dogra, Hrithik Roshan, AR Rahman Get Golden Globe Nominations, 127 days, Slumdog Millionaire, Aruna Shields, Maxim India|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aruna_shields/bollywood_aruna_shields_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aruna_shields/pics/aruna_shields_05.jpg" ALT="Aruna Shields Maxim India December 2010" TITLE="Aruna Shields Maxim India December 2010" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Aruna Shields On Cover Of Maxim India December 2010 Issue</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Aruna Shields On Cover Of Maxim India December 2010 Issue" HREF="http://www.bollywoodmovies.us/news/2010/12_13_2010.html">12/18/2010</A>: </font> <br> <A ALT="" TITLE="Aruna Shields" HREF="http://www.bollywoodmovies.us/actress/aruna_shields/bollywood_aruna_shields.html">Aruna Shields</A> is being featured on the cover of December 2010 edition of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . The photos will be part of the Maxim India December 2010 edition. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/music_director/ar_rahman/bollywood_ar_rahman_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/music_director/ar_rahman/pics/ar_rahman_01.jpg" ALT="AR Rahman" TITLE="AR Rahman" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>AR Rahman Get Golden Globe Nominations</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="AR Rahman Get Golden Globe Nominations" HREF="http://www.bollywoodmovies.us/news/2010/12_13_2010.html">12/15/2010</A>: </font> <br> Oscar winning Indian composer <A ALT="" TITLE="AR Rahman" HREF="http://www.bollywoodmovies.us/music_director/ar_rahman/bollywood_ar_rahman.html">AR Rahman</A> get Golden Globe nomination for Danny Boyle's 127 Hours. AR Rahman won two Oscars and a Golden Globe for his number 'Jai ho' for the movie <A ALT="" TITLE="Slumdog Millionaire Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/slumdog_millionaire.html">Slumdog Millionaire (2008)</A> . AR will be competing for Original Score for a motion picture category against Alexandre Desplat ('The King's Speech'), Trent Reznor and Atticus Ross ('The Social Network'), Danny Elfman ('Alice in Wonderland'), and Hans Zimmer ('Inception'). The soundtrack for the movie contains a popular song 'If I Rise' in which AR collaborated with pop star Dido. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center" colspan=2> <A ALT="" TITLE="Saina Nehwal Enters The Final" HREF="http://www.bollywoodmovies.us/news/2010/12_13_2010.html">12/13/2010</A>: <br> Saina Nehwal beat Juliane Schenk of Germany to enter the finals at the Hong Kong Super Series. Saina was down early but over came it to win 21-19 17-21 21-9. Saina will now play Asian Games champion Wang Shixian of China. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/hrithik_roshan/pics/hrithik_roshan_05.jpg" ALT="Hrithik Roshan" TITLE="Hrithik Roshan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/monica_dogra/bollywood_monica_dogra_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/monica_dogra/pics/monica_dogra_01.jpg" ALT="Monica Dogra" TITLE="Monica Dogra" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing December 17, 2010" HREF="http://www.bollywoodmovies.us/news/2010/12_13_2010.html">Movie Releasing December 17, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> 332 Mumbai To India <hr size="1" width="100%"> Kaalo <hr size="1" width="100%"> Mirch <hr size="1" width="100%"> Payback <hr size="1" width="100%"> Tera Kya Hoga Johny <hr size="1" width="100%"> Tron: Legacy <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
