s|TAG_META_TITLE|3 Idiots, Aamir Khan, Kareena Kapoor|g
s|TAG_META_KEYWORDS|3 Idiots, Aamir Khan, Kareena Kapoor|g
#
s|TAG_NEWS_WITH_IMAGE||g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing December 25, 2009" HREF="http://www.bollywoodmovies.us/news/2009/12_21_2009.html">Movie Releasing December 25, 2009</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for 3 Idiots" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/3_idiots.html">3 Idiots (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Aamir Khan" HREF="http://www.bollywoodmovies.us/actor/aamir_khan/bollywood_aamir_khan_photo_gallery_01.html">Aamir Khan </A> , <A ALT="" TITLE="Actress Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor_photo_gallery_01.html">Kareena Kapoor </A> </font> , Madhavan, Sharman Joshi, Boman Irani </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK|<!-- TABLE_SEPARATOR_START --> <TABLE WIDTH=100% ALIGN="center" cellspacing="0" border="1" bordercolor="blue"> <TR> <TD> <center><b><font color="#0033cc" size="4">Top 10 Songs Of The Week (12/05/2009)</font></b></center> <hr size="2" width="100%"s color="#0000FF"> <b>10.</b> Radio <hr size="2" width="100%"> <b>09.</b> <A ALT="" TITLE="London Dreams Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/london_dreams.html">London Dreams (2009)</A> <hr size="2" width="100%"> <b>08.</b> <A ALT="" TITLE="Wake up Sid Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/wake_up_sid.html">Wake up Sid (2009)</A> <hr size="2" width="100%"> <b>07.</b> <A ALT="" TITLE="Tum Mile Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/tum_mile.html">Tum Mile (2009)</A> <hr size="2" width="100%"> <b>06.</b> <A ALT="" TITLE="Rocket Singh Salesman Of The Year Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/rocket_singh_salesman_of_the_year.html">Rocket Singh Salesman Of The Year (2009)</A> <hr size="2" width="100%"> <b>05.</b> <A ALT="" TITLE="Paa Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/paa.html">Paa (2009)</A> <hr size="2" width="100%"> <b>04.</b> <A ALT="" TITLE="Kurbaan Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/kurbaan.html">Kurbaan (2009)</A> <hr size="2" width="100%"> <b>03.</b> <A ALT="" TITLE="3 Idiots Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/3_idiots.html">3 Idiots (2009)</A> <hr size="2" width="100%"> <b>02.</b> <A ALT="" TITLE="De Dhana Dhan Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/de_dhana_dhan.html">De Dhana Dhan (2009)</A> <hr size="2" width="100%"> <b>01.</b> <A ALT="" TITLE="Ajab Prem Ki Ghazab Kahani (APKGK) Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/ajab_prem_ki_ghazab_kahani.html">Ajab Prem Ki Ghazab Kahani (APKGK) (2009)</A> <hr size="2" width="100%"> </TD> </TR> </TABLE> <!-- TABLE_SEPARATOR_END -->|g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
