s|TAG_META_TITLE|Accident on Hill Road, Actress Celina Jaitley, Monikangana Dutta, Guzaarish, Hrithik Roshan, Android Based Tablet PC, Notion Ink|g
s|TAG_META_KEYWORDS|Accident on Hill Road, Actress Celina Jaitley, Monikangana Dutta, Guzaarish, Hrithik Roshan, Android Based Tablet PC, Notion Ink, Vindoo Dara Singh Bigg Boss Season 3|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/monikangana_dutta/bollywood_monikangana_dutta_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/monikangana_dutta/pics/monikangana_dutta_01.jpg" ALT="Monikangana Dutta" TITLE="Monikangana Dutta" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Hrithik Roshan And Monikangana Dutta In Guzaarish</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Hrithik Roshan And Monikangana Dutta In Guzaarish" HREF="http://www.bollywoodmovies.us/news/2009/12_28_2009.html">12/28/2009</A>: </font> <br> <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> is currently shotting with <A ALT="" TITLE="Monikangana Dutta" HREF="http://www.bollywoodmovies.us/actress/monikangana_dutta/bollywood_monikangana_dutta.html">Monikangana Dutta</A> in <A ALT="" TITLE="Sanjay Leela Bhansali" HREF="http://www.bollywoodmovies.us/director/sanjay_leela_bhansali/bollywood_sanjay_leela_bhansali.html">Sanjay Leela Bhansali</A> 's upcoming movie <A ALT="" TITLE="Guzaarish Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/guzaarish.html">Guzaarish (2010)</A> in Goa. Hrithik plays the husband of Monikangana in the movie which is a very intense love story, and hence Sanjay wants to shot lovemaking scene between which has made Hrithik's wife <A ALT="" TITLE="Suzanne Roshan" HREF="http://www.bollywoodmovies.us/actress/suzanne_roshan/bollywood_suzanne_roshan.html">Suzanne Roshan</A> very nervous. The model is making her Bollywood film debut in this film. Hrithik playing a paraplegic bound on a wheelchair who falls for his nurse played by <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A>. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE|<!-- TV_SHOWS_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Vindoo Dara Singh Bigg Boss Season 3" HREF="http://www.bollywoodmovies.us/news/2009/12_28_2009.html">12/29/2009</A> <br> Vindoo Dara Singh was the last man standing in Bigg Boss Season 3. He won Rs1 crore and a car. Per Vindoo it was Akshay Kumar that made him go into the house and now that has changed his life. <hr size="1" width="100%"> </td> </tr> <!-- TV_SHOWS_END -->|g
#
s|TAG_NEWS_WORLD|<!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="First Android Based Tablet PC For India" HREF="http://www.bollywoodmovies.us/news/2009/12_28_2009.html">12/28/2009</A>: <br> A small startup called Notion Ink, a Hyderabad-based technology company, has developed the first touchscreen tablet using the Google’s open source operating system Android. The touchscreen tablet uses Nvidia’s yet-to-be launched Tegra processor chips and a power saving display screen from the US based developer Pixel Qi, which will be showcased at the Las Vegas Consumer Electronics Show in January 2010. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END -->|g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing December 31, 2009" HREF="http://www.bollywoodmovies.us/news/2009/12_28_2009.html">Movie Releasing December 31, 2009</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Accident on Hill Road" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/accident_on_hill_road.html">Accident on Hill Road (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Farooq Sheikh" HREF="http://www.bollywoodmovies.us/actor/farooq_sheikh/bollywood_farooq_sheikh_photo_gallery_01.html">Farooq Sheikh </A> , <A ALT="" TITLE="Actress Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley_photo_gallery_01.html">Celina Jaitley </A> </font> , Abhimanyu Shekhar Singh, </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Raat Gayi Baat Gayi" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/raat_gayi_baat_gayi.html">Raat Gayi Baat Gayi (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Rajat Kapoor" HREF="http://www.bollywoodmovies.us/actor/rajat_kapoor/bollywood_rajat_kapoor_photo_gallery_01.html">Rajat Kapoor </A> , <A ALT="" TITLE="Actress Neha Dhupia" HREF="http://www.bollywoodmovies.us/actress/neha_dhupia/bollywood_neha_dhupia_photo_gallery_01.html">Neha Dhupia </A> </font> , Vinay Pathak, Iravati Harshe, </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
