s|TAG_TITLE_NAME|K K|g
s|TAG_KEYWORD_ACTRESS_NAME|k k|g
s|TAG_DESC_ACTRESS_NAME|k k|g
s|TAG_ALT_ACTRESS_NAME|K K|g
s|TAG_DIR_NAME_1|singer|g
s|TAG_DIR_ACTRESS_NAME|k_k|g
s|TAG_ACTRESS_LONG_DESC|K K...add description|g
