s|TAG_META_TITLE|Adriana Lima|g
s|TAG_META_KEYWORDS|adriana lima, pregnant, Maxim Hot 100 List, |g
s|TAG_META_DESCRIPTION|adriana lima, pregnant, Maxim Hot 100 List|g
#
s|TAG_BIOGRAPHY_1|<b>Adriana Francesca Lima </b> was born in Salvador, Bahia, Brazil on 12 June 1981.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Adriana is a Brazilian supermodel and has appeared in Victoria's Secret catalog. <BR> In 2008 she was ranked num 10 on the AskMen.com Top 99 Women list.|g
#
s|TAG_BIO_2008_LATEST_NEWS|<b>Karolina Kurkova Voted Sexiest Woman In The World</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Karolina Kurkova Voted Sexiest Woman In The World" HREF="http://www.bollywoodmovies.us/news/2008/11_17_2008.html">11/22/2008</A>: </font> <br> <A ALT="" TITLE="Karolina Kurkova" HREF="http://www.bollywoodmovies.us/models/karolina_kurkova/models_karolina_kurkova.html">Karolina Kurkova</A> was named as the sexiest woman in the wold by E! entertainment television. the Czech born beauty beat out other Victoria Secret models like <A ALT="" TITLE="Giselle Bundchen" HREF="http://www.bollywoodmovies.us/models/gisele_bundchen/models_gisele_bundchen.html">Giselle Bundchen</A> , <A ALT="" TITLE="Adriana Lima" HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima.html">Adriana Lima</A> and <A ALT="" TITLE="Heidi Klum" HREF="http://www.bollywoodmovies.us/models/heidi_klum/models_heidi_klum.html">Heidi Klum</A> . Karolina Kurkova will also play the role of Cover Girl in Paramount's upcoming movie "G.I. Joe." According to her rep, Karolina does not have a have a belly button because of an abdominal operation as an infant.<br><hr size="1" width="100%"> <b>Gisele Bundchen Worlds Top Supermodel</b> <br> Date: <A ALT="" TITLE="Gisele Bundchen Worlds Top Supermodel" HREF="http://www.bollywoodmovies.us/news/2008/04_28_2008.html">05/02/2008</A> <br> <A ALT="" TITLE="Gisele Bundchen" HREF="http://www.bollywoodmovies.us/models/gisele_bundchen/models_gisele_bundchen.html">Gisele Bundchen</A> , a Brazilian model, earned an estimated $35 million during the past year which put her a top the list of high earning models. <A ALT="" TITLE="Heidi Klum" HREF="http://www.bollywoodmovies.us/models/heidi_klum/models_heidi_klum.html">Heidi Klum</A> , came in 2nd with $14 million, <A ALT="" TITLE="Kate Moss" HREF="http://www.bollywoodmovies.us/models/kate_moss/models_kate_moss.html">Kate Moss</A> with $7.5 million, <A ALT="" TITLE="Adriana Lima" HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima.html">Adriana Lima</A> with $7 million and Doutzen Kroes with $6 million. Gisele last year finished her contract with Victoria's Secret but still has many other modeling jobs that she is juggling. Some of her contract include work for Pantene, Disney, Nivea, Vogue eyewear and Aquascutum. She also has a line of Grendene sandals, Ipanema by Gisele. She also has made news due to her romance with New England Patriots quarterback <A ALT="" TITLE="Tom Brady" HREF="http://www.bollywoodmovies.us/sports/football/tom_brady/football_tom_brady.html">Tom Brady</A>.|g
#
#
#
s|TAG_BIO_LATEST_NEWS|<b>Supermodel Adriana Lima is pregnant!</b> <br> Date: <A ALT="" TITLE="Supermodel Adriana Lima is pregnant!" HREF="http://www.bollywoodmovies.us/news/2009/05_25_2009.html">05/31/2009</A>: <br> The Victoria's Secret supermodel <A ALT="" TITLE="Adriana Lima" HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima.html">Adriana Lima</A> is expecting her first child with new husband, NBA player Marko Jaric, her reps confirms to Usmagazine.com. The Brazilian supermodel's baby is due in winter 2009. The wedding was held in Jackson Hole, Wyoming in a private civil ceremony on Valentine's Day.<br><hr size="1" width="100%"><b>House's Olivia Wilde Tops Maxim Hot 100 List</b> <br> Date: <A ALT="" TITLE="House's Olivia Wilde Tops Maxim Hot 100 List" HREF="http://www.bollywoodmovies.us/news/2009/05_11_2009.html">05/13/2009</A>: <br> Fox's hit medical drama House's <A ALT="" TITLE="Olivia Wilde" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/olivia_wilde/celebrites_olivia_wilde.html">Olivia Wilde</A> topped the list of the Maxim 2009 Hot 100 unveiled today. For the first time, the First Lady of the United States made the list. First lady, <A ALT="" TITLE="Michelle Obama" HREF="http://www.bollywoodmovies.us/famous_person/michelle_obama/famous_person_michelle_obama.html">Michelle Obama</A> showed on the list at number 93. The top 10 on the list are: <A ALT="" TITLE="Megan Fox" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/megan_fox/celebrites_megan_fox.html">Megan Fox</A> , <A ALT="" TITLE="Bar Refaeli" HREF="http://www.bollywoodmovies.us/models/bar_refaeli/models_bar_refaeli.html">Bar Refaeli</A> , <A ALT="" TITLE="Malin Akerman" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/malin_akerman/celebrites_malin_akerman.html">Malin Akerman</A> , <A ALT="" TITLE="Mila Kunis" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/mila_kunis/celebrites_mila_kunis.html">Mila Kunis</A> , <A ALT="" TITLE="Eliza Dushku" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/eliza_dushku/celebrites_eliza_dushku.html">Eliza Dushku</A> , <A ALT="" TITLE="Adriana Lima" HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima.html">Adriana Lima</A> , <A ALT="" TITLE="Rihanna" HREF="http://www.bollywoodmovies.us/hollywood/artists/rihanna/hollywood_rihanna.html">Rihanna</A> , <A ALT="" TITLE="Jordana Brewster" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/jordana_brewster/celebrites_jordana_brewster.html">Jordana Brewster</A> , <A ALT="" TITLE="Jennifer Love Hewitt" HREF="http://www.bollywoodmovies.us/hollywood/actress/jennifer_love_hewitt/hollywood_jennifer_love_hewitt.html">Jennifer Love Hewitt</A> .|g

