s|TAG_META_TITLE|Gisele Bundchen|g
s|TAG_META_KEYWORDS|gisele bundchen, |g
s|TAG_META_DESCRIPTION|gisele bundchen|g
#
s|TAG_BIOGRAPHY_1|<b>Gisele Bundchen</b> was born in Horizontina Rio Grande do Sul Brazil on July 20, 1980.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Gisele is a Brazilian supermodel. <BR> In 2008 Gisele was ranked num 16 on the AskMen.com Top 99 Women list. <BR> In 2006 she was ranked num 14 on the AskMen.com Top 99 Women list.|g
#
s|TAG_BIO_LATEST_NEWS|<b>Karolina Kurkova Voted Sexiest Woman In The World</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Karolina Kurkova Voted Sexiest Woman In The World" HREF="http://www.bollywoodmovies.us/news/2008/11_17_2008.html">11/22/2008</A>: </font> <br> <A ALT="" TITLE="Karolina Kurkova" HREF="http://www.bollywoodmovies.us/models/karolina_kurkova/models_karolina_kurkova.html">Karolina Kurkova</A> was named as the sexiest woman in the wold by E! entertainment television. the Czech born beauty beat out other Victoria Secret models like <A ALT="" TITLE="Giselle Bundchen" HREF="http://www.bollywoodmovies.us/models/gisele_bundchen/models_gisele_bundchen.html">Giselle Bundchen</A> , <A ALT="" TITLE="Adriana Lima" HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima.html">Adriana Lima</A> and <A ALT="" TITLE="Heidi Klum" HREF="http://www.bollywoodmovies.us/models/heidi_klum/models_heidi_klum.html">Heidi Klum</A> . Karolina Kurkova will also play the role of Cover Girl in Paramount's upcoming movie "G.I. Joe." According to her rep, Karolina does not have a have a belly button because of an abdominal operation as an infant.<br><hr size="1" width="100%"><b>Gisele Bundchen Worlds Top Supermodel</b> <br> Date: <A ALT="" TITLE="Gisele Bundchen Worlds Top Supermodel" HREF="http://www.bollywoodmovies.us/news/2008/04_28_2008.html">05/02/2008</A> <br> <A ALT="" TITLE="Gisele Bundchen" HREF="http://www.bollywoodmovies.us/models/gisele_bundchen/models_gisele_bundchen.html">Gisele Bundchen</A> , a Brazilian model, earned an estimated $35 million during the past year which put her a top the list of high earning models. <A ALT="" TITLE="Heidi Klum" HREF="http://www.bollywoodmovies.us/models/heidi_klum/models_heidi_klum.html">Heidi Klum</A> , came in 2nd with $14 million, <A ALT="" TITLE="Kate Moss" HREF="http://www.bollywoodmovies.us/models/kate_moss/models_kate_moss.html">Kate Moss</A> with $7.5 million, <A ALT="" TITLE="Adriana Lima" HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima.html">Adriana Lima</A> with $7 million and Doutzen Kroes with $6 million. Gisele last year finished her contract with Victoria's Secret but still has many other modeling jobs that she is juggling. Some of her contract include work for Pantene, Disney, Nivea, Vogue eyewear and Aquascutum. She also has a line of Grendene sandals, Ipanema by Gisele. She also has made news due to her romance with New England Patriots quarterback <A ALT="" TITLE="Tom Brady" HREF="http://www.bollywoodmovies.us/sports/football/tom_brady/football_tom_brady.html">Tom Brady</A>.|g


