s|TAG_META_TITLE|United Arab Emirates Dubai, The Burj Al Arab, Sheikh Zayed Road|g
s|TAG_META_KEYWORDS|United Arab Emirates Dubai, The Burj Al Arab, Sheikh Zayed Road|g
s|TAG_META_DESCRIPTION|Provide information and resources for finding the right information on United Arab Emirates Dubai.|g
#
s|TAG_INFO_CATEGORY|united_arab_emirates|g
#
s|TAG_TITLE_NAME|Information and Resouces For United Arab Emirates Dubai|g
#
s|TAG_MAIN_INFO_1|Places To See: Sheikh Zayed Road, Etisalat Tower 2, The Burj Al Arab is the world's tallest hotel.<BR>The Dubai Marina, a residential district, is the world's largest man-made marina.|g
#
# Put <table>  </table>
s|TAG_LATEST_NEWS_2008|<table> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/shahrukh_khan/pics/shahrukh_khan_01.jpg" ALT="Shahrukh Khan (SRK)" TITLE="Shahrukh Khan (SRK)" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Shahrukh Khan Boulevard in Dubai</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Shahrukh Khan Boulevard in Dubai" HREF="http://www.bollywoodmovies.us/news/2008/10_06_2008.html">10/09/2008</A>: </font> <br> Over the weekend, <A ALT="" TITLE="Shahrukh Khan (SRK)" HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan.html">Shahrukh Khan (SRK)</A> announced that he has teamed up with a United Arab Emirates (UAE) real estate firm to build a signature beachfront residential project in the gulf country with a budget of 2.17 billion dollars (USD). The project will be located on the Dana Island in Ras Al Khaimah. Shahrukh will work with a Los Angeles based architect Tony Ashai during the design of the beachfront community comprising 10 residential towers along with specially designed studios, and one and two bedroom apartments and townhouses, piers and boardwalks besides marine sports and leisure facilities. The project is scheduled to complete in 2012. </TD> </TR> <!-- STORY_END -->  <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_20.jpg" ALT="Aishwarya Rai Bachchan" TITLE="Aishwarya Rai Bachchan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Abhishek And Aishwarya Bachchan Buy House In Dubai</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Abhishek And Aishwarya Bachchan Buy House In Dubai" HREF="http://www.bollywoodmovies.us/news/2008/06_02_2008.html">06/02/2008</A>: </font> <br> Bollywood couple <A ALT="" TITLE="Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html">Abhishek Bachchan</A> and <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> have purchased a home in <A ALT="" TITLE="United Arab Emirates Dubai" HREF="http://www.bollywoodmovies.us/Regional/United_Arab_Emirates/Dubai/united_arab_emirates_dubai.html">Dubai</A> , UAE. The couple have purchased villa in the double gated community called Sanctuary Falls and recently also attented a resident party held at the Jumeirah Golf Estates. </TD> </TR> <!-- STORY_END --> </table>|g