s|TAG_META_TITLE|Anne Hathaway|g
s|TAG_META_KEYWORDS|anne hathaway, celebrites, hollywood, AskMen.com|g
s|TAG_META_DESCRIPTION|Anne Hathaway is an American actress. |g
#
s|TAG_BIOGRAPHY_1|<b>Anne Hathaway</b> was born on November 12, 1982 in Brooklyn, New York, U.S.A.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Anne Hathaway is an American actress. She made her TV debut in TV series Get Reel and then in a Disney movie The Princess Diaries in 2001.<BR>In 2011 she was ranked num 09 on the AskMen.com Top 99 Women list.|g
# -----------------------------
s|TAG_BIO_LATEST_NEWS|<b>AskMen List Of 2009 World’s Top 99 Most Desirable Women</b> <br> Date: <A ALT="" TITLE="AskMen List Of 2009 World’s Top 99 Most Desirable Women" HREF="http://www.bollywoodmovies.us/news/2009/01_19_2009.html">01/25/2009</A>: <br> AskMen.com announced there list of world’s top 99 most desirable women and it included some of Indian film industry. The list contains celebriteis from all over the world and they are voted for my the readers of AskMen.com. This year list has many new faces and many that have been on the list in the previous years. Britney Spears made a reappearance on the list at position 90. While Grey's Anatomy <A ALT="" TITLE="Katherine Heigl" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/katherine_heigl/celebrites_katherine_heigl.html">Katherine Heigl</A> dropped from number one in 2008 to number 81 for 2009, while <A ALT="" TITLE="Anne Hathaway" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/anne_hathaway/celebrites_anne_hathaway.html">Anne Hathaway</A> jumped 58 to no. 5. <A ALT="" TITLE="Eva Mendes" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/eva_mendes/celebrites_eva_mendes.html">Eva Mendes</A> won the honors of being number 01, with <A ALT="" TITLE="Megan Fox" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/megan_fox/celebrites_megan_fox.html">Megan Fox</A> taking the second stop folloed by <A ALT="" TITLE="Marisa Miller" HREF="http://www.bollywoodmovies.us/models/marisa_miller/models_marisa_miller.html">Marisa Miller</A> in third. From Bollywood it was first timer <A ALT="" TITLE="Katrina Kaif" HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif.html">Katrina Kaif</A> at number 48 while <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> ended up at 60th place in 2009, but was no. 27 in 2008. <BR> View the complete list at <A TARGET="_blank" ALT="" TITLE="AskMen.com Top 99 Women 2009" HREF="http://www.askmen.com/specials/top_99_women/">AskMen.com</A>|g
# -----------------------------
