s|TAG_META_TITLE|Dhobi Ghat (2011), Aamir Khan, Monica Dogra, Shruti Haasaen|g
s|TAG_META_KEYWORDS|Dhobi Ghat (2011), Aamir Khan, Monica Dogra, Shruti Haasaen|g
#
s|TAG_NEWS_WITH_IMAGE||g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/kim_clijsters/tennis_kim_clijsters_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/kim_clijsters/pics/kim_clijsters_01.jpg" ALT="Kim Clijsters" TITLE="Kim Clijsters" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Kim Clijsters Moves Onto Third Round With Victory Over Carla Suarez Navarro</b> <br> <A ALT="" TITLE="Kim Clijsters Moves Onto Third Round With Victory Over Carla Suárez Navarro" HREF="http://www.bollywoodmovies.us/news/2011/01_17_2011.html">01/20/2011</A>: <br> The No 3 seed from Belgium <A ALT="" TITLE="Kim Clijsters" HREF="http://www.bollywoodmovies.us/sports/tennis/kim_clijsters/tennis_kim_clijsters.html">Kim Clijsters</A> moves onto the third round at the Australian Open 2011 with victory over Carla Suarez Navarro. Kim won the match with score of 6-1, 6-3. Kim beat out Dinara Safina 6-0, 6-0 in the first round. </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/aamir_khan/bollywood_aamir_khan_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/aamir_khan/pics/aamir_khan_13.jpg" ALT="Aamir Khan" TITLE="Aamir Khan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/shruti_haasan/bollywood_shruti_haasan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/shruti_haasan/pics/shruti_haasan_09.jpg" ALT="Shruti Haasaen" TITLE="Shruti Haasaen" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing January 21, 2010" HREF="http://www.bollywoodmovies.us/news/2011/01_17_2011.html">Movie Releasing January 21, 2011</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Season Of The Witch <hr size="1" width="100%"> Hostel <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Dhobi Ghat" HREF="http://www.bollywoodmovies.us/movie_reviews/2011/dhobi_ghat.html">Dhobi Ghat (2011) </A> <br> Cast: <A ALT="" TITLE="Actor Aamir Khan" HREF="http://www.bollywoodmovies.us/actor/aamir_khan/bollywood_aamir_khan_photo_gallery_01.html">Aamir Khan </A> , <A ALT="" TITLE="Actress Monica Dogra" HREF="http://www.bollywoodmovies.us/actress/monica_dogra/bollywood_monica_dogra_photo_gallery_01.html">Monica Dogra </A> </font> , Prateik Babbar, Danish Hussain, Jehan Manekshaw, Ashok Varma, Kriti Malhotra, Kitu Gidwani </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK|<!-- TABLE_SEPARATOR_START --> <TABLE WIDTH=100% ALIGN="center" cellspacing="0" border="1" bordercolor="blue"> <TR> <TD> <center><b><font color="#0033cc" size="4">Top 10 Songs Of The Week (01/15/2011)</font></b></center> <hr size="2" width="100%"s color="#0000FF"> <b>10.</b> Angle <hr size="2" width="100%"> <b>09.</b> <A ALT="" TITLE="Yeh Saali Zindagi Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2011/yeh_saali_zindagi.html">Yeh Saali Zindagi (2011)</A> <hr size="2" width="100%"> <b>08.</b> Turning 30 <hr size="2" width="100%"> <b>07.</b> <A ALT="" TITLE="Saat Khoon Maaf Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/saat_khoon_maaf.html">Saat Khoon Maaf (2011)</A> <hr size="2" width="100%"> <b>06.</b> <A ALT="" TITLE="Dil To Bachcha Hai Ji Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/dil_to_bachcha_hai_ji.html">Dil To Bachcha Hai Ji (2011)</A> <hr size="2" width="100%"> <b>05.</b> Band Baaja Baaraat <hr size="2" width="100%"> <b>04.</b> <A ALT="" TITLE="Tees Maar Khan Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/tees_maar_khan.html">Tees Maar Khan (2010)</A> <hr size="2" width="100%"> <b>03.</b> <A ALT="" TITLE="Patiala House Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/patiala_house.html">Patiala House (2011)</A> <hr size="2" width="100%"> <b>02.</b> <A ALT="" TITLE="No One Killed Jessica Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2011/no_one_killed_jessica.html">No One Killed Jessica (2011)</A> <hr size="2" width="100%"> <b>01.</b> Yamla Pagla Deewana <hr size="2" width="100%"> </TD> </TR> </TABLE> <!-- TABLE_SEPARATOR_END -->|g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
