s|TAG_META_TITLE|Shahrukh Khan, My Name Is Khan (MNIK), Kajol|g
s|TAG_META_KEYWORDS|Shahrukh Khan, My Name Is Khan (MNIK), Kajol|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/shahrukh_khan/pics/shahrukh_khan_10.jpg" ALT="Shahrukh Khan" TITLE="Shahrukh Khan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Shahrukh Khan In Exchange Of Words With Shiv Sena</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Shahrukh Khan In Exchange Of Words With Shiv Sena" HREF="http://www.bollywoodmovies.us/news/2010/02_01_2010.html">02/06/2010</A>: </font> <br> Just before release of his movie, <A ALT="" TITLE="My Name Is Khan (MNIK) Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/my_name_is_khan.html">My Name Is Khan (MNIK) (2010)</A> on 12 February 2010 <A ALT="" TITLE="Shahrukh Khan" HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan.html">Shahrukh Khan</A> has be embroiled in a exchange of words with Shiv Sena for favouring Pakistani players in the Indian Premier League (IPL) and supporting them. On Saturday SRK said that he didn't owe an apology to the party but was not seeking a "confrontation" either. In an interview to a TV channel, SRK said," I have not said anything that is anti-national." Some of the posters of his movie have been burned and taken down, and now the release of this movie in <A ALT="" TITLE="Maharashtra Mumbai" HREF="http://www.bollywoodmovies.us/Regional/India/Maharashtra/Mumbai/Mumbai.html">Mumbai</A> could be in jeapordy.<BR>Now the questions all Indian must ask is that is this fare that a person in a Decormatic conutry cannot speak his mind without being afriad of remification of this words from a political party from within the country itself? Do we really want such fear withour own people or do we want to leave as one? <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actress/lakshmi_menon/bollywood_lakshmi_menon_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/lakshmi_menon/pics/lakshmi_menon_02.jpg" ALT="Lakshmi Menon" TITLE="Lakshmi Menon" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/jayde_nicole/models_jayde_nicole_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/jayde_nicole/pics/jayde_nicole_03.jpg" ALT="Jayde Nicole" TITLE="Jayde Nicole" WIDTH="100" HEIGHT="100" BORDER="0"> </A>..<A HREF="http://www.bollywoodmovies.us/models/georgia_jones/models_georgia_jones_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/georgia_jones/pics/georgia_jones_01.jpg" ALT="Georgia Jones" TITLE="Georgia Jones" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing Feburary 05, 2010" HREF="http://www.bollywoodmovies.us/news/2010/02_01_2010.html">Movie Releasing Feburary 05, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Striker <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
