s|TAG_META_TITLE|Amitabh Bachchan To Undergo Another Surgery, Nargis Fakhri Maxim India February 2012|g
s|TAG_META_KEYWORDS|Amitabh Bachchan To Undergo Another Surgery, Sania and Anastasia captures Pattaya Open, Nargis Fakhri Maxim India February 2012|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/nargis_fakhri/bollywood_nargis_fakhri_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/nargis_fakhri/pics/nargis_fakhri_15.jpg" ALT="Nargis Fakhri Maxim India February 2012" TITLE="Nargis Fakhri Maxim India February 2012" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Nargis Fakhri On Cover Of Maxim India February 2012 Issue</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Nargis Fakhri On Cover Of Maxim India February 2012 Issue" HREF="http://www.bollywoodmovies.us/news/2012/02_13_2012.html">02/17/2012</A>: </font> <br> <A ALT="" TITLE="Nargis Fakhri" HREF="http://www.bollywoodmovies.us/actress/nargis_fakhri/bollywood_nargis_fakhri.html">Nargis Fakhri</A> is being featured on the cover of February 2012 edition of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . The photos will be part of the Maxim India February 2012 edition. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/amitabh_bachchan/pics/amitabh_bachchan_01.jpg" ALT="Amitabh Bachchan" TITLE="Amitabh Bachchan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Amitabh Bachchan To Undergo Another Surgery</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Amitabh Bachchan To Undergo Another Surgery" HREF="http://www.bollywoodmovies.us/news/2012/02_13_2012.html">02/17/2012</A>: </font> <br> Bollywood veteran actor <A ALT="" TITLE="Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan.html">Amitabh Bachchan</A>, who underwent two operations on Saturday February 11, 2012 to rectify his hernia said on Twitter yesterday that he will have to undergo a second surgery and added that his stay in the hospital will be prolonged. It was also reported that Beti B visited her grandfather in the hospital. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD|<!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="Facebook and Saavn tie up for music" HREF="http://www.bollywoodmovies.us/news/2012/02_13_2012.html">02/17/2012</A>: <br> Saavn the music streaming radio service that provides Bollywood music, Indian music and regional South Asian music has tied up with Facebook to provide music. The integration began in December 2011 which has already brought more than 7,00,000 new Facebook users to Saavn. Saavn license music from over 200 providers, and have more than a million songs licensed. The service is free and makes its money through targeted display and rich media ad units. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END -->|g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/pics/sania_mirza_03.jpg" ALT="Sania Mirza" TITLE="Sania Mirza" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sania and Anastasia captures Pattaya Open</b> <br> <A ALT="" TITLE="Sania and Anastasia captures Pattaya Open" HREF="http://www.bollywoodmovies.us/news/2012/02_13_2012.html">02/13/2012</A>: <br> Indian star <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> and her doubles Australian partner Anastasia Rodionova won the women's doubles final of the Pattaya Open tennis championship in Thailand. Sania Mirza of India and Australian Anastasia Rodionova beat H. Chan and Yung-ja Chan of Taipei 3-6, 6-1, 10-8. The top-seeded duo of Sania and Anastasia rallied well from a first-set deficit. This happens to be the 13th WTA title for the Sania Mirza and the first for 2012. Sania is ranked World No 7 in women's double has a chance to compete in the 2012 London Olympics. </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing February 17, 2012" HREF="http://www.bollywoodmovies.us/news/2012/02_13_2012.html">Movie Releasing February 17, 2012</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Say Yes To Love <hr size="1" width="100%"> Tukkaa Fit <hr size="1" width="100%"> Married 2 America <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Ek Deewana Tha" HREF="http://www.bollywoodmovies.us/movie_reviews/2011/ek_deewana_tha.html">Ek Deewana Tha (2011) </A> <br> Cast: <A ALT="" TITLE="Actor Prateik Babbar" HREF="http://www.bollywoodmovies.us/actor/prateik_babbar/bollywood_prateik_babbar_photo_gallery_01.html">Prateik Babbar </A> , <A ALT="" TITLE="Actress Amy Jackson" HREF="http://www.bollywoodmovies.us/actress/amy_jackson/bollywood_amy_jackson_photo_gallery_01.html">Amy Jackson </A> </font> , Manu Rishi, Sachin Khedekar, Samantha Ruth Prabhu </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
