s|TAG_META_TITLE|Sachin Tendulkar, Cricket, Brooklyn Decker, Deepika Padukone, Karthik Calling Karthik, Teen Patti|g
s|TAG_META_KEYWORDS|Sachin Tendulkar, Cricket, Brooklyn Decker, Deepika Padukone, Karthik Calling Karthik, Teen Patti|g
#
s|TAG_NEWS_WITH_IMAGE||g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center" colspan=2> <A ALT="" TITLE="Tendulkar: Little Master, writes history" HREF="http://www.bollywoodmovies.us/news/2010/02_22_2009.html">02/25/2010</A>: <br> <A ALT="" TITLE="Sachin Tendulkar" HREF="http://www.bollywoodmovies.us/sports/cricket/sachin_tendulkar/cricket_sachin_tendulkar.html">Sachin Tendulkar</A> , the little master entered the records books once again becoming the first cricketer to score a double century in a 50 over international OID, in India's victory over South Africa in Gwalior. The previous record was held by Saeed Anwar's 194 against India and Charles Coventry's 194 versus Bangladesh. One Day International cricket, started in 1971 had to wait 4 decades to witness this great achievement. His unforgettable unbeaten 200 came off just 147 balls with 25 fours and three sixes in it in front of the crowd at Captain Roop Singh Stadium. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actress/deepika_padukone/bollywood_deepika_padukone_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/deepika_padukone/pics/deepika_padukone_01.jpg" ALT="Deepika Padukone" TITLE="Deepika Padukone" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/brooklyn_decker/models_brooklyn_decker_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/brooklyn_decker/pics/brooklyn_decker_05.jpg" ALT="Brooklyn Decker" TITLE="Brooklyn Decker" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing Feburary 26, 2010" HREF="http://www.bollywoodmovies.us/news/2010/02_22_2010.html">Movie Releasing Feburary 26, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Prem Kaa Game <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Karthik Calling Karthik" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/karthik_calling_karthik.html">Karthik Calling Karthik (2010) </A> <br> Cast: <A ALT="" TITLE="Actor Farhan Akhtar" HREF="http://www.bollywoodmovies.us/actor/farhan_akhtar/bollywood_farhan_akhtar_photo_gallery_01.html">Farhan Akhtar </A> , <A ALT="" TITLE="Actress Deepika Padukone" HREF="http://www.bollywoodmovies.us/actress/deepika_padukone/bollywood_deepika_padukone_photo_gallery_01.html">Deepika Padukone </A> </font> , Ram Kapoor, Shefali Shah </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Teen Patti" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/teen_patti.html">Teen Patti (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan_photo_gallery_01.html">Amitabh Bachchan </A> , <A ALT="" TITLE="Actress Raima Sen" HREF="http://www.bollywoodmovies.us/actress/raima_sen/bollywood_raima_sen_photo_gallery_01.html">Raima Sen </A> </font> , Richard Gere, R. Madhavan, Ajay Devgan, Siddharth Kher, Druv Ganesh, Vaibhav Talwar, Mahesh Manjrekar, Irrfan Khan, Boman Irani, Jackie Shroff, Danny Denzongpa, Ben Kingsley, , Shraddha Kapoor, Sushmita Sen </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
