s|TAG_META_TITLE|Mattel Barbie Doll, Aishwarya Bachchan, Movie Releasing March 27, 2009, Aa Dekhen Zara, Heaven On Earth, Videsh|g
s|TAG_META_KEYWORDS|Maxim March 2009, Mattel Barbie Doll, Aishwarya Bachchan, Movie Releasing March 27, 2009, Aa Dekhen Zara, Heaven On Earth, Videsh, Neil Mukesh, Bipasha Basu, Preity Zinta, Priyamani Tollywood, Helena Christensen Model, Top 10 Songs Of The Week|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/freida_pinto/bollywood_freida_pinto_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/freida_pinto/pics/freida_pinto_14.jpg" ALT="Freida Pinto Maxim India March 2009" TITLE="Freida Pinto Maxim India March 2009" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Maxim March 2009</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Maxim March 2008" HREF="http://www.bollywoodmovies.us/news/2009/03_23_2009.html">03/29/2009</A>: </font> <br> The following stars graced the cover of <A ALT="" TITLE="Maxim magazine" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim magazine</A> in the month of March 2009: <A ALT="" TITLE="Freida Pinto" HREF="http://www.bollywoodmovies.us/actress/freida_pinto/bollywood_freida_pinto.html">Freida Pinto</A> , Eliza Dushku (USA), Krista Ranillo (Philippines), Willa Ford, Julianna Guill, Laura Ramsey, Danneel Harris, and Kim Ha Yul (Korea). <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_12.jpg" ALT="Aishwarya Rai (Aishwarya Bachchan)" TITLE="Aishwarya Rai (Aishwarya Bachchan)" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Barbie Doll To Be Modelled On Miss World, Aishwarya Rai Bachchan</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Barbie Doll To Be Modelled On Miss World, Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/news/2009/03_23_2009.html">03/25/2009</A>: </font> <br> Mattel Toys (India) and <A ALT="" TITLE="Aishwarya Rai (Aishwarya Bachchan)" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> are in the initial negotiating stages for having a series of Barbie Dolls designed on Aishwarya. If the deal is signed, then it would be the first time a Barbie inspired from an Indian actress would hit the market shelves and put Aishwarya in the league of Hollywood celebrities like Elizabeth Taylor, Diana Ross, Beyonce Knowles and Cher for whom such a Barbie has already be designed. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/models/helena_christensen/models_helena_christensen_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/helena_christensen/pics/helena_christensen_06.jpg" ALT="Helena Christensen" TITLE="Helena Christensen" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/tollywood/actress/priyamani/tollywood_priyamani_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/tollywood/actress/priyamani/pics/priyamani_07.jpg" ALT="Priyamani Tollywood" TITLE="Priyamani Tollywood" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing March 27, 2009: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Aa Dekhen Zara" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/aa_dekhen_zara.html">Aa Dekhen Zara (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Neil Mukesh" HREF="http://www.bollywoodmovies.us/actor/neil_mukesh/bollywood_neil_mukesh_photo_gallery_01.html">Neil Mukesh </A> , <A ALT="" TITLE="Actress Bipasha Basu" HREF="http://www.bollywoodmovies.us/actress/bipasha_basu/bollywood_bipasha_basu_photo_gallery_01.html">Bipasha Basu </A> </font> , Rahul Dev, Sophie Choudry <hr size="2" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Heaven On Earth, Videsh" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/heaven_on_earth.html">Heaven On Earth, Videsh (2008) </A> <br> Cast: <A ALT="" TITLE="Actress Preity Zinta" HREF="http://www.bollywoodmovies.us/actress/preity_zinta/bollywood_preity_zinta_photo_gallery_01.html">Preity Zinta </A> <hr size="2" width="100%"> </font> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Ek The Power Of One </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK|<center><b><font color="#0033cc" size="4">Top 10 Songs Of The Week (03/06/2009)</font></b></center> <hr size="2" width="100%"s color="#0000FF"> <b>10.</b> (<A ALT="" TITLE="Straight Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/straight.html">Straight (2009)</A>) <hr size="2" width="100%"> <b>09.</b> Baawre (<A ALT="" TITLE="Luck by Chance Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/luck_by_chance.html">Luck by Chance (2009)</A>) <hr size="2" width="100%"> <b>08.</b> (Gulaal) <hr size="2" width="100%"> <b>07.</b> (Dhoondte Reh Jaoge) <hr size="2" width="100%"> <b>06.</b> (Jai Veeru) <hr size="2" width="100%"> <b>05.</b> O... Saya (<A ALT="" TITLE="Slumdog Millionaire Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/slumdog_millionaire.html">Slumdog Millionaire (2008)</A>) <hr size="2" width="100%"> <b>04.</b> (Aloo Chaat) <hr size="2" width="100%"> <b>03.</b> Billoo Bhayankar (<A ALT="" TITLE="Billo Barber Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/billo_barber.html">Billo Barber (2009)</A>) <hr size="2" width="100%"> <b>02.</b> Masakali (<A ALT="" TITLE="Delhi 6, Dilli 6 Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/delhi_6.html">Delhi 6, Dilli 6 (2009)</A>) <hr size="2" width="100%"> <b>01.</b> (<A ALT="" TITLE="Aa Dekhen Zara Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/aa_dekhen_zara.html">Aa Dekhen Zara (2009)</A>) <hr size="2" width="100%">|g
