s|TAG_META_TITLE|Salman Khan, Asin Thottumkal, Ready, Sania Mirza|g
s|TAG_META_KEYWORDS|Salman Khan, Asin Thottumkal, Ready, Sania Mirza to marry Pakistani cricketer Shoaib Malik|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/asin_thottumkal/bollywood_asin_thottumkal_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/asin_thottumkal/pics/asin_thottumkal_11.jpg" ALT="Asin Thottumkal" TITLE="Asin Thottumkal" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Asin Thottumkal To Star Opposite Salman Khan</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Asin Thottumkal To Star Opposite Salman Khan" HREF="http://www.bollywoodmovies.us/news/2010/03_29_2010.html">03/31/2010</A>: </font> <br> <A ALT="" TITLE="Asin Thottumkal" HREF="http://www.bollywoodmovies.us/actress/asin_thottumkal/bollywood_asin_thottumkal.html">Asin Thottumkal</A> has been signed opposite <A ALT="" TITLE="Salman Khan" HREF="http://www.bollywoodmovies.us/actor/salman_khan/bollywood_salman_khan.html">Salman Khan</A> to star in a remake of <A ALT="" TITLE="Ready Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/ready.html">Ready (2010)</A> , a Telugu hit. The movie will be directed by Anees Bazmee, who is currently busy in Canada shooting for upcoming movie, <A ALT="" TITLE="Thank You Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/thank_you.html">Thank You (2010)</A> . Requires a person similar to the prepee role Asin played in <A ALT="" TITLE="Ghajini Remake Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/ghajini.html">Ghajini Remake (2007)</A>. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza_photo_gallery_04.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/pics/sania_mirza_30.jpg" ALT="Ana Ivanovic" TITLE="Ana Ivanovic" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Indian tennis star Sania Mirza to marry Pakistani cricketer Shoaib Malik</b> <br> <A ALT="" TITLE="Indian tennis star Sania Mirza to marry Pakistani cricketer Shoaib Malik" HREF="http://www.bollywoodmovies.us/news/2010/03_29_2010.html">03/31/2010</A>: <br> Next month, Indian tennis star <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> will marry Pakistani cricketer Shoaib Malik. The couple plan to settle in Dubai after the marriage. The marriage comes two months after Mirza broke off her engagement to a childhood friend. </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing April 02, 2010" HREF="http://www.bollywoodmovies.us/news/2010/03_29_2010.html">Movie Releasing April 02, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Sadiyaan <hr size="1" width="100%"> The Great Indian Butterfly <hr size="1" width="100%"> Tum Milo Toh Sahi <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Pankh" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/pankh.html">Pankh (2008) </A> <br> Cast: <A ALT="" TITLE="Actor Lillete Dubey" HREF="http://www.bollywoodmovies.us/actor/lillete_dubey/bollywood_lillete_dubey_photo_gallery_01.html">Lillete Dubey </A> , <A ALT="" TITLE="Actress Bipasha Basu" HREF="http://www.bollywoodmovies.us/actress/bipasha_basu/bollywood_bipasha_basu_photo_gallery_01.html">Bipasha Basu </A> </font> , Ronit Roy, Mahesh Manjrekar, Maradona Robello, </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
