s|TAG_META_TITLE|Aishwarya Rai At Bachchan 2012 Dubai World Cup|g
s|TAG_META_KEYWORDS|Aishwarya Rai At Bachchan 2012 Dubai World Cup|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actor/aamir_khan/bollywood_aamir_khan_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/aamir_khan/pics/aamir_khan_13.jpg" ALT="Aamir Khan" TITLE="Aamir Khan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Aamir Khan To Launch Music Record Fo His New TV Show Satyamev Jayate</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Aamir Khan To Launch Music Record Fo His New TV Show Satyamev Jayate" HREF="http://www.bollywoodmovies.us/news/2012/04_02_2012.html">04/08/2012</A>: </font> <br> <A ALT="" TITLE="Aamir Khan" HREF="http://www.bollywoodmovies.us/actor/aamir_khan/bollywood_aamir_khan.html">Aamir Khan</A> will be soon been seen on the small screen, Aamir is launching a new tv show called Satyamev Jayate. The show is scheduled to go on air in June 2012. The promos of the show are interesting where Aamir wants us to watch it with hearts and eyes open. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_02.jpg" ALT="Aishwarya Rai Bachchan" TITLE="Aishwarya Rai Bachchan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Aishwarya Rai At Bachchan 2012 Dubai World Cup</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Dhoom 3 On Schedule Confirms Yash Raj Films" HREF="http://www.bollywoodmovies.us/news/2012/04_02_2012.html">04/03/2012</A>: </font> <br> <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> made an appearance at 2012 Dubai World Cup at Meydan Grandstand on Saturday, March 31, 2012. Aishwarya wore a gorgeous coral red Sabyasachi tubular kalidaar dress. This was Aishwarya first professional appearance post the birth of her baby girl, Aaradhya, on November 15, 2011. She was there as Longines ambassador to present the Most Elegant Lady Award to Carolyn Coe, a ladies watch from the Longines Saint Imier Collection. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/saif_ali_khan/bollywood_saif_ali_khan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/saif_ali_khan/pics/saif_ali_khan_01.jpg" ALT="Saif Ali Khan" TITLE="Saif Ali Khan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/kareena_kapoor/pics/kareena_kapoor_09.jpg" ALT="Kareena Kapoor" TITLE="Kareena Kapoor" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing April 06, 2012" HREF="http://www.bollywoodmovies.us/news/2012/04_02_2012.html">Movie Releasing April 06, 2012</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Housefull 2" HREF="http://www.bollywoodmovies.us/movie_reviews/2011/housefull_2.html">Housefull 2 (2011) </A> <br> Cast: <A ALT="" TITLE="Actor Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar_photo_gallery_01.html">Akshay Kumar </A> , <A ALT="" TITLE="Actress Asin Thottumkal" HREF="http://www.bollywoodmovies.us/actress/asin_thottumkal/bollywood_asin_thottumkal_photo_gallery_01.html">Asin Thottumkal </A> </font> , Amitabh Bachchan, Riteish Deshmukh, John Abraham, Randhir Kapoor, Rishi Kapoor, , Jacqueline Fernandez <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
