s|TAG_META_TITLE|Sonakshi Sinha's Dances To Dance Karle English Mein, Sarah Jane Dias Maxim India April 2011, Sania Mirza, Peng Shuai of China, Elena Vesnina of Russia, Charleston, South Carolina|g
s|TAG_META_KEYWORDS|Sonakshi Sinha's Dances To Dance Karle English Mein, Sarah Jane Dias Maxim India April 2011, Sania Mirza, Peng Shuai of China, Elena Vesnina of Russia, Charleston, South Carolina|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/sonakshi_sinha/bollywood_sonakshi_sinha_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/sonakshi_sinha/pics/sonakshi_sinha_20.jpg" ALT="Sonakshi Sinha" TITLE="Sonakshi Sinha" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sonakshi Sinha's Dances To Dance Karle English Mein In Joker</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Sonakshi Sinha's Dances To Dance Karle English Mein In Joker" HREF="http://www.bollywoodmovies.us/news/2011/04_11_2011.html">04/14/2011</A>: </font> <br> New debuten of 2010, <A ALT="" TITLE="Sonakshi Sinha" HREF="http://www.bollywoodmovies.us/actress/sonakshi_sinha/bollywood_sonakshi_sinha.html">Sonakshi Sinha</A> who won great reviews for her role in <A ALT="" TITLE="Dabangg Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/dabangg.html">Dabangg (2010)</A> will be performing a some enticing moves in a special song and dance sequence called Dance Karle English Mein in the forthcoming movie <A ALT="" TITLE="Joker Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2011/joker.html">Joker (2011)</A> starring <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A> . The song is just not an item number but is part of the movie story line. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/sarah_jane_dias/bollywood_sarah_jane_dias_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/sarah_jane_dias/pics/sarah_jane_dias_08.jpg" ALT="Sarah Jane Dias Maxim India April 2011" TITLE="Sarah Jane Dias Maxim India April 2011" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sarah Jane Dias On Cover Of Maxim India April 2011 Issue</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Sarah Jane Dias On Cover Of Maxim India April 2011 Issue" HREF="http://www.bollywoodmovies.us/news/2011/04_11_2011.html">04/12/2011</A>: </font> <br> <A ALT="" TITLE="Sarah Jane Dias" HREF="http://www.bollywoodmovies.us/actress/sarah_jane_dias/bollywood_sarah_jane_dias.html">Sarah Jane Dias</A> is being featured on the cover of April 2011 edition of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . The photos will be part of the Maxim India April 2011 edition. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/pics/sania_mirza_02.jpg" ALT="Sania Mirza" TITLE="Sania Mirza" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sania Mirza Jumps 17 Places In WTA singles rankings and Wins Her 2nd WTA Doubles Title</b> <br> <A ALT="" TITLE="Sania Mirza Jumps 17 Places In WTA singles rankings and Wins Her 2nd WTA Doubles Title" HREF="http://www.bollywoodmovies.us/news/2011/04_11_2011.html">04/11/2011</A>: <br> <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> who has been quite in the world of tennis after her marriage seems to be making a comeback. Last week, Indian tennis ace Sania Mirza reached the quarterfinal in the Family Circle Cup at Charleston, South Carolina, USA where she lost to Peng Shuai of China. <BR> But Sania and her doubles partner Elena Vesnina of Russia did win their second WTA title together by beating Americans Bethanie Mattek-Sands and Meghann Shaughnessy in straight-set. </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing April 15, 2011" HREF="http://www.bollywoodmovies.us/news/2011/04_11_2011.html">Movie Releasing April 15, 2011</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Teen Thay Bhai </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
