s|TAG_META_TITLE|Kites, Hrithik Roshan, Barbara Mori, Kangna Ranaut, Rima Fakih, Miss USA 2010|g
s|TAG_META_KEYWORDS|Kites, Hrithik Roshan, Barbara Mori, Kangna Ranaut, Rima Fakih, Miss USA 2010, Aishwarya Rai, Cannes, Martin Scorsese|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_07.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_62.jpg" ALT="Aishwarya Rai" TITLE="Aishwarya Rai" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Martin Scorsese Wants To Cast Aishwarya Rai</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Martin Scorsese Wants To Cast Aishwarya Rai" HREF="http://www.bollywoodmovies.us/news/2010/05_17_2010.html">05/20/2010</A>: </font> <br> The rumor out of the Cannes Film Festival is that <A ALT="" TITLE="Aishwarya Rai" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai</A> is a special guest at a dinner in honour of Scorsese. Aishwarya is was also present at the screening of the latest movie by Scorsese, the Italian film II Gattapardo. The director wants to make the Indian classic Kalpana by Uday Shankar and may have discussed this with the Bollywood film star, Aishwarya. The French press has now been referring to Aish as the ‘Princess of Cannes.’ <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/hrithik_roshan/pics/hrithik_roshan_01.jpg" ALT="Hrithik Roshan" TITLE="Hrithik Roshan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/rima_fakih/models_rima_fakih_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/rima_fakih/pics/rima_fakih_01.jpg" ALT="Rima Fakih" TITLE="Rima Fakih" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing May 21, 2010" HREF="http://www.bollywoodmovies.us/news/2010/05_17_2010.html">Movie Releasing May 21, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Kites" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/kites.html">Kites (2010) </A> <br> Cast: <A ALT="" TITLE="Actor Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan_photo_gallery_01.html">Hrithik Roshan </A> , <A ALT="" TITLE="Actress Kangna Ranaut" HREF="http://www.bollywoodmovies.us/actress/kangna_ranaut/bollywood_kangna_ranaut_photo_gallery_01.html">Kangna Ranaut </A> </font> , <A ALT="" TITLE="Barbara Mori" HREF="http://www.bollywoodmovies.us/actress/barbara_mori/bollywood_barbara_mori.html">Barbara Mori</A>, </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
