s|TAG_META_TITLE|Aishwarya Rai Bachchan And Sonam Kapoor, IIFA Awards 2009, Barbara Mori, Jillian Harris, Picture Of The Day, Adriana Lima|g
s|TAG_META_KEYWORDS|Barbara Mori, Jillian Harris, Picture Of The Day, Aishwarya Rai Bachchan And Sonam Kapoor To Perform At IIFA 2009, French Open, Sania Mirza, Adriana Lima|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/models/adriana_lima/pics/adriana_lima_11.jpg" ALT="Adriana Lima" TITLE="Adriana Lima" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Supermodel Adriana Lima is pregnant!</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Supermodel Adriana Lima is pregnant!" HREF="http://www.bollywoodmovies.us/news/2009/05_25_2009.html">05/31/2009</A>: </font> <br> The Victoria's Secret supermodel <A ALT="" TITLE="Adriana Lima" HREF="http://www.bollywoodmovies.us/models/adriana_lima/models_adriana_lima.html">Adriana Lima</A> is expecting her first child with new husband, NBA player Marko Jaric, her reps confirms to Usmagazine.com. The Brazilian supermodel's baby is due in winter 2009. The wedding was held in Jackson Hole, Wyoming in a private civil ceremony on Valentine's Day. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_07.jpg" ALT="Aishwarya Rai (Aishwarya Bachchan)" TITLE="Aishwarya Rai (Aishwarya Bachchan)" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Aishwarya Rai Bachchan And Sonam Kapoor To Perform At IIFA 2009</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Aishwarya Rai Bachchan And Sonam Kapoor To Perform At IIFA 2009" HREF="http://www.bollywoodmovies.us/news/2009/05_25_2009.html">05/29/2009</A>: </font> <br> <A ALT="" TITLE="Aishwarya Rai (Aishwarya Bachchan)" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> , <A ALT="" TITLE="Sonam Kapoor" HREF="http://www.bollywoodmovies.us/actress/sonam_kapoor/bollywood_sonam_kapoor.html">Sonam Kapoor</A> , and <A ALT="" TITLE="Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor.html">Kareena Kapoor</A> . are going to be performing on stage at the IIFA Awards in Macau on June 11, 2009. The IIFA awards will be hosted by <A ALT="" TITLE="Riteish Deshmukh" HREF="http://www.bollywoodmovies.us/actor/ritesh_deshmukh/bollywood_ritesh_deshmukh.html">Riteish Deshmukh</A> , <A ALT="" TITLE="Lara Dutta" HREF="http://www.bollywoodmovies.us/actress/lara_dutta/bollywood_lara_dutta.html">Lara Dutta</A> and Boman Irani. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/pics/sania_mirza_18.jpg" ALT="Sania Mirza" TITLE="Sania Mirza" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sania Mirza knocked out of French Open singles</b> <br> <A ALT="" TITLE="Sania Mirza knocked out of French Open singles" HREF="http://www.bollywoodmovies.us/news/2009/05_25_2009.html">05/29/2009</A>: <br> <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> was knocked out of the singles match at the French Open by Kazakhstan's Galina Voskoboeva in Roland Garros, score of 4-6 6-7 (3). Sania and her doubles patner Chia-Jung Chuang from Taipei, were able to defeat Ipek Senoglu and Yanina Wickmayer in straight sets to continue to the next round. <BR>On a personel note, Sania will be engaged on July 10 to her classmate from her school days, Hyderabad based businessman, Mr. Muhammad Sohrab Mirza. With wedding date to be formalised later. Also, it is not clear whether Sania will continue playing tennis after marriage or not. Sania Mirza is the first Indian Woman to win a WTA Singles Title and break into the world's top 50. She won a Grand Slam Title this year, when she won the Australian Open Mixed Doubles Titles, with her partner Mahesh Bhupathi. </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actress/barbara_mori/bollywood_barbara_mori_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/barbara_mori/pics/barbara_mori_03.jpg" ALT="Barbara Mori" TITLE="Barbara Mori" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/jillian_harris/celebrites_jillian_harris_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/jillian_harris/pics/jillian_harris_01.jpg" ALT="Jillian Harris" TITLE="Jillian Harris" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing May 29, 2009: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> The Murderer </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
