s|TAG_META_TITLE|Chitrangada Singh Maxim India May 2010, Rima Fakih, Rajneeti (2010)|g
s|TAG_META_KEYWORDS|Rima Fakih, Hrithik Roshan, Chitrangada Singh Maxim India May 2010, Rajneeti (2010)|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/katrina_kaif/pics/katrina_kaif_04.jpg" ALT="Katrina Kaif" TITLE="Katrina Kaif" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Rajneeti First Get Adult Certificate And Now U/A Certificate</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Rajneeti First Get Adult Certificate And Now U/A Certificate" HREF="http://www.bollywoodmovies.us/news/2010/05_24_2010.html">05/27/2010</A>: </font> <br> <A ALT="" TITLE="Rajneeti Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/rajneeti.html">Rajneeti (2010)</A> initially got an adult certifidate on May 21 and after director Prakash Jha cut the lovemaking scene of Arjun and <A ALT="" TITLE="Katrina Kaif" HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif.html">Katrina Kaif</A> by half, replacing the F-word used in one of <A ALT="" TITLE="Arjun Rampal" HREF="http://www.bollywoodmovies.us/actor/arjun_rampal/bollywood_arjun_rampal.html">Arjun Rampal</A> 's dialogues; beep to replace cuss word in <A ALT="" TITLE="Ranbir Kapoor" HREF="http://www.bollywoodmovies.us/actor/ranbir_kapoor/bollywood_ranbir_kapoor.html">Ranbir Kapoor</A> 's dialogue it is now given a U/A Certificate by the Central Board of Film Certification. The movie also stars Nana Patekar, Ajay Devgan, Manoj Bajpai, and Naseeruddin Shah. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/chitrangada_singh/bollywood_chitrangada_singh_photo_gallery_08.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/chitrangada_singh/pics/chitrangada_singh_05.jpg" ALT="Chitrangada Singh Maxim India May 2010" TITLE="Chitrangada Singh Maxim India May 2010" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Chitrangada Singh On Cover Of Maxim India May 2010 Issue</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Chitrangada Singh On Cover Of Maxim India May 2010 Issue" HREF="http://www.bollywoodmovies.us/news/2010/05_24_2010.html">05/26/2010</A>: </font> <br> <A ALT="" TITLE="Chitrangada Singh" HREF="http://www.bollywoodmovies.us/actress/chitrangada_singh/bollywood_chitrangada_singh.html">Chitrangada Singh</A> is being featured on the cover of May 2010 edition of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . The photos will be part of the Maxim India May 2010 edition. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE|<!-- TV_SHOWS_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Manav, Archana a real life couple?" HREF="http://www.bollywoodmovies.us/news/2010/05_24_2010.html">05/24/2010</A> <br> The onscreen couple of <A ALT="" TITLE="Pavitra Rishta" HREF="http://www.bollywoodmovies.us/tv_shows/pavitra_rishta.html">Pavitra Rishta</A>, Manav Deshmukh (Sushant Singh Rajput) and Archana Deshmukh ( <A ALT="" TITLE="Ankita Lokhande" HREF="http://www.bollywoodmovies.us/actress/ankita_lokhande/bollywood_ankita_lokhande.html">Ankita Lokhande</A> ) a real life couple? They are shown to be madly in love on screen and that love may have transition into real life. Given they are work together for more then 14 hours a day, something is bound to happen. If the rumors are we all wish them the best on their on screen romance as well as in real life. <hr size="1" width="100%"> </td> </tr> <!-- TV_SHOWS_END -->|g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/hrithik_roshan/pics/hrithik_roshan_01.jpg" ALT="Hrithik Roshan" TITLE="Hrithik Roshan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/rima_fakih/models_rima_fakih_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/rima_fakih/pics/rima_fakih_01.jpg" ALT="Rima Fakih" TITLE="Rima Fakih" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES||g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
