s|TAG_META_TITLE|I Hate Luv Storys, Actor Imran Khan, Sonam Kapoor, Sonali Bendre, Kim Kardashian|g
s|TAG_META_KEYWORDS|I Hate Luv Storys, Actor Imran Khan, Sonam Kapoor, Sonali Bendre To Be A Judge On India's Got Talent Khoj 2, Mahendra Singh Dhoni, Kim Kardashian|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/kim_kardashian/celebrites_kim_kardashian_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/kim_kardashian/pics/kim_kardashian_01.jpg" ALT="Kim Kardashian" TITLE="Kim Kardashian" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Kim Kardashian Has A New Boyfriend</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Kim Kardashian Has A New Boyfriend" HREF="http://www.bollywoodmovies.us/news/2010/06_28_2010.html">07/03/2010</A>: </font> <br> <A ALT="" TITLE="Kim Kardashian" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/kim_kardashian/celebrites_kim_kardashian.html">Kim Kardashian</A> had been dating Orleans Saints running back Reggie Bush for a while and now just two months after splitting with Reggie, Kim was seen with Dallas Cowboys wide receiver Miles Austin. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END --><!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/sonali_bendre/bollywood_sonali_bendre_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/sonali_bendre/pics/sonali_bendre_01.jpg" ALT="Sonali Bendre" TITLE="Sonali Bendre" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Sonali Bendre To Be A Judge On India's Got Talent Khoj 2</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Sonali Bendre To Be A Judges On India's Got Talent Khoj 2" HREF="http://www.bollywoodmovies.us/news/2010/06_28_2010.html">07/01/2010</A>: </font> <br> Bollywood star <A ALT="" TITLE="Sonali Bendre" HREF="http://www.bollywoodmovies.us/actress/sonali_bendre/bollywood_sonali_bendre.html">Sonali Bendre</A> has been signed to be part of the judgeing panel on Color's talent show ‘India's Got Talent Khoj 2', which is scheduled to start goes on August. Sonali is in her mid-thirties but still look young and beautiful as she did when she starred in movies like Sarfarosh, Major Saab and Anaahat(Marathi). She has also been a judge on TV shows Kya Masti Kya Dhoom!, Indian Idol Season 4 and India's Got Talent. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center" colspan=2> <A ALT="" TITLE="Mahendra Singh Dhoni Engaged To School Friend" HREF="http://www.bollywoodmovies.us/news/2010/06_28_2010.html">07/03/2010</A>: <br> Indian cricket team captin <A ALT="" TITLE="Mahendra Singh Dhoni" HREF="http://www.bollywoodmovies.us/sports/cricket/mahendra_singh_dhoni/cricket_mahendra_singh_dhoni.html">Mahendra Singh Dhoni</A> has taken the next big step in his life by getting engaged to his friend Sakshi Singh Rawat at Bhagirath hotel in Dehradun. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing July 02, 2010" HREF="http://www.bollywoodmovies.us/news/2010/06_28_2010.html">Movie Releasing July 02, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for I Hate Luv Storys" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/i_hate_luv_storys.html">I Hate Luv Storys (2010) </A> <br> Cast: <A ALT="" TITLE="Actor Imran Khan" HREF="http://www.bollywoodmovies.us/actor/imran_khan/bollywood_imran_khan_photo_gallery_01.html">Imran Khan </A> , <A ALT="" TITLE="Actress Sonam Kapoor" HREF="http://www.bollywoodmovies.us/actress/sonam_kapoor/bollywood_sonam_kapoor_photo_gallery_01.html">Sonam Kapoor </A> </font> , Sameer Dattani, Bruna Abdullah, Kavin Dave, Kavi Shastri, Pooja Ghai, Ketki Dave </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
