s|TAG_META_TITLE|Milenge Milenge, Shahid Kapoor, Kareena Kapoor, Rima Fakih, Ali Larter, Hrithik Roshan, London, Wax, Pavitra Rishta|g
s|TAG_META_KEYWORDS|Milenge Milenge, Shahid Kapoor, Kareena Kapoor, Rima Fakih, Ali Larter, Hrithik Roshan, London, Wax, Pavitra Rishta|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/hrithik_roshan/pics/hrithik_roshan_01.jpg" ALT="Hrithik Roshan" TITLE="Hrithik Roshan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Hrithik Roshan Wax Figure In Madame Tussauds London</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Hrithik Roshan Wax Figure In Madame Tussauds London" HREF="http://www.bollywoodmovies.us/news/2010/07_05_2010.html">07/05/2010</A>: </font> <br> Bollywood star <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> will join <A ALT="" TITLE="Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan.html">Amitabh Bachchan</A> , <A ALT="" TITLE="Salman Khan" HREF="http://www.bollywoodmovies.us/actor/salman_khan/bollywood_salman_khan.html">Salman Khan</A> and <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> as the next Bollywood actor to have his wax figure at the famous Madame Tussauds in London. Hrithik is currently in Spain shooting for his next film, <A ALT="" TITLE="Zindagi Milegi Na Dobara Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/zindagi_milegi_na_dobara.html">Zindagi Milegi Na Dobara (2010)</A> .<BR> <A ALT="" TITLE="Shahrukh Khan" HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan.html">Shahrukh Khan</A> 's wax figure was the first one for a Bollywood star in the Madame Tussauds in Los Angeles. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE|<!-- TV_SHOWS_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Pavitra Rishta July 11 2010" HREF="http://www.bollywoodmovies.us/news/2010/07_05_2010.html">07/11/2010</A> <br> <A ALT="" TITLE="Ankita Lokhande" HREF="http://www.bollywoodmovies.us/actress/ankita_lokhande/bollywood_ankita_lokhande.html">Ankita Lokhande</A> household is busy preparing for Vaishali marriage, as enters Archana back home after one year of not seeing any of them. The whole family is very happy to see her. Soon thereafter they again were busy with the preperation for the wedding. They Archana goes across the street to get some more sweets and at that time Manav and his friend walk by with his son. Nither Archana or Manav see other. Manav gets a call and he leaves the baby with his friend who is unable to calm him done, at which point Archana asks to hold the baby and he calms down, unknowingly she is holding onto Manav's and Sharvani's baby. She then gives the baby back to Manav's friend and walks away. The episode ends with Archana mentioning the baby and how it felt that she and the baby had some relationship. <hr size="1" width="100%"> </td> </tr> <!-- TV_SHOWS_END --> <!-- TV_SHOWS_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Pavitra Rishta July 08 2010" HREF="http://www.bollywoodmovies.us/news/2010/07_05_2010.html">07/08/2010</A> <br> <A ALT="" TITLE="Pavitra Rishta" HREF="http://www.bollywoodmovies.us/tv_shows/pavitra_rishta.html">Pavitra Rishta</A> jumped one year into the future with <A ALT="" TITLE="Ankita Lokhande" HREF="http://www.bollywoodmovies.us/actress/ankita_lokhande/bollywood_ankita_lokhande.html">Ankita Lokhande</A> arriving back home via train, while Manav and Shravani rasing Sachin's and Sharvani's son, and the Archana's parents busy planning a wedding for their 3rd daughter Vaishali, and Varsha seems to be have been staying with her parents for the last year away from Satish. <hr size="1" width="100%"> </td> </tr> <!-- TV_SHOWS_END -->|g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center" colspan=2> <A ALT="" TITLE="LeBron James decides to go down south" HREF="http://www.bollywoodmovies.us/news/2010/07_05_2010.html">07/08/2010</A>: <br> On live tv, for the first time, a basketball player announces his next team. <A ALT="" TITLE="LeBron James" HREF="http://www.bollywoodmovies.us/sports/basketball/lebron_james/basketball_lebron_james.html">LeBron James</A> , of the former Cleveland Cavaliers, announces his decision to move to the Miami heat as is next team. LeBron will be the teammate of Chris Bosh and <A ALT="" TITLE="Dwyane Wade" HREF="http://www.bollywoodmovies.us/sports/basketball/dwyane_wade/basketball_dwyane_wade.html">Dwyane Wade</A> who yesterday announced their decision to play for the Miami heat. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/ali_larter/celebrites_ali_larter_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/ali_larter/pics/ali_larter_02.jpg" ALT="Ali Larter" TITLE="Ali Larter" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/rima_fakih/models_rima_fakih_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/rima_fakih/pics/rima_fakih_01.jpg" ALT="Rima Fakih" TITLE="Rima Fakih" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing Jul7 9, 2010 " HREF="http://www.bollywoodmovies.us/news/2010/07_05_2010.html">Movie Releasing July 09, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Red Alert - The War Within <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Milenge Milenge" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/milenge_milenge.html">Milenge Milenge (2010) </A> <br> Cast: <A ALT="" TITLE="Actor Shahid Kapoor" HREF="http://www.bollywoodmovies.us/actor/shahid_kapoor/bollywood_shahid_kapoor_photo_gallery_01.html">Shahid Kapoor </A> , <A ALT="" TITLE="Actress Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor_photo_gallery_01.html">Kareena Kapoor </A> </font> , Delnaaz Paul, Satish Shah, Aarti Chhabria, Kirron Kher, Himani Shivpuri </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
