s|TAG_META_TITLE|Katrina Kaif To Perform Song As A Belly Dancer, Ankita Lokhande, Pavitra Rishta|g
s|TAG_META_KEYWORDS|Katrina Kaif To Perform Song As A Belly Dancer, Tees Maar Khan Movie Review, Zindagi Milegi Na Dobara Movie Review, Ankita Lokhande, Pavitra Rishta|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/katrina_kaif/pics/katrina_kaif_25.jpg" ALT="Katrina Kaif" TITLE="Katrina Kaif" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Katrina Kaif To Perform Song As A Belly Dancer</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Katrina Kaif To Perform Song As A Belly Dancer" HREF="http://www.bollywoodmovies.us/news/2010/07_12_2010.html">07/12/2010</A>: </font> <br> <A ALT="" TITLE="Katrina Kaif" HREF="http://www.bollywoodmovies.us/actress/katrina_kaif/bollywood_katrina_kaif.html">Katrina Kaif</A> will be performing a song in which she will be dancing like a belly dancer. The song will be choreographed by Farah Khan for her movie <A ALT="" TITLE="Tees Maar Khan Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/tees_maar_khan.html">Tees Maar Khan (2010)</A> , which stars <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A> , <A ALT="" TITLE="Akshaye Khanna" HREF="http://www.bollywoodmovies.us/actor/akshaye_khanna/bollywood_akshaye_khanna.html">Akshaye Khanna</A> , and <A ALT="" TITLE="Deepika Padukone" HREF="http://www.bollywoodmovies.us/actress/deepika_padukone/bollywood_deepika_padukone.html">Deepika Padukone</A> . The director also mentioned that Katrina will be learning the dance to ensure the item number is done justice. Katrina is currently busy shooting for Zoya Akthar’s <A ALT="" TITLE="Zindagi Milegi Na Dobara Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/zindagi_milegi_na_dobara.html">Zindagi Milegi Na Dobara (2010)</A> . <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE|<!-- TV_SHOWS_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A HREF="http://www.bollywoodmovies.us/actress/ankita_lokhande/bollywood_ankita_lokhande_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/ankita_lokhande/pics/ankita_lokhande_01.jpg" ALT="Kim Kardashian" TITLE="Kim Kardashian" WIDTH="100" HEIGHT="100" BORDER="0"> </A> <BR> <A ALT="" TITLE="Pavitra Rishta July 15 2010" HREF="http://www.bollywoodmovies.us/news/2010/07_12_2010.html">07/15/2010</A> <br> Today's episode started off like the last couple, slow. <A ALT="" TITLE="Ankita Lokhande" HREF="http://www.bollywoodmovies.us/actress/ankita_lokhande/bollywood_ankita_lokhande.html">Ankita Lokhande</A> has started a new job, at Dharmeshes car garage , as a administrative supervisor and it happens that Manav works for the same car garage as a mechanic. The middle of the episode show Rasika, Ajit and Vandita in their new house, in Manav's neighborhood. They have lost all their money and are now fighting to stay alive one day at a time. Manav stops by to drop of some money for his sister, as he does monthly. Later Ajit is shown to be a new and improved man with no job, atleast he is nice to Vandita. Archana is thinking of quiting the job given she cannot have Manav work for her, but her mom convince her to stick it out a couple of more days. Later that day Archana is traveling in the same train as Shravani, who is caught without a ticket given Manav is in the men's compartment. Archana over heres them and finds out that their last name are different and they have not gotten married. This opens up the door for Manav and Archana? Watch and find out. <hr size="1" width="100%"> </td> </tr> <!-- TV_SHOWS_END -->|g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES||g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
