s|TAG_META_TITLE|Bodyguard, Salman Khan, Actress Kareena Kapoor|g
s|TAG_META_KEYWORDS|Bodyguard, Salman Khan, Actress Kareena Kapoor, Celina Jaitley and Peter Haag, Wedding, Marriage, Dubai|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/celina_jaitley/pics/celina_jaitley_22.jpg" ALT="Celina Jaitley" TITLE="Celina Jaitley" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Celina Jaitley Announced Her Marriage Via Twitter</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Celina Jaitley Announced Her Marriage Via Twitter" HREF="http://www.bollywoodmovies.us/news/2011/08_29_2011.html">08/29/2011</A>: </font> <br> Bollywood actress <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> recently announced her wedding to Peter Haag on Twitter. The wedding took place last month in a monastery in Austria. Peter Haag is a Dubai based hotelier. Celina Jaitley and Peter Haag have been together since one-and-a-half years now. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD|<!-- INDIA_STORY_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Heavy Rains In Mumbai" HREF="http://www.bollywoodmovies.us/news/2011/08_29_2011.html">08/29/2011</A>: <br> On Monday, <A ALT="" TITLE="Maharashtra Mumbai" HREF="http://www.bollywoodmovies.us/Regional/India/Maharashtra/Mumbai/Mumbai.html">Mumbai</A> city’s transport system were strangulated by the rain that fell over the weekend. Suburban trains on all the three lines, Central, Western and Harbour, came to a standstill. With visibility levels falling below 450 metres, air traffic in the two city airports were halted. A portion of a small hill near the city's famous Haji Ali Dargah collapsed; one person has died. <hr size="1" width="100%"> </td> </tr> <!-- INDIA_STORY_END -->|g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<center><b><font color="#0033cc" size="5"> <A ALT="" TITLE="Pictures Of The Day Bollywood Actress Anushka Sharma And Bollywood Actor Shahrukh Khan (SRK)" HREF="http://www.bollywoodmovies.us/news/2011/05_23_2010.html">Pictures Of The Day</A>: </font></b></center> <A HREF="http://www.bollywoodmovies.us/actor/shahrukh_khan/bollywood_shahrukh_khan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/shahrukh_khan/pics/shahrukh_khan_07.jpg" ALT="Shahrukh Khan (SRK)" TITLE="Shahrukh Khan (SRK)" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actress/anushka_sharma/bollywood_anushka_sharma_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/anushka_sharma/pics/anushka_sharma_06.jpg" ALT="Anushka Sharma" TITLE="Anushka Sharma" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing August 26, 2011" HREF="http://www.bollywoodmovies.us/news/2011/08_29_2011.html">Movie Releasing August 31, 2011</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Bol <hr size="1" width="100%"> Mummy Punjabi <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Bodyguard" HREF="http://www.bollywoodmovies.us/movie_reviews/2011/bodyguard.html">Bodyguard (2011) </A> <br> Cast: <A ALT="" TITLE="Actor Salman Khan" HREF="http://www.bollywoodmovies.us/actor/salman_khan/bollywood_salman_khan_photo_gallery_01.html">Salman Khan </A> , <A ALT="" TITLE="Actress Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor_photo_gallery_01.html">Kareena Kapoor </A> </font> , </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
