s|TAG_META_TITLE|Aishwarya Rai Bachchan Walks The Ramp After 15 Years|g
s|TAG_META_KEYWORDS|Aishwarya Rai Bachchan Walks The Ramp After 15 Years|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/aishwarya_rai/pics/aishwarya_rai_22.jpg" ALT="Aishwarya Rai" TITLE="Aishwarya Rai" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Aishwarya Rai Bachchan Walks The Ramp After 15 Years</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Aishwarya Rai Bachchan Walks The Ramp After 15 Years" HREF="http://www.bollywoodmovies.us/news/2010/10_04_2010.html">10/07/2010</A>: </font> <br> Former Miss World and Bollywood actress <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> walked the ramp as the showstopper for friend and fashion designer Manish Malhotra on the first day of the HDIL India Couture Week 2010 in Mumbai, India. Aishwarya was dressed in a traditional ivory colored lehnga and a sexy backless corset. Aishwarya recent release includes <A ALT="" TITLE="Enthiram Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/enthiram.html">Enthiram (2010)</A> opposite <A ALT="" TITLE="Rajnikanth" HREF="http://www.bollywoodmovies.us/kollywood/actor/rajnikanth/kollywood_rajnikanth.html">Rajnikanth</A> and her upcoming movies are <A ALT="" TITLE="Guzaarish Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2010/guzaarish.html">Guzaarish (2010)</A> opposite Bollywood heartthrob <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> and <A ALT="" TITLE="Action Replay Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/action_replay.html">Action Replay (2010)</A> opposite <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A>. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center" colspan=2> <A ALT="" TITLE="Donovan McNabb Wins Against Philadelphia Eagles" HREF="http://www.bollywoodmovies.us/news/2010/10_04_2010.html">10/4/2010</A>: <br> Donovan McNabb returned to play in Philadelphia against the Eagle for the first time after his trade to the Washington Redskins, and he had a memorable game. The Washington Redskins defeated the Philadelphia Eagles 17, 12 to take the top spot in their division. The game started off real fast for the Redskins, with 2 quick scores. In the 2nd half, the Redskins offense was very quite. The Eagles were doing well until Michael Vick injury. The Eagles offense too was very quite after that. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END --> <!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center" colspan=2> <A ALT="" TITLE="India Beats Australia In Mohali" HREF="http://www.bollywoodmovies.us/news/2010/10_04_2010.html">10/5/2010</A>: <br> India beats Australia in Mohali in an unbelievable finish. India wins a one wicket victory against Australia, in the first of a two-test series. VVS Laxman set up a decisive 81 run ninth wicket partnership with Ishant Sharma, India came back from 124/8 to stun the Australian. On the fifth and final day of the first test at Mohali, Laxman's 73 runs from 79 balls ensured India will retain the Border Gavaskar Trophy. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK||g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing October 08, 2010" HREF="http://www.bollywoodmovies.us/news/2010/10_04_2010.html">Movie Releasing October 08, 2010</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Crook: It'S Good To Be Bad <hr size="1" width="100%"> Do Dooni Chaar <hr size="1" width="100%"> Lava Kusa <hr size="1" width="100%"> Bachao <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK||g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
