s|TAG_META_TITLE|Shilpa Shetty Marries Raj Kundra, Kurbaan, Saif Ali Khan, Kareena Kapoor|g
s|TAG_META_KEYWORDS|Kurbaan, Saif Ali Khan, Kareena Kapoor, Natalia Vodianova, Model, Shilpa Shetty Marries Raj Kundra|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty_photo_gallery_04.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/shilpa_shetty/pics/shilpa_shetty_31.jpg" ALT="Shilpa Shetty" TITLE="Shilpa Shetty" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Shilpa Shetty Marries Raj Kundra</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Shilpa Shetty Married Raj Kundra" HREF="http://www.bollywoodmovies.us/news/2009/11_16_2009.html">11/22/2009</A>: </font> <br> On 22nd November 2009, Bollywood actress and Celebrity Big Brother star <A ALT="" TITLE="Shilpa Shetty" HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty.html">Shilpa Shetty</A> married London based businessman Raj Kundra in Khandala. Shilpa was dressed in red-and-gold saree. The two had met after Shilpa rose to fame as the winner of the British reality show 'Celebrity Big Brother' in a controversial 2007 season. On Tuesday 24 November 2009, Shetty and Kundra will host a wedding reception in Mumbai. <hr size="1" width="100%"> </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD||g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/models/daria_werbowy/models_daria_werbowy_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/daria_werbowy/pics/daria_werbowy_08.jpg" ALT="Daria Werbowy" TITLE="Daria Werbowy" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/models/natalia_vodianova/models_natalia_vodianova_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/models/natalia_vodianova/pics/natalia_vodianova_01.jpg" ALT="Natalia Vodianova" TITLE="Natalia Vodianova" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> <A ALT="" TITLE="Bollywood Movie Releasing Movie Releasing November 20, 2009" HREF="http://www.bollywoodmovies.us/news/2009/11_16_2009.html">Movie Releasing November 20, 2009</A>: </font></strong> </TD> </TR> <!-- ------------ --> <!-- REVIEW_START --> <!-- ------------ --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> Marega Salaa <hr size="1" width="100%"> Shaabash! You Can Do It <hr size="1" width="100%"> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Kurbaan" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/kurbaan.html">Kurbaan (2009) </A> <br> Cast: <A ALT="" TITLE="Actor Saif Ali Khan" HREF="http://www.bollywoodmovies.us/actor/saif_ali_khan/bollywood_saif_ali_khan_photo_gallery_01.html">Saif Ali Khan </A> , <A ALT="" TITLE="Actress Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor_photo_gallery_01.html">Kareena Kapoor </A> </font> , Vivek Oberoi, Om Puri , Dia Mirza </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_TOP_10_SONGS_OF_WEEK|<!-- TABLE_SEPARATOR_START --> <TABLE WIDTH=100% ALIGN="center" cellspacing="0" border="1" bordercolor="blue"> <TR> <TD> <center><b><font color="#0033cc" size="4">Top 10 Songs Of The Week (11/17/2009)</font></b></center> <hr size="2" width="100%"s color="#0000FF"> <b>10.</b> <A ALT="" TITLE="Jail Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/jail.html">Jail (2009)</A> <hr size="2" width="100%"> <b>09.</b> <A ALT="" TITLE="All The Best Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/all_the_best.html">All The Best (2009)</A> <hr size="2" width="100%"> <b>08.</b> <A ALT="" TITLE="Blue Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/blue.html">Blue (2009)</A> <hr size="2" width="100%"> <b>07.</b> <A ALT="" TITLE="3 Idiots Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/3_idiots.html">3 Idiots (2009)</A> <hr size="2" width="100%"> <b>06.</b> <A ALT="" TITLE="Wake up Sid Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/wake_up_sid.html">Wake up Sid (2009)</A> <hr size="2" width="100%"> <b>05.</b> <A ALT="" TITLE="Tum Mile Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/tum_mile.html">Tum Mile (2009)</A> <hr size="2" width="100%"> <b>04.</b> <A ALT="" TITLE="London Dreams Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/london_dreams.html">London Dreams (2009)</A> <hr size="2" width="100%"> <b>03.</b> <A ALT="" TITLE="De Dhana Dhan Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/de_dhana_dhan.html">De Dhana Dhan (2009)</A> <hr size="2" width="100%"> <b>02.</b> <A ALT="" TITLE="Kurbaan Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/kurbaan.html">Kurbaan (2009)</A> <hr size="2" width="100%"> <b>01.</b> <A ALT="" TITLE="Ajab Prem Ki Ghazab Kahani (APKGK) Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/ajab_prem_ki_ghazab_kahani.html">Ajab Prem Ki Ghazab Kahani (APKGK) (2009)</A> <hr size="2" width="100%"> </TD> </TR> </TABLE> <!-- TABLE_SEPARATOR_END -->|g
#
s|TAG_HEADLINES_OF_THE_WEEK||g
