s|TAG_META_TITLE|Hrithik Roshan, Neha Dhupia, Dus Kahaniyan, Khoya Khoya Chand, iPhone, Flickr|g
s|TAG_META_KEYWORDS|Hrithik Roshan, Neha Dhupia, Dus Kahaniyan, Khoya Khoya Chand, iPhone, Flickr|g
#
s|TAG_NEWS_WITH_IMAGE||g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD|<!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="Google Enables More Apps for the iPhone" HREF="http://www.bollywoodmovies.us/news/2007/12_03_2007.html">12/07/2007</A>: <br> Today Google announced that is has optimized the Google Search, Gmail, Google Calendar and Google Reader for the iPhone which builds upon other Google products like Maps and YouTube that are already available. When a iPhone user visits the Google main site, the iPhone is automatically detected and the apps are made avaialble to the user via iPhone's Safari browser. In other news, Google introduced the addition of AIM (AOL Instant Messenger) To Gmail. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END --><!-- MONEY_NEWS_STORY_START --> <tr HEIGHT=30 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <A ALT="" TITLE="Yahoo Flickr Image Editing Tools" HREF="http://www.bollywoodmovies.us/news/2007/12_03_2007.html">12/05/2007</A>: <br> Yahoo's online photo sharing service Flickr, an online photo sharing website, today announced the introduction of new online digital imagee editing tools that can be used by members to edit photos. The tools suite will be provided by Picnik. Flickr was purchased by Yahoo back in 2005 at which time, Yahoo discontinued it's own Yahoo Photos service for Flickr. <hr size="1" width="100%"> </td> </tr> <!-- MONEY_NEWS_STORY_END -->|g
#
s|TAG_NEWS_SPORT||g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/actress/neha_dhupia/bollywood_neha_dhupia_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/neha_dhupia/pics/neha_dhupia_07.jpg" ALT="Neha Dhupia" TITLE="Neha Dhupia" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/hrithik_roshan/pics/hrithik_roshan_03.jpg" ALT="Hrithik Roshan" TITLE="Hrithik Roshan" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing December 07, 2007: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Dus Kahaniyan" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/dus_kahaniyan.html">Dus Kahaniyan (2007) </A> <br> Cast: <A ALT="" TITLE="Bollywood Movie Review, Sanjay Dutt" HREF="http://www.bollywoodmovies.us/actor/sanjay_dutt/bollywood_sanjay_dutt_photo_gallery_01.html">Sanjay Dutt </A> , <A ALT="" TITLE="Bollywood Movie Review, Neha Dhupia" HREF="http://www.bollywoodmovies.us/actress/neha_dhupia/bollywood_neha_dhupia_photo_gallery_01.html">Neha Dhupia </A> </font> </td> </tr> <!-- REVIEW_START_END --> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Khoya Khoya Chand" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/khoya_khoya_chand.html">Khoya Khoya Chand (2007) </A> <br> Cast: <A ALT="" TITLE="Bollywood Movie Review, Shiny Ahuja" HREF="http://www.bollywoodmovies.us/actor/shiny_ahuja/bollywood_shiny_ahuja_photo_gallery_01.html">Shiny Ahuja </A> , <A ALT="" TITLE="Bollywood Movie Review, Soha Ali Khan" HREF="http://www.bollywoodmovies.us/actress/soha_ali_khan/bollywood_soha_ali_khan_photo_gallery_01.html">Soha Ali Khan </A> </font> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_DATE_MONTH|2007_12_Dec|g