s|TAG_META_TITLE|Hrithik Roshan, Krazzy 4, Benazir Bhutto, Sania Mirza, Hanuman 2|g
s|TAG_META_KEYWORDS|Hrithik Roshan, Krazzy 4, Benazir Bhutto, Sania Mirza, Gauri Khan Vouge, Kingfisher Swimsuit Calendar 2008, Hanuman 2|g
#
s|TAG_NEWS_WITH_IMAGE|<!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/actor/hrithik_roshan/pics/hrithik_roshan_01.jpg" ALT="Hrithik Roshan" TITLE="Hrithik Roshan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b>Hrithik Roshan To Perform Song In Krazzy 4</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Hrithik Roshan Krazzy 4" HREF="http://www.bollywoodmovies.us/news/2007/12_24_2007.html">12/28/2007</A>: </font> <br> <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> will be seen in a item song in the forthcoming movie <A ALT="" TITLE="Krazzy 4 Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/krazy_4.html">Krazy 4 (2008)</A> . Currently Hrithik is recovering from a knee surgery. The appearence will mark his father's, Rakesh Roshan, first production without Hrithik as a hero in the film. The songs music is provided by Rajesh Roshan and will be shot in March 2008 if Hrithik is feeling upto it. </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_WITHOUT_IMAGE||g
#
s|TAG_NEWS_WORLD|<!-- STORY_START --> <TR ALIGN="left"> <TD WIDTH=900 bgcolor="white"> <A ALT="" TITLE="Benazir Bhutto Assassinated" HREF="http://www.bollywoodmovies.us/news/2007/12_24_2007.html">12/27/2007</A>: <br> Benazir Bhutto, former Prime Minister of Pakistan, was killed after a campaign rally in the city of Rawalpindi where she had just finished giving an address to her supporters. She was taken to Rawalpindi General Hospital where surgeons were unable to save her. The attacker first fired at her and then blew himself up, killing Bhutto and 15 to 20 other bystanders. Bhutto had recently returned back to Pakistan after her exile. </TD> </TR> <!-- STORY_END -->|g
#
s|TAG_NEWS_SPORT|<!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- STORY_START --> <TR VALIGN="top"> <TD WIDTH=15% BORDER="1" BORDERCOLOR="orange"> <A HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/pics/sania_mirza_02.jpg" ALT="Sania Mirza" TITLE="Sania Mirza" WIDTH="100" HEIGHT="100" BORDER="0"> </A> </TD> <TD WIDTH=75% BORDER="1" BORDERCOLOR="green"> <b></b> <br> <A ALT="" TITLE="Sania Mirza Addidas" HREF="http://www.bollywoodmovies.us/news/2007/12_24_2007.html">12/27/2007</A>: <br> <A ALT="" TITLE="Sania Mirza" HREF="http://www.bollywoodmovies.us/sports/tennis/sania_mirza/tennis_sania_mirza.html">Sania Mirza</A> has been signed by Addidas as their first global brand ambassador. Sania joins a list of other well known brand ambassadors of Addidas to inlcude David Beckham (football, soccer), Zin dine Zidane, Sachin Tendulkar (cricket) and Ricky Ponting (cricket). Sania will next be playing mixed-team competition in The Hopman Cup and then onto the Hobart International, starting January 7, 2008 and then the Fed Cup in February 2008. Sania will be paired with Rohan Bopanna and will face Meghann Shaughnessy and Mardy Fish (United States), followed by a match against Alicia Molik and Peter Luczak (Australia) and then Lucie Safarova and Tomas Berdych (Czech Republic). </TD> </TR> <!-- STORY_END --> </table> <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->|g
#
s|TAG_PICTURES_OF_THE_WEEK|<A HREF="http://www.bollywoodmovies.us/producer/gauri_khan/bollywood_gauri_khan_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/producer/gauri_khan/pics/gauri_khan_01.jpg" ALT="Gauri Khan" TITLE="Gauri Khan" WIDTH="100" HEIGHT="100" BORDER="0"> </A> .. <A HREF="http://www.bollywoodmovies.us/info/kingfisher_swimsuit_calendar.html"> <IMG SRC="http://www.bollywoodmovies.us/info/pics/kingfisher_swimsuit_2008_03.jpg" ALT="Kingfisher Swimsuit Calendar 2008" TITLE="Kingfisher Swimsuit Calendar 2008" WIDTH="100" HEIGHT="100" BORDER="0"> </A>|g
#
s|TAG_MOVIE_RELEASES|<!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_START --> <TABLE width=100% align="center" cellspacing="0" border="1" bordercolor="#ffdead" id="Movie Reviews Table"> <TR ALIGN="center"> <TD WIDTH=100% bgcolor="#ffdead"> <strong><font color="#3300ff" size="4"> Movie Releasing December 28, 2007: </font></strong> </TD> </TR> <!-- REVIEW_START --> <TR ALIGN="left" BORDER="0"> <TD WIDTH=100% bgcolor="white"> <table WIDTH=100% border="0" cellspacing="0" cellpadding="0" bgcolor="white"> <!-- REVIEW_START_START --> <tr HEIGHT=40 bgcolor="white"> <td WIDTH=100% VALIGN="center" align="left" valign="center"> <font size="2" face="Verdana, Arial, Helvetica, sans-serif"> <A ALT="" TITLE="Bollywood Movie Review for Hanuman 2" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/hanuman_2.html">Hanuman 2 (2007) </A> <br> </font> </td> </tr> <!-- REVIEW_START_END --> </table> </TD> </TR> <!-- REVIEW_END --> </TABLE> <!-- MOVIE_RELEASE_NEXT_WEEK_TABLE_END -->|g
#
s|TAG_DATE_MONTH|2007_12_Dec|g