s|TAG_META_TITLE|Ankita Lokhande|g
s|TAG_META_KEYWORDS|Ankita Lokhande, tv show, zee tv, Pavitra Rishta, Archana Deshmukh, Manav Deshmukh|g
s|TAG_META_DESCRIPTION|Ankita Lokhande is an Indian movie actress. Ankita well known for her role as Archana Deshmukh on Zee TV show Pavitra Rishta.|g
#
s|TAG_BIOGRAPHY_1|<b>Ankita Lokhande</b> was born on __ in __.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Ankita Lokhande is an Indian movie actress. Ankita well known for her role as Archana Deshmukh on Zee TV show <A ALT="" TITLE="Pavitra Rishta" HREF="http://www.bollywoodmovies.us/tv_shows/pavitra_rishta.html">Pavitra Rishta</A>.|g
#
s|TAG_BIO_LATEST_NEWS|<b>Jhalak Dikhhla Jaa Season 4</b> <br> Date: <A ALT="" TITLE="Jhalak Dikhhla Jaa Season 4" HREF="http://www.bollywoodmovies.us/news/2010/12_20_2010.html">12/20/2010</A>: <br> <A ALT="" TITLE="Madhuri Dixit" HREF="http://www.bollywoodmovies.us/actress/madhuri_dixit/bollywood_madhuri_dixit.html">Madhuri Dixit</A> has been signed as one of the judge for season 4 of <A ALT="" TITLE="Jhalak Dikhhla Jaa 4" HREF="http://www.bollywoodmovies.us/tv_shows/jhalak_dikhhla_jaa/jhalak_dikhhla_jaa.html">Jhalak Dikhhla Jaa</A>, along with Bollywood movie star <A ALT="" TITLE="Malaika Arora Khan" HREF="http://www.bollywoodmovies.us/actress/malaika_arora/bollywood_malaika_arora.html">Malaika Arora Khan</A> , Remo D'souza and is hosted by Mona Singh and Sumeet Raghavan. This years contestants are Sushant Singh Rajput (TV Actor - Known as Manav in Pavitra Rishta), Anushka Manchanda (Singer), <A ALT="" TITLE="Ankita Lokhande" HREF="http://www.bollywoodmovies.us/actress/ankita_lokhande/bollywood_ankita_lokhande.html">Ankita Lokhande</A> (Known as Archana in Pavitra Rishta), Ragini Khanna (TV Actress, Known as Suhana in Sasural Genda Phool), Shekhar Suman (Actor/Comedian), Mahii Vij (Actress Known as Nakusha in Laagi Tujhse Lagan), Meiyang Chang (Singer,Actor (Indian Idol 3 Contestant)), Akhil Kumar Boxer (Winner of Arjun Award), Yana Gupta (Actress/Model), Krushna Abhishek (Stand-Up Comedian From Comedy Circus), Renuka Shahane (Film Actress/TV Star), and Dayanand Shetty (Known as Senior Inspector Daya in C.I.D./TV actor).|g
