s|TAG_META_TITLE|Ashutosh Gowariker|g
s|TAG_META_KEYWORDS|ashutosh gowariker, |g
s|TAG_META_DESCRIPTION|ashutosh gowariker|g
#
s|TAG_BIOGRAPHY_1|<b>Ashutosh Gowariker</b> |g
s|TAG_BIOGRAPHY_OTHER_FACTS||g
#
s|TAG_BIO_LATEST_NEWS|<b>Deepika Padukone Joins Cast Of Khelein Gay Hum Jee Jaan Se</b> <br> Date: <A ALT="" TITLE="Deepika Padukone Joins Cast Of Khelein Gay Hum Jee Jaan Se" HREF="http://www.bollywoodmovies.us/news/2009/11_02_2009.html">11/08/2009</A>: <br> <A ALT="" TITLE="Deepika Padukone" HREF="http://www.bollywoodmovies.us/actress/deepika_padukone/bollywood_deepika_padukone.html">Deepika Padukone</A> has joined the cast of Khelein Gay Hum Jee Jaan Se to star opposite <A ALT="" TITLE="Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html">Abhishek Bachchan</A> . The movie is being directed by <A ALT="" TITLE="Ashutosh Gowariker" HREF="http://www.bollywoodmovies.us/director/ashutosh_gowariker/bollywood_ashutosh_gowariker.html">Ashutosh Gowariker</A> . Just recently <A ALT="" TITLE="Asin Thottumkal" HREF="http://www.bollywoodmovies.us/actress/asin_thottumkal/bollywood_asin_thottumkal.html">Asin Thottumkal</A> stepped out of the movie and now Deepika has stepped in.|g
#
s|TAG_BIO_2008_LATEST_NEWS|<b>Jodha Akbar A Big Success</b> <br> Date: <A ALT="" TITLE="Jodha Akbar A Big Success" HREF="http://www.bollywoodmovies.us/news/2008/03_17_2008.html">03/20/2008</A>: <br> <A ALT="" TITLE="Jodha Akbar, Jodhaa Akbar (2007)" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/jodha_akbar.html">Jodha Akbar (2008)</A> has had a great start for the movie as well as for Bollywood in 2008. The movie has grossed over Rs 120 crore worldwide since its release one month ago. Of that Rs 90 crores from within India and the remaining from the rest of the world. The movie stars the Dhoom 2 pair of <A ALT="" TITLE="Hrithik Roshan" HREF="http://www.bollywoodmovies.us/actor/hrithik_roshan/bollywood_hrithik_roshan.html">Hrithik Roshan</A> and <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_bachchan/bollywood_aishwarya_bachchan.html">Aishwarya Rai Bachchan</A> and the Oscar nominated director <A ALT="" TITLE="Ashutosh Gowariker" HREF="http://www.bollywoodmovies.us/director/ashutosh_gowariker/bollywood_ashutosh_gowariker.html">Ashutosh Gowariker</A> . Ashutosh has previosly directed Lagaan and Swades. Even with the bans in several Indian states that was faced by the movie, the movie did very well in the opening weeks. The film was released on 1000 screens of which 400 were through digital cinemas within India. The movie was dubbed in Hindi, Telegu, and Tamil and released in 25 countries in North America, Europe, Asia and West Asia.|g
