s|TAG_META_TITLE|Irfan Khan|g
s|TAG_META_KEYWORDS|irfan khan, |g
s|TAG_META_DESCRIPTION|irfan khan|g
#
s|TAG_BIOGRAPHY_1|<b>Irfan Khan</b> |g
s|TAG_BIOGRAPHY_OTHER_FACTS||g
#
s|TAG_BIO_2006_LATEST_NEWS||g
#
s|TAG_BIO_2008_LATEST_NEWS|<b>Irrfan Khan Opposite Natalie Portman</b> <br> Date: <A ALT="" TITLE="Irrfan Khan Opposite Natalie Portman" HREF="http://www.bollywoodmovies.us/news/2008/02_25_2008.html">02/28/2008</A>: <br> <A ALT="" TITLE="Irrfan Khan" HREF="http://www.bollywoodmovies.us/actor/irfan_khan/bollywood_irfan_khan.html">Irrfan Khan</A> has been signed by Mira Nair to star opposite Hollywood star <A ALT="" TITLE="Natalie Portman" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/natalie_portman/celebrites_natalie_portman.html">Natalie Portman</A> . The film is titled Kosher Vegetarian, and is directed by Mira Nair. The movie is about a love story between a Gujarati guy (<A ALT="" TITLE="Irrfan Khan" HREF="http://www.bollywoodmovies.us/actor/irfan_khan/bollywood_irfan_khan.html">Irrfan Khan</A>) and a Jewish girl (<A ALT="" TITLE="Natalie Portman" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/natalie_portman/celebrites_natalie_portman.html">Natalie Portman</A>). Just recently Irrfan won the Filmfare Best Supporting Actor award for his performance in Anurag Basu's <A ALT="" TITLE="Life...In a Metro (2007)" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/metro.html">Life...In a Metro (2007)</A> . During which time Irrfan was at the Spirit Awards being held in California, USA, were he was nominated for Best Supporting Actor for his role in Mira Nair's <A ALT="" TITLE="The Namesake (2007)" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/the_namesake.html">The Namesake (2007)</A> .|g
#
s|TAG_BIO_LATEST_NEWS|<b>Preity Zinta to play gangster in next film?</b> <br> Date: <A ALT="" TITLE="Preity Zinta to play gangster in next film?" HREF="http://www.bollywoodmovies.us/news/2011/04_25_2011.html">04/26/2011</A>: <br> <A ALT="" TITLE="Preity Zinta" HREF="http://www.bollywoodmovies.us/actress/preity_zinta/bollywood_preity_zinta.html">Preity Zinta</A> has been keeping herself busy with her Indian Premier League (IPL) cricket team, Kings XI Punjab team and her TV show, but now it seems that she has been offered a role in a film directed by Tigmanshu Dhulia. Preity has read the script and has agreed to work in the film but has not formly signed as she is away from Mumbai. Per the script she is to play a gangster, with the film provisionally titled Jai Ramji. Others who will be in the movie include <A ALT="" TITLE="Irfan Khan" HREF="http://www.bollywoodmovies.us/actor/irfan_khan/bollywood_irfan_khan.html">Irfan Khan</A> , <A ALT="" TITLE="Arjun Rampal" HREF="http://www.bollywoodmovies.us/actor/arjun_rampal/bollywood_arjun_rampal.html">Arjun Rampal</A> and Randeep Hooda. Preity was last seen in <A ALT="" TITLE="Main Aur Mrs Khanna Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/main_aur_mrs_khanna.html">Main Aur Mrs Khanna (2008)</A> , which costarred <A ALT="" TITLE="Salman Khan" HREF="http://www.bollywoodmovies.us/actor/salman_khan/bollywood_salman_khan.html">Salman Khan</A> and <A ALT="" TITLE="Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor.html">Kareena Kapoor</A> . And her latest film <A ALT="" TITLE="Har Pall Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2007/har_pall.html">Har Pall (2007)</A> is still awaiting release after costar <A ALT="" TITLE="Shiney Ahuja" HREF="http://www.bollywoodmovies.us/actor/shiney_ahuja/bollywood_shiney_ahuja.html">Shiney Ahuja</A> was imprisoned for sexual assault.|g

