s|TAG_META_TITLE|Karishma Kapoor|g
s|TAG_META_KEYWORDS|karishma kapoor, |g
s|TAG_META_DESCRIPTION|karishma kapoor|g
#
s|TAG_BIOGRAPHY_1|<b>Karishma Kapoor</b> |g
s|TAG_BIOGRAPHY_OTHER_FACTS|NEED_TO_UPDATE|g
#
s|TAG_BIO_LATEST_NEWS|<b>Karishma Kapoor To Make Bollywood Comeback With Dangerous Ishq</b> <br> Date: <A ALT="" TITLE="Karishma Kapoor To Make Bollywood Comeback With Dangerous Ishq" HREF="http://www.bollywoodmovies.us/news/2011/06_13_2011.html">06/14/2011</A>: <br> <A ALT="" TITLE="Karishma Kapoor" HREF="http://www.bollywoodmovies.us/actress/karishma_kapoor/bollywood_karishma_kapoor.html">Karishma Kapoor</A> will be making a Bollywood comeback with Vikram Bhatt 3D thriller <A ALT="" TITLE="Dangerous Ishq Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2011/dangerous_ishq.html">Dangerous Ishq (2011)</A> . Karisma Kapoor whose last seen in Bollywood movie with her appearance in Suneel Darshan's Mere Jeevan Saathi in 2002.|g
#
#
s|TAG_BIO_2008_LATEST_NEWS|<b>Karishma Kapoor To Be A Judge On Nach Baliye 4</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Karishma Kapoor To Be A Judge On Nach Baliye 4" HREF="http://www.bollywoodmovies.us/news/2008/10_06_2008.html">10/10/2008</A>: </font> <br> <A ALT="" TITLE="Karishma Kapoor" HREF="http://www.bollywoodmovies.us/actress/karishma_kapoor/bollywood_karishma_kapoor.html">Karishma Kapoor</A> has been out of the Bollywood film industry for a while and now is coming to the small screen. Karishma, along with choreographer and director Farah Khan and actor <A ALT="" TITLE="Arjun Rampal" HREF="http://www.bollywoodmovies.us/actor/arjun_rampal/bollywood_arjun_rampal.html">Arjun Rampal</A> to judge the season four of the dance show, which will air on Friday and Saturday at 8 pm on Star Plus from October 10, 2008.|g
#
s|TAG_BIO_2006_LATEST_NEWS|<b>Karisma Kapoor On The Small Screen</b> <br> Date: <A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2006/07_31_2006.html">08/03/2006</A> <br> <A ALT="" TITLE="Karishma Kapoor" HREF="http://www.bollywoodmovies.us/actress/karishma_kapoor/bollywood_karishma_kapoor.html">Karishma Kapoor</A> has been signed as one of the judges by Sony Entertainment television for their upcoming dance show called Jhalak Dikhla Jaa along with Farah Khan, the third judge has yet not been finalized. <A ALT="" TITLE="Karishma Kapoor" HREF="http://www.bollywoodmovies.us/actress/karishma_kapoor/bollywood_karishma_kapoor.html">Karishma Kapoor</A> was previously seen in the TV soap called Karishma and her Bollywood film, <A ALT="" TITLE="Zamaanat Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2006/zamaanat.html">Zamaanat</A> , that has been delayed for a while will soon be released. The movie stars <A ALT="" TITLE="Karishma Kapoor" HREF="http://www.bollywoodmovies.us/actress/karishma_kapoor/bollywood_karishma_kapoor.html">Karishma Kapoor</A> , Arshad Warsi and <A ALT="" TITLE="Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan.html">Amitabh Bachchan</A>.|g