s|TAG_META_TITLE|Kim Sharma|g
s|TAG_META_KEYWORDS|kim sharma, |g
s|TAG_META_DESCRIPTION|kim sharma|g
#
s|TAG_BIOGRAPHY_1|<b>Kim Sharma</b> was born on January 21, 1980 in Ahmednagar, India. She is a Indian actress and model.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Kim is the brand ambassador of Olay in India.<BR>|g
#
s|TAG_BIO_LATEST_NEWS|<b>Kim Sharma On Cover Of Maxim</b> <br> Date: <A ALT="" TITLE="Kim Sharma On Cover Of Maxim" HREF="http://www.bollywoodmovies.us/news/2008/01_14_2008.html">01/19/2008</A>: <br> <A ALT="" TITLE="Kim Sharma" HREF="http://www.bollywoodmovies.us/actress/kim_sharma/bollywood_kim_sharma.html">Kim Sharma</A> will be the next Bollywood film actress to be on the cover of <A ALT="" TITLE="Maxim India" HREF="http://www.bollywoodmovies.us/info/maxim_magazine.html">Maxim India</A> . Kim will be featured on the January 2008 cover of 2nd Anniversay Mega Issue of Maxim Magazine with many other picture within the magazine. Kim will join other Bollywood stars who have already made there presence in Maxim India, and they include such stars as <A ALT="" TITLE="Malaika Arora Khan" HREF="http://www.bollywoodmovies.us/actress/malaika_arora/bollywood_malaika_arora.html">Malaika Arora Khan</A> , <A ALT="" TITLE="Celina Jaitley" HREF="http://www.bollywoodmovies.us/actress/celina_jaitley/bollywood_celina_jaitley.html">Celina Jaitley</A> , <A ALT="" TITLE="Mallika Sherawat" HREF="http://www.bollywoodmovies.us/actress/mallika_sherawat/bollywood_mallika_sherawat.html">Mallika Sherawat</A> , <A ALT="" TITLE="Amisha Patel" HREF="http://www.bollywoodmovies.us/actress/amisha_patel/bollywood_amisha_patel.html">Amisha Patel</A> <A ALT="" TITLE="Shilpa Shetty" HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty.html">Shilpa Shetty</A> , <A ALT="" TITLE="Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor.html">Kareena Kapoor</A> and <A ALT="" TITLE="Priyanka Chopra" HREF="http://www.bollywoodmovies.us/actress/priyanka_chopra/bollywood_priyanka_chopra.html">Priyanka Chopra</A> .|g
