s|TAG_META_TITLE|Ritesh Deshmukh|g
s|TAG_META_KEYWORDS|ritesh deshmukh, |g
s|TAG_META_DESCRIPTION|ritesh deshmukh|g
#
s|TAG_BIOGRAPHY_1|<b>Ritesh Deshmukh</b> was born December 17, 1978 in Latur, Maharashtra, India.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Ritesh is an actor in the Indiam film industry.|g
#
s|TAG_BIO_LATEST_NEWS||g
#
s|TAG_BIO_2011_LATEST_NEWS|<b>Genelia Dsouza And Ritesh Deshmukh Officially Engaged</b> <br> Date: <A ALT="" TITLE="Genelia Dsouza And Ritesh Deshmukh Officially Engaged" HREF="http://www.bollywoodmovies.us/news/2011/10_10_2011.html">10/13/2011</A>: <br> Bollywood actress <A ALT="" TITLE="Genelia Dsouza" HREF="http://www.bollywoodmovies.us/actress/genelia_dsouza/bollywood_genelia_dsouza.html">Genelia Dsouza</A> and Bollywood actor <A ALT="" TITLE="Ritesh Deshmukh" HREF="http://www.bollywoodmovies.us/actor/ritesh_deshmukh/bollywood_ritesh_deshmukh.html">Ritesh Deshmukh</A> are officially engaged. The engagement was held at Riteish's father and former Maharashtra CM Vilasrao Deshmukh's residence. The two have been dating each other for almost seven years.|g
#
s|TAG_BIO_2009_LATEST_NEWS|<b>Aishwarya Rai Bachchan And Sonam Kapoor To Perform At IIFA 2009</b> <br> Date: <A ALT="" TITLE="Aishwarya Rai Bachchan And Sonam Kapoor To Perform At IIFA 2009" HREF="http://www.bollywoodmovies.us/news/2009/05_25_2009.html">05/29/2009</A>: <br> <A ALT="" TITLE="Aishwarya Rai (Aishwarya Bachchan)" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A> , <A ALT="" TITLE="Sonam Kapoor" HREF="http://www.bollywoodmovies.us/actress/sonam_kapoor/bollywood_sonam_kapoor.html">Sonam Kapoor</A> , and <A ALT="" TITLE="Kareena Kapoor" HREF="http://www.bollywoodmovies.us/actress/kareena_kapoor/bollywood_kareena_kapoor.html">Kareena Kapoor</A> . are going to be performing on stage at the IIFA Awards in Macau on June 11, 2009. The IIFA awards will be hosted by <A ALT="" TITLE="Riteish Deshmukh" HREF="http://www.bollywoodmovies.us/actor/ritesh_deshmukh/bollywood_ritesh_deshmukh.html">Riteish Deshmukh</A> , <A ALT="" TITLE="Lara Dutta" HREF="http://www.bollywoodmovies.us/actress/lara_dutta/bollywood_lara_dutta.html">Lara Dutta</A> and Boman Irani.|g
#
s|TAG_BIO_2008_LATEST_NEWS|<b>The Bachchan's 'Unforgettable' World Tour</b> <br> Date: <A ALT="" TITLE="The Bachchan's Unforgettable World Tour" HREF="http://www.bollywoodmovies.us/news/2008/05_26_2008.html">05/28/2008</A>: <br> The Bachchan's are in preparation for their world tour called <A ALT="" TITLE="Unforgettable Tour 2008" HREF="http://www.bollywoodmovies.us/info/bollywood_concert.html">Unforgettable Tour</A>, . The tour is set to being on July 18, 2008 in Toronto followed by performances at Trinidad, Tobago, Houston, Atlantic City, New York, Vancouver, and London. Currently <A ALT="" TITLE="Abhishek Bachchan" HREF="http://www.bollywoodmovies.us/actor/abhishek_bachchan/bollywood_abhishek_bachchan.html">Abhishek Bachchan</A>, <A ALT="" TITLE="Aishwarya Rai Bachchan" HREF="http://www.bollywoodmovies.us/actress/aishwarya_rai/bollywood_aishwarya_rai.html">Aishwarya Rai Bachchan</A>, and <A ALT="" TITLE="Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan.html">Amitabh Bachchan</A> are rehearsing the performances at a hall in Juhu, <A ALT="" TITLE="Maharashtra Mumbai" HREF="http://www.bollywoodmovies.us/Regional/India/Maharashtra/Mumbai/Mumbai.html">Mumbai</A> . Aishwarya will be performaing the hit 'Dola re..' number from <A ALT="" TITLE="Devdas Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2002/devdas.html">Devdas (2002)</A> with <A ALT="" TITLE="Madhuri Dixit" HREF="http://www.bollywoodmovies.us/actress/madhuri_dixit/bollywood_madhuri_dixit.html">Madhuri Dixit</A>, . The Bachchan family trio will also be performing the famous song 'Kajra re' from the hit movie <A ALT="" TITLE="Bunty Aur Babli Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2005/bunty_aur_babli.html">Bunty Aur Babli (2005)</A> . Others joining the tour include Bollywood actors <A ALT="" TITLE="Preity Zinta" HREF="http://www.bollywoodmovies.us/actress/preity_zinta/bollywood_preity_zinta.html">Preity Zinta</A>, , <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A> and <A ALT="" TITLE="Riteish Deshmukh" HREF="http://www.bollywoodmovies.us/actor/ritesh_deshmukh/bollywood_ritesh_deshmukh.html">Riteish Deshmukh</A> , choreographer Shiamak Davar and music duo of <A ALT="" TITLE="Vishal Dadlani" HREF="http://www.bollywoodmovies.us/music_director/vishal_dadlani/bollywood_vishal_dadlani_filmography.html">Vishal Dadlani</A> and <A ALT="" TITLE="Shekhar Ravjiani" HREF="http://www.bollywoodmovies.us/music_director/shekhar_ravjiani/bollywood_shekhar_ravjiani_filmography.html">Shekhar Ravjiani</A> .|g
