s|TAG_META_TITLE|Sameer|g
s|TAG_META_KEYWORDS|sameer, |g
s|TAG_META_DESCRIPTION|sameer|g
#
s|TAG_BIOGRAPHY_1|<b>Sameer</b> |g
s|TAG_BIOGRAPHY_OTHER_FACTS|NEED_TO_UPDATE|g
#
s|TAG_BIO_LATEST_NEWS|NEED_TO_UPDATE|g