s|TAG_META_TITLE|Shamita Shetty|g
s|TAG_META_KEYWORDS|Shamita Shetty, |g
s|TAG_META_DESCRIPTION|Shamita Shetty|g
#
s|TAG_BIOGRAPHY_1|<b>Shamita Shetty</b> was born on 2 February 1979 in <A ALT="" TITLE="Karnataka Mangalore" HREF="http://www.bollywoodmovies.us/regional/india/karnataka/mangalore/mangalore.html">Mangalore</A>, India.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Shamita is an Indian actress. She is Bollywood actress <A ALT="" TITLE="Shilpa Shetty" HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty.html">Shilpa Shetty</A> younger sister.|g
#
s|TAG_BIO_LATEST_NEWS|<b>Bigg Boss 3 Contestants</b> <br> Date: <A ALT="" TITLE="Bigg Boss 3 Contestants" HREF="http://www.bollywoodmovies.us/news/2009/10_05_2009.html">10/05/2009</A>: <br> The list of contestants for the new season of <A ALT="" TITLE="Bigg Boss 3" HREF="http://www.bollywoodmovies.us/tv_shows/bigg_boss/bigg_boss.html">Bigg Boss 3</A> on tv channel Colors have been announced. The show will be hosted by <A ALT="" TITLE="Amitabh Bachchan" HREF="http://www.bollywoodmovies.us/actor/amitabh_bachchan/bollywood_amitabh_bachchan.html">Amitabh Bachchan</A> . The list includes Bollywood movie actress <A ALT="" TITLE="Sherlyn Chopra" HREF="http://www.bollywoodmovies.us/actress/sherlyn_chopra/bollywood_sherlyn_chopra.html">Sherlyn Chopra</A> , Shilpa's little sister <A ALT="" TITLE="Shamita Shetty" HREF="http://www.bollywoodmovies.us/actress/shamita_shetty/bollywood_shamita_shetty.html">Shamita Shetty</A> . Aditi Gowitrikar a former Mrs World 2001, ex-Gladrags champion who also starred on first season of Khatron Ke Khiladi. Music director Ismail Darbar sho provided hit songs from Hum Dil De Chuke Sanam, Tera Jadoo Chal Gaya and <A ALT="" TITLE="Devdas Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2002/devdas.html">Devdas (2002)</A> . Jaya Sawant, mother of Rakhi Sawant. German super model, singer and actress Claudia Ciesla. Former Miss India and Bollywood actress from the the 80s Poonam Dhillon. Comedian Raju Srivastav, designer Rohit Varma, Kamaal R Khan, Vindoo Dara Singh, and the married couple Bakhtiyar and Tanaz Irani.<br><hr size="1" width="100%">|g
#
s|TAG_BIO_2008_LATEST_NEWS|<b>Shilpa Shetty Turns Producer</b> <br> Date: <A ALT="" TITLE="Shilpa Shetty Turns Producer" HREF="http://www.bollywoodmovies.us/news/2008/07_07_2008.html">07/09/2008</A>: <br> <A ALT="" TITLE="Shilpa Shetty" HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty.html">Shilpa Shetty</A> has turned into an entrepreneur by setting up her won production company named, Shilpa Shetty Global Productions. The first movie to be produced by the new production house will be the film named <A ALT="" TITLE="VIP Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/vip.html">VIP (2008)</A> , which will also be co produced by UTV Motion Pictures and directed by Manish Jha. The movie will star Shilpa herself, along with <A ALT="" TITLE="Bipasha Basu" HREF="http://www.bollywoodmovies.us/actress/bipasha_basu/bollywood_bipasha_basu.html">Bipasha Basu</A>. While Shilpa’s sister, <A ALT="" TITLE="Shamita Shetty" HREF="http://www.bollywoodmovies.us/actress/shamita_shetty/bollywood_shamita_shetty.html">Shamita Shetty</A> , will not be seen on the screen in the movie but will play key role behind the scene as she is the creative producer for the film.|g
