s|TAG_META_TITLE|Shruti Haasan|g
s|TAG_META_KEYWORDS|shruti haasan, |g
s|TAG_META_DESCRIPTION|shruti haasan|g
#
s|TAG_BIOGRAPHY_1|<b>Shruti Haasan</b> was born on January 28, 1986 in Chennai, India. She is an actress and singer in India. She is the daugther of Kamal Haasan and Sarika.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS||g
#
s|TAG_BIO_LATEST_NEWS|<b>Imran Khan In Cape Town For Luck</b> <br> Date: <A ALT="" TITLE="Imran Khan In Cape Town For Luck" HREF="http://www.bollywoodmovies.us/news/2008/09_15_2008.html">09/17/2008</A>: <br> <A ALT="" TITLE="Imran Khan" HREF="http://www.bollywoodmovies.us/actor/imran_khan/bollywood_imran_khan.html">Imran Khan</A> is currently in Cape Town, Africa to shot for movie <A ALT="" TITLE="Luck Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/luck.html">Luck (2008)</A> being directed by Soham Shah. The movie also stars <A ALT="" TITLE="Shruti Haasan" HREF="http://www.bollywoodmovies.us/actress/shruti_haasan/bollywood_shruti_haasan.html">Shruti Haasan</A> , <A ALT="" TITLE="Sanjay Dutt" HREF="http://www.bollywoodmovies.us/actor/sanjay_dutt/bollywood_sanjay_dutt.html">Sanjay Dutt</A> , Mithun Chakraborty, Ravi Kissen and Danny Denzongpa.<br><hr size="1" width="100%"> <b>Shruti Haasan To Make Bollywood Debut</b> <br> Date: <A ALT="" TITLE="Shruti Haasan To Make Bollywood Debut" HREF="http://www.bollywoodmovies.us/news/2008/06_02_2008.html">06/05/2008</A>: <br> Kamal Haasan's daughter <A ALT="" TITLE="Shruti Haasan" HREF="http://www.bollywoodmovies.us/actress/shruti_haasan/bollywood_shruti_haasan.html">Shruti Haasan</A> is all set to make her Bollywood film debut. Shruti has been signed for the movie <A ALT="" TITLE="Luck Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/luck.html">Luck (2008)</A> to play opposite <A ALT="" TITLE="Imran Khan" HREF="http://www.bollywoodmovies.us/actor/imran_khan/bollywood_imran_khan.html">Imran Khan</A> , <A ALT="" TITLE="Aamir Khan" HREF="http://www.bollywoodmovies.us/actor/aamir_khan/bollywood_aamir_khan.html">Aamir Khan</A> 's nephew. The film will be directed by Soham Shah with music by Salim Suleiman. The movie also stars <A ALT="" TITLE="Sanjay Dutt" HREF="http://www.bollywoodmovies.us/actor/sanjay_dutt/bollywood_sanjay_dutt.html">Sanjay Dutt</A> , Mithun Chakraborty, Danny Denzongpa, Ravi Kissen and Rati Agnihotri and is set to begin filming in early July in South Africa.|g
