s|TAG_META_TITLE|Twinkle Khanna|g
s|TAG_META_KEYWORDS|Twinkle Khanna, |g
s|TAG_META_DESCRIPTION|Twinkle Khanna|g
#
s|TAG_BIOGRAPHY_1|<b>Twinkle Khanna</b> was born on December 29, 1974 in Pune, Maharashtra, India.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Twinkle is an Indian actress. Twinkle is the wife of BOllywood actor <A ALT="" TITLE="Chandni Chowk To China, Made In China, CC2C Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/chandni_chowk_to_china.html">Chandni Chowk To China, Made In China, CC2C (2009)</A>.|g
#
s|TAG_BIO_LATEST_NEWS|<b>Akshay Kumar and Wife Twinkle Khanna Could Be Arrested Soon</b> <br> Date: <A ALT="" TITLE="Akshay Kumar and Wife Twinkle Khanna Could Be Arrested Soon" HREF="http://www.bollywoodmovies.us/news/2009/04_06_2009.html">04/08/2009</A>: <br> <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A> and his wife <A ALT="" TITLE="Twinkle Khanna" HREF="http://www.bollywoodmovies.us/actress/twinkle_khanna/bollywood_twinkle_khanna.html">Twinkle Khanna</A> and the organizers of Lakme Fashion Week could be arrested soon in response to the complained registered by social activist, Anil Nair. The event in question is the unbuttoning of Akshay's pants buttons by Twinkle at the Lakme Fashion Week last week. Akshay, is the brand ambassador for Levi’s unbuttoned jeans, and walking the ramp at the fashion show for designer Tarun Tahiliani and approached wife Twinkle and asked her to unbutton his jeans. Given the major box office successes given by Akshay in the past year, has not held on this year. Akshay's first two releases of the year 2009, <A ALT="" TITLE="Chandni Chowk To China, Made In China, CC2C Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/chandni_chowk_to_china.html">Chandni Chowk To China, Made In China, CC2C (2009)</A> and <A ALT="" TITLE="Tasveer Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2009/tasveer.html">Tasveer (2009)</A> , have not done well at the box office and now must wait to see what happens to his upcoming movie, with some high potentinal, movie release of <A ALT="" TITLE="Blue Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/blue.html">Blue (2009)</A> and <A ALT="" TITLE="Kambakth Ishq Movie Review" HREF="http://www.bollywoodmovies.us/movie_reviews/2008/kambakth_ishq.html">Kambakth Ishq (2009)</A> in the coming months.|g
