s|TAG_META_TITLE|Paris Hilton|g
s|TAG_META_KEYWORDS|paris hilton, |g
s|TAG_META_DESCRIPTION|paris hilton|g
#
s|TAG_BIOGRAPHY_1|<b>Paris Hilton</b> was born in New York City, New York, USA on 17 February 1981.|g
#
s|TAG_BIOGRAPHY_OTHER_FACTS|Filmography: Bottom's Up (2006). House of Wax (2005). The Hillz (2004). Raising Helen (2004). Las Vegas: Things That Go Jump in the Night (2004) TV Episode.|g
#
s|TAG_BIO_2007_LATEST_NEWS|<b>Paris Hilton Released From Jail</b> <br> Date: <A ALT="" TITLE="Hollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/06_25_2007.html">06/26/2007</A>: <br> The 26 years old <A ALT="" TITLE="Paris Hilton" HREF="http://www.bollywoodmovies.us/models/paris_hilton/models_paris_hilton.html">Paris Hilton</A> was released from Los Angeles County jail early Tuesday morning after a three-week stay. She is still on probation which ends March 2009, and must keep her her driver's license current and and stay out of trouble. She was initially arrested after she failed a sobriety test and later she was stopped driving with a suspended license.<br><hr size="1" width="100%"><A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/06_04_2007.html">06/04/2007</A>: <br> <A ALT="" TITLE="Paris Hilton" HREF="http://www.bollywoodmovies.us/hollywood/models/paris_hilton/models_paris_hilton_photo_gallery.html">Paris Hilton</A> reported to Los Angeles County jail to serve her three-week stay for violating probation in an alcohol-related reckless driving case. She was booked on Sunday and will serve 23 days out of the original 45 days asked by the judge because of good behavior. Eariler in the day she has attented MTV Movie Awards where she spoke to reporters briefly.<br><hr size="1" width="100%"><A ALT="" TITLE="Bollywood Movie News" HREF="http://www.bollywoodmovies.us/news/2007/05_07_2007.html">05/08/2007</A>: <br> <A ALT="" TITLE="Paris Hilton" HREF="http://www.bollywoodmovies.us/hollywood/models/paris_hilton/models_paris_hilton_photo_gallery.html">Paris Hilton</A> has been ordered by a California to report to county jail by June 5 for violating her probation in an previous alcohol-related reckless driving case. Paris is the star of reality TV show The Simple Life which is scheduled to premieres May 28.|g
#
s|TAG_BIO_LATEST_NEWS|<b>Paris Hilton Responds To Ad By Republican candidate John McCain</b> <br> Date: <A ALT="" TITLE="Paris Hilton Responds To Ad By Republican candidate John McCain" HREF="http://www.bollywoodmovies.us/news/2008/08_04_2008.html">08/07/2008</A>: <br> <A ALT="" TITLE="Paris Hilton" HREF="http://www.bollywoodmovies.us/models/paris_hilton/models_paris_hilton.html">Paris Hilton</A> who seems to always find a way to get into the news has now responded to some ads that were created by the Republican candidate John McCain. The ad compares the Democrat candidate Barack Obama to Hilton and Britney, which could suggest Obama was no more than a celebrity candidate. Paris also discussed her version of the energy policy which seems to be a hybrid of McCain's offshore oil drilling plan and Obama's incentives for new energy technology.|g
#
