s|TAG_META_TITLE|Avian Influenza (Bird Flu).|g
s|TAG_META_KEYWORDS|Avian Influenza (Bird Flu).|g
s|TAG_META_DESCRIPTION|Provide information and resources for Avian Influenza (Bird Flu).|g
#
s|TAG_INFO_CATEGORY|Bird Flue|g
#
s|TAG_TITLE_NAME|Information and Resouces for Avian Influenza (Bird Flu).|g
#
s|TAG_MAIN_INFO_1||g
#
s|TAG_LATEST_NEWS_2008|<table><!-- INDIA_STORY_START --> <tr HEIGHT=25 VALIGN="top" bgcolor="white"> <td WIDTH=100% align="left" valign="center"> <A ALT="" TITLE="Bird Flu West Bengal" HREF="http://www.bollywoodmovies.us/news/2008/01_21_2008.html">01/24/2008</A>: <br> Bird flu has hit West Bengal hard and the Authorities are having a hard time controlling it from spreading. Authorities fears that the bird flu could reach big cities like Kolkata. Currently the bird flu has been reported in nine of West Bengal's 19 districts with new reports that are coming from other districts. Indonesian man died who had tested positive for the H5N1 bird flu virus and the virus has also resurfaced in Europe. <hr size="1" width="100%"> </td> </tr> <!-- INDIA_STORY_END --></table>|g
#
s|TAG_LATEST_NEWS_2007|<table>03/21/2006: <A ALT="" TITLE="Bird flu killed five young people in Azerbaijan " TARGET="_blank" HREF="http://news.yahoo.com/fc/Health/Bird_Flu">Bird flu killed five young people in Azerbaijan </A> <br> Bird flu killed five young people in Azerbaijan .<br><hr size="1" width="100%">03/21/2006: <A ALT="" TITLE="Pakistan confirms bird flu" TARGET="_blank" HREF="http://www.alertnet.org/thenews/newsdesk/SP254970.htm">Pakistan confirms bird flu </A> <br> Pakistan confirms bird flu.<br><hr size="1" width="100%">03/21/2006: <A ALT="" TITLE="Second strain of bird flu found" TARGET="_blank" HREF="http://www.smh.com.au/news/world/second-strain-of-bird-flu-found-say-scientists/2006/03/21/1142703358739.html">Story_Title </A> <br> THE H5N1 bird flu in humans has evolved into two separate strains, a development that will complicate the search for a vaccine and the prevention of a pandemic, US researchers say.<br><hr size="1" width="100%"><b>Deadly bird flu found in Czech swans</b> <br> Date: 04/27/2006 <br> Czech Republic authorities say 12 cases of bird flu found in dead wild swans have been confirmed to be the deadly H5N1 strain of the virus. Thirteen EU countries have now had confirmed outbreaks of bird flu, which has killed more than 100 people in Asia since 2003.<br><hr size="1" width="100%"><b>Bird flu killed five young people in Azerbaijan</b> <br> Date: 03/21/2006 <br> on Tuesday the World Health Organization said that bird flu has killed five young people in Azerbaijan and that it was investigating whether some of the victims could have been infected collecting feathers from dead swans.<br><hr size="1" width="100%"><b>Pakistan confirms bird flu</b> <br> Date: 03/21/2006 <br> Pakistan on Tuesday became the latest country to confirm bird flu in two poultry flocks late last month was the H5N1 strain. Fears are growing the H5N1 flu virus will mutate and pass easily from one person to another but for the moment it remains hard for people to catch it from infected birds.<br><hr size="1" width="100%"><b>Egyptian treat a women believed to be infected with the virus</b> <br> Date: 03/21/2006 <br> Egyptian treat a women believed to be infected with the virus. This would be the country's third case in less than a week. Egypt's three suspected cases come from Qaloubiyah governorate. The woman in the latest case had handled infected birds and had slaughtered some of them earlier this month.</table>|g
