s|TAG_META_TITLE|Olympic Games, 2008 Summer Olympics, Beijing, China|g
s|TAG_META_KEYWORDS|Olympic Games, 2008 Summer Olympics|g
s|TAG_META_DESCRIPTION|Provide information and resources for Olympic Games and 2008 Summer Olympics in Beijing, China.|g
#
s|TAG_INFO_CATEGORY|Olympic Games|g
#
s|TAG_TITLE_NAME|Information and Resouces for Olympic Games and 2008 Summer Olympics in Beijing, China.|g
#
s|TAG_MAIN_INFO_1||g
#
s|TAG_LATEST_NEWS|<table> <!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center" colspan=2> <A ALT="" TITLE="Olympic US Basketball Team" HREF="http://www.bollywoodmovies.us/news/2008/08_04_2008.html">08/04/2008</A>: <br> The US basketball team wrapped up their final exhibition game with a win over Australia 87-76. Now they will be heading to Beijing for the <A ALT="" TITLE="2008 Summer Olympics" HREF="http://www.bollywoodmovies.us/info/olympic_games.html">2008 Summer Olympics</A> . The US basketball team was undefeated during their exhibition games but will have some tougher games during the Olympics. <A ALT="" TITLE="Dwyane Wade" HREF="http://www.bollywoodmovies.us/sports/basketball/dwyane_wade/basketball_dwyane_wade.html">Dwyane Wade</A> scored 22 points and <A ALT="" TITLE="LeBron James" HREF="http://www.bollywoodmovies.us/sports/basketball/lebron_james/basketball_lebron_james.html">LeBron James</A> . <hr size="1" width="100%"> </td> </tr> <!-- STORY_END -->  <!-- STORY_START --> <tr HEIGHT=25 bgcolor="white"> <td WIDTH=100% align="left" valign="center" colspan=2> <A ALT="" TITLE="2008 Summer Olympics, Beijing, China" HREF="http://www.bollywoodmovies.us/news/2008/04_28_2008.html">05/01/2008</A>: <br> This summer Beijing, China will host the <A ALT="" TITLE="2008 Summer Olympics" HREF="http://www.bollywoodmovies.us/info/olympic_games.html">2008 Summer Olympics</A> . The Opening ceremony will be held on August 8, 2008 and the Closing ceremony will be held on August 24, 2008. The 2008 Summer Olympics will consist of 302 evebts in 28 sports with over 10000 Athletes participating. The 2008 Summer Olympics have been in recent news with nations calling for boycotts due to some people being upset with China's involvement in the crisis in Darfur. Other concern related to environmental and health issues in and around Beijing have been raised due to the concern that it may potentially effect athletes health. <hr size="1" width="100%"> </td> </tr> <!-- STORY_END --> </table>|g
