s|TAG_META_TITLE|American Idol season 9|g
s|TAG_META_KEYWORDS|American Idol season 9|g
s|TAG_META_DESCRIPTION|We provided the latest information on TV Show American Idol season 9.|g
#
s|TAG_INFO_CATEGORY|TV_American_Idol_9|g
#
s|TAG_TITLE_NAME|American Idol season 9|g
#
s|TAG_MAIN_INFO_1|<!-- TAG_MAIN_INFO_1_START --> <!-- INDIAN_IDOL_START --> <table width=100% align="center" cellspacing="0" border="1" bordercolor="white" id="INDIAN_IDOL"> <tr> <td width=80% valign="top" align="left" bgcolor="white" colspan=2> <center><h3>The American Indian Idol Judges</h3></center> </td> </tr> <!-- JUDGE_START --> <TR> <TD WIDTH=10% BORDER="1" BORDERCOLOR="white"> </TD> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="white" VALIGN="top"> <b>Simon Cowell</b> was born 7 October 1959, and is a English artist and repertoire and as off 2008 was an executive for Sony BMG in the United Kingdom. <hr align="center" width="100%" size="2" color="#000080"> </TD> </TR> <!-- JUDGE_END --> <!-- JUDGE_START --> <TR> <TD WIDTH=10% BORDER="1" BORDERCOLOR="white"> </TD> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="white" VALIGN="top"> <b><A ALT="" TITLE="Ellen DeGeneres" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/ellen_degeneres/celebrites_ellen_degeneres.html">Ellen DeGeneres</A></b> was born January 26, 1958, and is a Emmy Award winning American stand up comedienne, television hostess and actress. She hosts the award winning syndicated talk show The Ellen DeGeneres Show, and in 2009 joined as one of the judge on American Idol's ninth season. <hr align="center" width="100%" size="2" color="#000080"> </TD> </TR> <!-- JUDGE_END --> <!-- JUDGE_START --> <TR> <TD WIDTH=10% BORDER="1" BORDERCOLOR="white"> </TD> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="white" VALIGN="top"> <b>Randy Jackson</b> was born on 23 June 1956 in Baton Rouge, Louisiana, U.S.A. He is a singer and television Personality. Since 2002, Jackson has been judging regularly on the Fox Network reality television series American Idol. <hr align="center" width="100%" size="2" color="#000080"> </TD> </TR> <!-- JUDGE_END --> <!-- JUDGE_START --> <TR> <TD WIDTH=10% BORDER="1" BORDERCOLOR="white"> </TD> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="white" VALIGN="top"> <b><A ALT="" TITLE="Kara DioGuardi" HREF="http://www.bollywoodmovies.us/hollywood/artists/kara_dioguardi/hollywood_kara_dioguardi.html">Kara DioGuardi</A></b> was born on 23 June 1956 in Baton Rouge, Louisiana, U.S.A. He is a record producer, singer and songwriter. She will join the American Idol panel of judge this year. She has written many international hit songs from 1999 to today and many have been nominated for the Grammy. <hr align="center" width="100%" size="2" color="#000080"> </TD> </TR> <!-- JUDGE_END --> </table> <!-- INDIAN_IDOL_END --> <!-- TAG_MAIN_INFO_1_END -->|g
#
s|TAG_MAIN_INFO_2|The ninth season of American Idol will premiere on __. |g
#
s|TAG_LATEST_NEWS|<!-- TAG_LATEST_NEWS_START --> <!-- LATEST_NEWS_START --> <table width=100% cellspacing="0" border="1" bordercolor="white" id="Latest News Table"> <tr> <td width=900 colspan=2 align=center bgcolor="#f0f8ff"> <h3>American Idol Season 9 Latest News and Headlines:</h3> </td> </tr> <tr> <td width=900 colspan=2> <!-- STORY_START --> <A HREF="http://www.bollywoodmovies.us/hollywood/celebrites/ellen_degeneres/celebrites_ellen_degeneres_photo_gallery_01.html"> <IMG SRC="http://www.bollywoodmovies.us/hollywood/celebrites/ellen_degeneres/pics/ellen_degeneres_01.jpg" ALT="Ellen DeGeneres" TITLE="Ellen DeGeneres" WIDTH="100" HEIGHT="100" BORDER="0"> </A> <b>Ellen DeGeneres To Joining American Idol As Fourth Judge</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Ellen DeGeneres To Joining American Idol As Fourth Judge" HREF="http://www.bollywoodmovies.us/news/2009/09_07_2009.html">09/10/2009</A>: </font> <br> After the whole summer of auditions to fill the fourth judges' chair, left vacant by <A ALT="" TITLE="Paula Abdul" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/paula_abdul/celebrites_paula_abdul.html">Paula Abdul</A> , it was announced that stand up comedienne, <A ALT="" TITLE="Ellen DeGeneres" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/ellen_degeneres/celebrites_ellen_degeneres.html">Ellen DeGeneres</A> would be joining the <A ALT="" HREF="http://www.bollywoodmovies.us/american_idol/american_idol_9.html" TITLE="TV Show American Idol 9">American Idol season 9</A> as the forth judge. As a non-singer, DeGeneres should provide some nice criticism and fill in the gaps with her funny comments. Ellen is already a busy woman serving as the host of her self-titled talk show, The Ellen DeGeneres Show, and she also is a face of Covergirl. <hr size="1" width="100%"> --> <!-- STORY_END --> <!-- STORY_START --> <!-- Date: MM/DD/2006 <br> Guest Stars: STAR_NAME <br> TAG_DESC Voted Off: STAR_NAME <hr size="1" width="100%"> --> <!-- STORY_END --> <!-- STORY_START --> <!-- Date: MM/DD/2006 <br> Guest Stars: STAR_NAME <br> TAG_DESC Voted Off: STAR_NAME <hr size="1" width="100%"> --> <!-- STORY_END --> </td> </tr> </table> <!-- LATEST_NEWS_END --> <!-- TAG_LATEST_NEWS_END -->|g
#
