s|TAG_META_TITLE|American Idol season 8|g
s|TAG_META_KEYWORDS|American Idol season 8|g
s|TAG_META_DESCRIPTION|We provided the latest information on TV Show American Idol season 8.|g
#
s|TAG_INFO_CATEGORY|TV_American_Idol_8|g
#
s|TAG_TITLE_NAME|American Idol season 8|g
#
s|TAG_MAIN_INFO_1|<!-- TAG_MAIN_INFO_1_START --> <!-- INDIAN_IDOL_START --> <table width=100% align="center" cellspacing="0" border="1" bordercolor="white" id="INDIAN_IDOL"> <tr> <td width=80% valign="top" align="left" bgcolor="white" colspan=2> <center><h3>The American Indian Idol Judges</h3></center> </td> </tr> <!-- JUDGE_START --> <TR> <TD WIDTH=10% BORDER="1" BORDERCOLOR="white"> </TD> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="white" VALIGN="top"> <b>Simon Cowell</b> was born 7 October 1959, and is a English artist and repertoire and as off 2008 was an executive for Sony BMG in the United Kingdom. <hr align="center" width="100%" size="2" color="#000080"> </TD> </TR> <!-- JUDGE_END --> <!-- JUDGE_START --> <TR> <TD WIDTH=10% BORDER="1" BORDERCOLOR="white"> </TD> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="white" VALIGN="top"> <b><A ALT="" TITLE="Paula Abdul" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/paula_abdul/celebrites_paula_abdul.html">Paula Abdul</A></b> was born 19 June 1962, and is an American singer, choreographer and dancer. She used to be a cheerleader for the Los Angeles Lakers NBA basketball team and met with good success with string of hits in the late 1980s and early 1990s. She then resurfaced in 2000, as judge on the television series American Idol. <hr align="center" width="100%" size="2" color="#000080"> </TD> </TR> <!-- JUDGE_END --> <!-- JUDGE_START --> <TR> <TD WIDTH=10% BORDER="1" BORDERCOLOR="white"> </TD> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="white" VALIGN="top"> <b>Randy Jackson</b> was born on 23 June 1956 in Baton Rouge, Louisiana, U.S.A. He is a singer and television Personality. Since 2002, Jackson has been judging regularly on the Fox Network reality television series American Idol. <hr align="center" width="100%" size="2" color="#000080"> </TD> </TR> <!-- JUDGE_END --> <!-- JUDGE_START --> <TR> <TD WIDTH=10% BORDER="1" BORDERCOLOR="white"> </TD> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="white" VALIGN="top"> <b><A ALT="" TITLE="Kara DioGuardi" HREF="http://www.bollywoodmovies.us/hollywood/artists/kara_dioguardi/hollywood_kara_dioguardi.html">Kara DioGuardi</A></b> was born on 23 June 1956 in Baton Rouge, Louisiana, U.S.A. He is a record producer, singer and songwriter. She will join the American Idol panel of judge this year. She has written many international hit songs from 1999 to today and many have been nominated for the Grammy. <hr align="center" width="100%" size="2" color="#000080"> </TD> </TR> <!-- JUDGE_END --> </table> <!-- INDIAN_IDOL_END --> <!-- TAG_MAIN_INFO_1_END -->|g
#
s|TAG_MAIN_INFO_2|The eighth season of American Idol will premiere on January 13, 2009. Season eight will be hosted by Simon Cowell, <A ALT="" TITLE="Paula Abdul" HREF="http://www.bollywoodmovies.us/hollywood/celebrites/paula_abdul/celebrites_paula_abdul.html">Paula Abdul</A>, and Randy Jackson along with <A ALT="" TITLE="Kara DioGuardi" HREF="http://www.bollywoodmovies.us/hollywood/artists/kara_dioguardi/hollywood_kara_dioguardi.html">Kara DioGuardi</A>.|g
