s|TAG_META_TITLE|TV Show, Bigg Boss 2|g
s|TAG_META_KEYWORDS|TV Show, Bigg Boss 2|g
s|TAG_META_DESCRIPTION|We provided the latest information on TV Show, Bigg Boss 2.|g
#
s|TAG_INFO_CATEGORY|TV_Bigg_Boss|g
#
s|TAG_TITLE_NAME|TV Show, Bigg Boss 2|g
#
s|TAG_MAIN_INFO_1|<!-- TAG_MAIN_INFO_1_START --> <!-- INDIAN_CONTESTANTS_START --> <table width=100% align="center" cellspacing="0" border="1" bordercolor="white" id="INDIAN_IDOL"> <tr> <td width=80% valign="top" align="left" bgcolor="white" colspan=2> <center><h3>Bigg Boss 2 Hosted By</h3></center> </td> </tr> <!-- JUDGE_START --> <TR> <TD WIDTH=10% BORDER="1" BORDERCOLOR="white"> </TD> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="white" VALIGN="top"> <A ALT="" TITLE="Shilpa Shetty" HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty.html">Shilpa Shetty</A> . <hr align="center" width="100%" size="2" color="#000080"> </TD> </TR> <!-- JUDGE_END --> </table> <!-- INDIAN_CONTESTANTS_END --> <!-- TAG_MAIN_INFO_1_END -->|g
#
s|TAG_MAIN_INFO_2| <!-- TAG_MAIN_INFO_2_START --><!-- SHOW_CONTESTANTS_START --> <table width=900 align="center" cellspacing="0" border="1" bordercolor="white" id="INDIAN_IDOL"> <tr> <td width=100% valign="top" align="left" bgcolor="white" colspan=2> <center><h3>List Of Bigg Boss 2 Female Contestants</h3></center> </td> </tr> <!-- CONTESTANTS_START --> <TR> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="#faebd7" VALIGN="top"> <table width=100% bgcolor="white" border="0" cellspacing="0" cellpadding="0" bordercolor="white"> <tr> <td width=30% valign="center"> <b><u>Ahsaan Qureshi</u></b> </td> <td width=15% valign="center"> <b>Age:</b> __ </td> <td width=25% valign="center"> <b>City:</b> </td> <td width=10% valign="center"> </td> <td width=20% valign="center" align="right"> <b>Status:</b> IN </td> </tr> <tr> <td width=100% valign="center" colspan=5 bgcolor="#F8F8F1"> <b>Biography:</b> </td> </tr> <tr> <td width=100% valign="center" align="right" colspan=5 bgcolor="#faebd7"> Evicted On </td> </tr> </table> </TD> </TR> <!-- CONTESTANTS_END --> <!-- CONTESTANTS_START --> <TR> <TD WIDTH=70% BORDER="1" BORDERCOLOR="white" bgcolor="#faebd7" VALIGN="top"> <table width=100% bgcolor="white" border="0" cellspacing="0" cellpadding="0" bordercolor="white"> <tr> <td width=30% valign="center"> <b><u>Ashutosh Kaushik</u></b> <BR> <b><u>Debojit Saha</u></b> <BR> <b><u>Elina Wadiwala</u></b> <BR> <b><u>Jade Goody</u></b> <BR> <b><u>Ketaki Dave</u></b> <BR> <b><u>Monica Bedi</u></b> <BR> <b><u>Payal Rohatgi</u></b> <BR> <b><u>Rahul Mahajan</u></b> <BR> <b><u>Raja Chaudhri</u></b> <BR> <b><u>Raja Chaudhri</u></b> <BR> <b><u>Sambhavana Seth</u></b> <BR> <b><u>Sanjay Nirupam</u></b> <BR> <b><u>Zulfi Syed </u></b> <BR> </td> <td width=15% valign="center"> </td> <td width=25% valign="center"> </td> <td width=10% valign="center"> </td> <td width=20% valign="center" align="right"> </td> </tr> <tr> <td width=100% valign="center" colspan=5 bgcolor="#F8F8F1"> </td> </tr> <tr> <td width=100% valign="center" align="right" colspan=5 bgcolor="#faebd7"> </td> </tr> </table> </TD> </TR> <!-- CONTESTANTS_END --> </table> <!-- SHOW_CONTESTANTS_END --> <!-- TAG_MAIN_INFO_2_END -->  |g
#
s|TAG_LATEST_NEWS|<A HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty_photo_gallery_02.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/shilpa_shetty/pics/shilpa_shetty_16.jpg" ALT="Shilpa Shetty" TITLE="Shilpa Shetty" WIDTH="100" HEIGHT="100" BORDER="0"> </A><b>Shilpa Shetty To Host Season 2 Of Big Boss</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Shilpa Shetty To Host Season 2 Of Big Boss" HREF="http://www.bollywoodmovies.us/news/2008/08_04_2008.html">08/07/2008</A>: </font> <br> <A ALT="" TITLE="Shilpa Shetty" HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty.html">Shilpa Shetty</A> the winner of the Big Brother UK, will be the host of <A ALT="" TITLE="Bigg Boss 2" HREF="http://www.bollywoodmovies.us/tv_shows/bigg_boss/bigg_boss.html">Bigg Boss 2</A> Indian version of the show. The show will star to air on TV on August 17, it will also make it the first reality show to be telecast on all seven days of the week. The show is have 14 people locked into a house under the surveillance of over 30 cameras for a period of three months. <br><hr size="1" width="100%">  <A HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty_photo_gallery_03.html"> <IMG SRC="http://www.bollywoodmovies.us/actress/shilpa_shetty/pics/shilpa_shetty_21.jpg" ALT="Shilpa Shetty" TITLE="Shilpa Shetty" WIDTH="100" HEIGHT="100" BORDER="0"> </A>  <b>Shilpa Shetty Could Host Season 2 Of Big Boss</b> <br> <font size="1" face="Verdana, Arial, Helvetica, sans-serif"> Date: <A ALT="" TITLE="Shilpa Shetty Could Host Season 2 Of Big Boss" HREF="http://www.bollywoodmovies.us/news/2008/07_28_2008.html">07/28/2008</A>: </font> <br> <A ALT="" TITLE="Shilpa Shetty" HREF="http://www.bollywoodmovies.us/actress/shilpa_shetty/bollywood_shilpa_shetty.html">Shilpa Shetty</A> the winner of the Big Brother UK, may be offered to host the next season of <A ALT="" TITLE="Bigg Boss 2" HREF="http://www.bollywoodmovies.us/tv_shows/bigg_boss/bigg_boss.html">Bigg Boss 2</A> in India. Bigg Boss was last year hosted by Arshad Warsi. If Shilpa chooses to host the show, she could be paid more then Rs 8 Crores. Bigg Boss (India) will start after <A ALT="" TITLE="Fear Factor Khatron Ke Khiladi" HREF="http://www.bollywoodmovies.us/tv_shows/fear_factor_khatron_ke_khiladi/fear_factor_khatron_ke_khiladi.html">Fear Factor Khatron Ke Khiladi</A>, , hosted by <A ALT="" TITLE="Akshay Kumar" HREF="http://www.bollywoodmovies.us/actor/akshay_kumar/bollywood_akshay_kumar.html">Akshay Kumar</A> , ends in August 2008. The new season of Bigg Boss will air on newly launched channel, Colors. |g
#
s|TAG_GOOGLE_ADLINKS|9774778087|g
