REM call create_resources_links_page.bat resources resources_kids_and_teens_entertainment.sed

call create_resources_main_page.bat resources resources

call create_resources_main_page.bat resources resources_directories
call create_resources_links_page.bat resources resources_directories_01